// filepath: src/AFG.Generators/GlobalUsings.cs
global using System;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.IO;
global using System.Linq;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;
global using AFG.Core.Enums;
global using AFG.Core.Models.Ast;
global using AFG.Core.Models.Common;
global using AFG.Core.Models.Logic;
global using AFG.Generators.Abstractions;
global using AFG.Generators.Models;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using Microsoft.CodeAnalysis.Formatting;
