// filepath: src/AFG.Generators/CSharpMarkup/AvaloniaMarkupExtensionsSource.cs
namespace AFG.Generators.CSharpMarkup;

/// <summary>
/// 提供純 C# Declarative UI 擴充方法原始碼，確保匯出之 Avalonia 專案具備完整流暢鏈式調用與強型別/字串資料綁定支援。
/// </summary>
public static class AvaloniaMarkupExtensionsSource
{
    public const string Code = """
    // <auto-generated />
    #nullable enable

    using System;
    using System.Collections.Generic;
    using Avalonia;
    using Avalonia.Controls;
    using Avalonia.Controls.Primitives;
    using Avalonia.Data;
    using Avalonia.Input;
    using Avalonia.Layout;
    using Avalonia.Media;

    namespace Avalonia.Controls;

    /// <summary>
    /// Avalonia C# Declarative UI Fluent 擴充方法集合。
    /// </summary>
    public static class AvaloniaMarkupExtensions
    {
        // 1. 幾何尺寸與外觀數值與資料綁定
        public static T Width<T>(this T control, double value) where T : Control { control.Width = value; return control; }
        public static T Width<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            control.Bind(Layoutable.WidthProperty, new Binding(path) { Mode = mode });
            return control;
        }

        public static T Height<T>(this T control, double value) where T : Control { control.Height = value; return control; }
        public static T Height<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            control.Bind(Layoutable.HeightProperty, new Binding(path) { Mode = mode });
            return control;
        }

        public static T MinWidth<T>(this T control, double value) where T : Control { control.MinWidth = value; return control; }
        public static T MinHeight<T>(this T control, double value) where T : Control { control.MinHeight = value; return control; }
        public static T MaxWidth<T>(this T control, double value) where T : Control { control.MaxWidth = value; return control; }
        public static T MaxHeight<T>(this T control, double value) where T : Control { control.MaxHeight = value; return control; }
        public static T Margin<T>(this T control, Thickness value) where T : Control { control.Margin = value; return control; }
        public static T HorizontalAlignment<T>(this T control, HorizontalAlignment value) where T : Control { control.HorizontalAlignment = value; return control; }
        public static T VerticalAlignment<T>(this T control, VerticalAlignment value) where T : Control { control.VerticalAlignment = value; return control; }

        public static T Opacity<T>(this T control, double value) where T : Control { control.Opacity = value; return control; }
        public static T Opacity<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            control.Bind(Visual.OpacityProperty, new Binding(path) { Mode = mode });
            return control;
        }

        public static T IsEnabled<T>(this T control, bool value) where T : Control { control.IsEnabled = value; return control; }
        public static T IsEnabled<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            control.Bind(InputElement.IsEnabledProperty, new Binding(path) { Mode = mode });
            return control;
        }

        public static T IsVisible<T>(this T control, bool value) where T : Control { control.IsVisible = value; return control; }
        public static T IsVisible<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            control.Bind(Visual.IsVisibleProperty, new Binding(path) { Mode = mode });
            return control;
        }

        public static T ZIndex<T>(this T control, int value) where T : Control { control.ZIndex = value; return control; }

        // 2. 容器附加屬性 (Attached Properties)
        public static T CanvasLeft<T>(this T control, double value) where T : Control { Canvas.SetLeft(control, value); return control; }
        public static T CanvasTop<T>(this T control, double value) where T : Control { Canvas.SetTop(control, value); return control; }
        public static T GridRow<T>(this T control, int value) where T : Control { Grid.SetRow(control, value); return control; }
        public static T GridColumn<T>(this T control, int value) where T : Control { Grid.SetColumn(control, value); return control; }
        public static T GridRowSpan<T>(this T control, int value) where T : Control { Grid.SetRowSpan(control, value); return control; }
        public static T GridColumnSpan<T>(this T control, int value) where T : Control { Grid.SetColumnSpan(control, value); return control; }
        public static T Dock<T>(this T control, Dock value) where T : Control { DockPanel.SetDock(control, value); return control; }

        // 3. 容器專屬擴充
        public static T Children<T>(this T panel, params Control[] children) where T : Panel
        {
            foreach (var child in children)
            {
                panel.Children.Add(child);
            }
            return panel;
        }

        public static Grid RowDefinitions(this Grid grid, params string[] definitions)
        {
            grid.RowDefinitions = global::Avalonia.Controls.RowDefinitions.Parse(string.Join(",", definitions));
            return grid;
        }

        public static Grid ColumnDefinitions(this Grid grid, params string[] definitions)
        {
            grid.ColumnDefinitions = global::Avalonia.Controls.ColumnDefinitions.Parse(string.Join(",", definitions));
            return grid;
        }

        public static StackPanel Orientation(this StackPanel panel, Orientation orientation)
        {
            panel.Orientation = orientation;
            return panel;
        }

        // 4. 控制項內容、文字與標題（數值與資料綁定雙支援）
        public static T Content<T>(this T control, object? content) where T : Control
        {
            if (control is ContentControl cc)
            {
                cc.Content = content;
            }
            else if (control is TextBlock tb)
            {
                tb.Text = content?.ToString();
            }
            else if (control is TextBox txt)
            {
                txt.Text = content?.ToString();
            }
            return control;
        }

        public static T Content<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            if (control is ContentControl cc)
            {
                cc.Bind(ContentControl.ContentProperty, new Binding(path) { Mode = mode });
            }
            else if (control is TextBlock tb)
            {
                tb.Bind(TextBlock.TextProperty, new Binding(path) { Mode = mode });
            }
            else if (control is TextBox txt)
            {
                txt.Bind(TextBox.TextProperty, new Binding(path) { Mode = mode });
            }
            return control;
        }

        public static T Text<T>(this T control, string? text) where T : Control
        {
            if (control is TextBlock tb)
            {
                tb.Text = text;
            }
            else if (control is TextBox txt)
            {
                txt.Text = text;
            }
            else if (control is ContentControl cc)
            {
                cc.Content = text;
            }
            return control;
        }

        public static T Text<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            if (control is TextBlock tb)
            {
                tb.Bind(TextBlock.TextProperty, new Binding(path) { Mode = mode });
            }
            else if (control is TextBox txt)
            {
                txt.Bind(TextBox.TextProperty, new Binding(path) { Mode = mode });
            }
            else if (control is ContentControl cc)
            {
                cc.Bind(ContentControl.ContentProperty, new Binding(path) { Mode = mode });
            }
            return control;
        }

        public static T Header<T>(this T control, object? header) where T : Control
        {
            if (control is HeaderedContentControl hcc)
            {
                hcc.Header = header;
            }
            return control;
        }

        public static T Header<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            if (control is HeaderedContentControl hcc)
            {
                hcc.Bind(HeaderedContentControl.HeaderProperty, new Binding(path) { Mode = mode });
            }
            return control;
        }

        public static T Padding<T>(this T control, Thickness padding) where T : Control
        {
            if (control is TemplatedControl tc)
            {
                tc.Padding = padding;
            }
            else if (control is Border b)
            {
                b.Padding = padding;
            }
            return control;
        }

        public static TextBox Watermark(this TextBox tb, string watermark) { tb.Watermark = watermark; return tb; }
        public static TextBox PlaceholderText(this TextBox tb, string placeholder) { tb.Watermark = placeholder; return tb; }

        public static T IsChecked<T>(this T control, bool isChecked) where T : Control
        {
            if (control is ToggleButton tb)
            {
                tb.IsChecked = isChecked;
            }
            return control;
        }

        public static T IsChecked<T>(this T control, string path, BindingMode mode = BindingMode.TwoWay) where T : Control
        {
            if (control is ToggleButton tb)
            {
                tb.Bind(ToggleButton.IsCheckedProperty, new Binding(path) { Mode = mode });
            }
            return control;
        }

        public static T Value<T>(this T control, double value) where T : Control
        {
            if (control is RangeBase rb)
            {
                rb.Value = value;
            }
            return control;
        }

        public static T Value<T>(this T control, string path, BindingMode mode = BindingMode.TwoWay) where T : Control
        {
            if (control is RangeBase rb)
            {
                rb.Bind(RangeBase.ValueProperty, new Binding(path) { Mode = mode });
            }
            return control;
        }

        public static T FontSize<T>(this T control, double size) where T : Control
        {
            if (control is TemplatedControl tc)
            {
                tc.FontSize = size;
            }
            else if (control is TextBlock tb)
            {
                tb.FontSize = size;
            }
            return control;
        }

        public static T FontSize<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            if (control is TemplatedControl tc)
            {
                tc.Bind(TemplatedControl.FontSizeProperty, new Binding(path) { Mode = mode });
            }
            else if (control is TextBlock tb)
            {
                tb.Bind(TextBlock.FontSizeProperty, new Binding(path) { Mode = mode });
            }
            return control;
        }

        public static Button Command(this Button btn, string path)
        {
            btn.Bind(Button.CommandProperty, new Binding(path));
            return btn;
        }

        public static T ItemsSource<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : ItemsControl
        {
            control.Bind(ItemsControl.ItemsSourceProperty, new Binding(path) { Mode = mode });
            return control;
        }

        public static T SelectedItem<T>(this T control, string path, BindingMode mode = BindingMode.TwoWay) where T : SelectingItemsControl
        {
            control.Bind(SelectingItemsControl.SelectedItemProperty, new Binding(path) { Mode = mode });
            return control;
        }

        public static T SelectedIndex<T>(this T control, string path, BindingMode mode = BindingMode.TwoWay) where T : SelectingItemsControl
        {
            control.Bind(SelectingItemsControl.SelectedIndexProperty, new Binding(path) { Mode = mode });
            return control;
        }
    }
    """;
}
