// filepath: src/AFG.Generators/CSharpMarkup/AvaloniaMarkupExtensionsSource.cs
namespace AFG.Generators.CSharpMarkup;

/// <summary>
/// 提供純 C# Declarative UI 擴充方法原始碼，確保匯出之 Avalonia 專案具備完整流暢鏈式調用支援。
/// </summary>
public static class AvaloniaMarkupExtensionsSource
{
    public const string Code = """
    // <auto-generated />
    #nullable enable

    using System;
    using System.Collections.Generic;
    using Avalonia;
    using Avalonia.Controls;
    using Avalonia.Controls.Primitives;
    using Avalonia.Data;
    using Avalonia.Input;
    using Avalonia.Layout;
    using Avalonia.Media;

    namespace Avalonia.Controls;

    /// <summary>
    /// Avalonia C# Declarative UI Fluent 擴充方法集合。
    /// </summary>
    public static class AvaloniaMarkupExtensions
    {
        // 1. 幾何尺寸與外觀
        public static T Width<T>(this T control, double value) where T : Control { control.Width = value; return control; }
        public static T Height<T>(this T control, double value) where T : Control { control.Height = value; return control; }
        public static T MinWidth<T>(this T control, double value) where T : Control { control.MinWidth = value; return control; }
        public static T MinHeight<T>(this T control, double value) where T : Control { control.MinHeight = value; return control; }
        public static T MaxWidth<T>(this T control, double value) where T : Control { control.MaxWidth = value; return control; }
        public static T MaxHeight<T>(this T control, double value) where T : Control { control.MaxHeight = value; return control; }
        public static T Margin<T>(this T control, Thickness value) where T : Control { control.Margin = value; return control; }
        public static T HorizontalAlignment<T>(this T control, HorizontalAlignment value) where T : Control { control.HorizontalAlignment = value; return control; }
        public static T VerticalAlignment<T>(this T control, VerticalAlignment value) where T : Control { control.VerticalAlignment = value; return control; }
        public static T Opacity<T>(this T control, double value) where T : Visual { control.Opacity = value; return control; }
        public static T IsEnabled<T>(this T control, bool value) where T : InputElement { control.IsEnabled = value; return control; }
        public static T IsVisible<T>(this T control, bool value) where T : Visual { control.IsVisible = value; return control; }
        public static T ZIndex<T>(this T control, int value) where T : Control { control.ZIndex = value; return control; }

        // 2. 容器附加屬性 (Attached Properties)
        public static T CanvasLeft<T>(this T control, double value) where T : Control { Canvas.SetLeft(control, value); return control; }
        public static T CanvasTop<T>(this T control, double value) where T : Control { Canvas.SetTop(control, value); return control; }
        public static T GridRow<T>(this T control, int value) where T : Control { Grid.SetRow(control, value); return control; }
        public static T GridColumn<T>(this T control, int value) where T : Control { Grid.SetColumn(control, value); return control; }
        public static T GridRowSpan<T>(this T control, int value) where T : Control { Grid.SetRowSpan(control, value); return control; }
        public static T GridColumnSpan<T>(this T control, int value) where T : Control { Grid.SetColumnSpan(control, value); return control; }
        public static T Dock<T>(this T control, Dock value) where T : Control { DockPanel.SetDock(control, value); return control; }

        // 3. 容器專屬擴充
        public static T Children<T>(this T panel, params Control[] children) where T : Panel
        {
            foreach (var child in children)
            {
                panel.Children.Add(child);
            }
            return panel;
        }

        public static Grid RowDefinitions(this Grid grid, params string[] definitions)
        {
            grid.RowDefinitions = global::Avalonia.Controls.RowDefinitions.Parse(string.Join(",", definitions));
            return grid;
        }

        public static Grid ColumnDefinitions(this Grid grid, params string[] definitions)
        {
            grid.ColumnDefinitions = global::Avalonia.Controls.ColumnDefinitions.Parse(string.Join(",", definitions));
            return grid;
        }

        public static StackPanel Orientation(this StackPanel panel, Orientation orientation)
        {
            panel.Orientation = orientation;
            return panel;
        }

        // 4. 控制項專屬內容與字級
        public static T Content<T>(this T control, object content) where T : ContentControl { control.Content = content; return control; }
        public static T Header<T>(this T control, object header) where T : HeaderedContentControl { control.Header = header; return control; }
        public static T Padding<T>(this T control, Thickness padding) where T : TemplatedControl { control.Padding = padding; return control; }
        public static Border Padding(this Border border, Thickness padding) { border.Padding = padding; return border; }

        public static TextBlock Text(this TextBlock tb, string text) { tb.Text = text; return tb; }
        public static TextBlock Text(this TextBlock tb, string path, BindingMode mode = BindingMode.Default)
        {
            tb.Bind(TextBlock.TextProperty, new Binding(path) { Mode = mode });
            return tb;
        }

        public static TextBox Text(this TextBox tb, string text) { tb.Text = text; return tb; }
        public static TextBox Text(this TextBox tb, string path, BindingMode mode = BindingMode.TwoWay)
        {
            tb.Bind(TextBox.TextProperty, new Binding(path) { Mode = mode });
            return tb;
        }

        public static TextBox Watermark(this TextBox tb, string watermark) { tb.Watermark = watermark; return tb; }
        public static TextBox PlaceholderText(this TextBox tb, string placeholder) { tb.Watermark = placeholder; return tb; }

        public static ToggleButton IsChecked(this ToggleButton tb, bool isChecked) { tb.IsChecked = isChecked; return tb; }
        public static ToggleButton IsChecked(this ToggleButton tb, string path, BindingMode mode = BindingMode.TwoWay)
        {
            tb.Bind(ToggleButton.IsCheckedProperty, new Binding(path) { Mode = mode });
            return tb;
        }

        public static RangeBase Value(this RangeBase rb, double value) { rb.Value = value; return rb; }
        public static RangeBase Value(this RangeBase rb, string path, BindingMode mode = BindingMode.TwoWay)
        {
            tbBindValue(rb, path, mode);
            return rb;
        }

        private static void tbBindValue(RangeBase rb, string path, BindingMode mode)
        {
            rb.Bind(RangeBase.ValueProperty, new Binding(path) { Mode = mode });
        }

        public static T FontSize<T>(this T control, double size) where T : TemplatedControl { control.FontSize = size; return control; }
        public static TextBlock FontSize(this TextBlock tb, double size) { tb.FontSize = size; return tb; }

        public static Button Command(this Button btn, string path)
        {
            btn.Bind(Button.CommandProperty, new Binding(path));
            return btn;
        }
    }
    """;
}
