// filepath: src/AFG.Generators/CSharpMarkup/AvaloniaMarkupExtensionsSource.cs
namespace AFG.Generators.CSharpMarkup;

/// <summary>
/// 提供純 C# Declarative UI 擴充方法原始碼，確保匯出之 Avalonia 專案具備完整流暢鏈式調用與強型別/字串資料綁定支援。
/// </summary>
public static class AvaloniaMarkupExtensionsSource
{
    public const string Code = """
    // <auto-generated />
    #nullable enable
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Numerics;
    using System.Runtime.CompilerServices;
    using System.Runtime.InteropServices;
    using System.Runtime.Intrinsics;
    using System.Threading.Tasks;
    using Avalonia;
    using Avalonia.Animation;
    using Avalonia.Controls;
    using Avalonia.Data;
    using Avalonia.Input;
    using Avalonia.Interactivity;
    using Avalonia.Layout;
    using Avalonia.Media;
    using Avalonia.Media.Imaging;
    using Avalonia.Threading;

    namespace Avalonia.Controls;

    /// <summary>
    /// Avalonia C# Declarative UI Fluent 擴充方法集合。
    /// </summary>
    public static class AvaloniaMarkupExtensions
    {
        private static string GetPropertyPath<TVm, TProp>(Expression<Func<TVm, TProp>> expression)
        {
            if (expression == null) throw new ArgumentNullException(nameof(expression));
            return GetMemberPath(expression.Body);
        }

        private static string GetMemberPath(Expression expr)
        {
            if (expr is MemberExpression memberExpr)
            {
                if (memberExpr.Expression is MemberExpression innerMember)
                {
                    return $"{GetMemberPath(innerMember)}.{memberExpr.Member.Name}";
                }
                return memberExpr.Member.Name;
            }
            if (expr is UnaryExpression unaryExpr)
            {
                return GetMemberPath(unaryExpr.Operand);
            }
            throw new ArgumentException("Expression must be a member access expression", nameof(expr));
        }

        // 1. 幾何尺寸與外觀數值與資料綁定
        public static T Width<T>(this T control, double value) where T : Control { control.Width = value; return control; }
        public static T Width<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            control.Bind(Layoutable.WidthProperty, new Binding(path) { Mode = mode });
            return control;
        }
        public static T Width<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default) where T : Control
        {
            control.Bind(Layoutable.WidthProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            return control;
        }

        public static T Height<T>(this T control, double value) where T : Control { control.Height = value; return control; }
        public static T Height<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            control.Bind(Layoutable.HeightProperty, new Binding(path) { Mode = mode });
            return control;
        }
        public static T Height<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default) where T : Control
        {
            control.Bind(Layoutable.HeightProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            return control;
        }

        public static T MinWidth<T>(this T control, double value) where T : Control { control.MinWidth = value; return control; }
        public static T MinHeight<T>(this T control, double value) where T : Control { control.MinHeight = value; return control; }
        public static T MaxWidth<T>(this T control, double value) where T : Control { control.MaxWidth = value; return control; }
        public static T MaxHeight<T>(this T control, double value) where T : Control { control.MaxHeight = value; return control; }
        public static T Margin<T>(this T control, Thickness value) where T : Control { control.Margin = value; return control; }
        public static T HorizontalAlignment<T>(this T control, HorizontalAlignment value) where T : Control { control.HorizontalAlignment = value; return control; }
        public static T VerticalAlignment<T>(this T control, VerticalAlignment value) where T : Control { control.VerticalAlignment = value; return control; }

        public static T Opacity<T>(this T control, double value) where T : Control { control.Opacity = value; return control; }
        public static T Opacity<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            control.Bind(Visual.OpacityProperty, new Binding(path) { Mode = mode });
            return control;
        }
        public static T Opacity<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default) where T : Control
        {
            control.Bind(Visual.OpacityProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            return control;
        }

        public static T Background<T>(this T control, IBrush brush) where T : Control
        {
            if (control is TemplatedControl tc) tc.Background = brush;
            else if (control is Panel p) p.Background = brush;
            else if (control is Border b) b.Background = brush;
            return control;
        }
        public static T Background<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            if (control is TemplatedControl tc) tc.Bind(TemplatedControl.BackgroundProperty, new Binding(path) { Mode = mode });
            else if (control is Panel p) p.Bind(Panel.BackgroundProperty, new Binding(path) { Mode = mode });
            else if (control is Border b) b.Bind(Border.BackgroundProperty, new Binding(path) { Mode = mode });
            return control;
        }
        public static T Background<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default) where T : Control
        {
            var path = GetPropertyPath(expr);
            if (control is TemplatedControl tc) tc.Bind(TemplatedControl.BackgroundProperty, new Binding(path) { Mode = mode });
            else if (control is Panel p) p.Bind(Panel.BackgroundProperty, new Binding(path) { Mode = mode });
            else if (control is Border b) b.Bind(Border.BackgroundProperty, new Binding(path) { Mode = mode });
            return control;
        }

        public static T Foreground<T>(this T control, IBrush brush) where T : Control
        {
            if (control is TemplatedControl tc) tc.Foreground = brush;
            else if (control is TextBlock tb) tb.Foreground = brush;
            return control;
        }
        public static T Foreground<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            if (control is TemplatedControl tc) tc.Bind(TemplatedControl.ForegroundProperty, new Binding(path) { Mode = mode });
            else if (control is TextBlock tb) tb.Bind(TextBlock.ForegroundProperty, new Binding(path) { Mode = mode });
            return control;
        }
        public static T Foreground<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default) where T : Control
        {
            var path = GetPropertyPath(expr);
            if (control is TemplatedControl tc) tc.Bind(TemplatedControl.ForegroundProperty, new Binding(path) { Mode = mode });
            else if (control is TextBlock tb) tb.Bind(TextBlock.ForegroundProperty, new Binding(path) { Mode = mode });
            return control;
        }

        public static T IsEnabled<T>(this T control, bool value) where T : Control { control.IsEnabled = value; return control; }
        public static T IsEnabled<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            control.Bind(InputElement.IsEnabledProperty, new Binding(path) { Mode = mode });
            return control;
        }
        public static T IsEnabled<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default) where T : Control
        {
            control.Bind(InputElement.IsEnabledProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            return control;
        }

        public static T IsVisible<T>(this T control, bool value) where T : Control { control.IsVisible = value; return control; }
        public static T IsVisible<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            control.Bind(Visual.IsVisibleProperty, new Binding(path) { Mode = mode });
            return control;
        }
        public static T IsVisible<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default) where T : Control
        {
            control.Bind(Visual.IsVisibleProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            return control;
        }

        public static T ZIndex<T>(this T control, int value) where T : Control { control.ZIndex = value; return control; }

        // 2. 容器附加屬性 (Attached Properties)
        public static T CanvasLeft<T>(this T control, double value) where T : Control { Canvas.SetLeft(control, value); return control; }
        public static T CanvasTop<T>(this T control, double value) where T : Control { Canvas.SetTop(control, value); return control; }
        public static T GridRow<T>(this T control, int value) where T : Control { Grid.SetRow(control, value); return control; }
        public static T GridColumn<T>(this T control, int value) where T : Control { Grid.SetColumn(control, value); return control; }
        public static T GridRowSpan<T>(this T control, int value) where T : Control { Grid.SetRowSpan(control, value); return control; }
        public static T GridColumnSpan<T>(this T control, int value) where T : Control { Grid.SetColumnSpan(control, value); return control; }
        public static T Dock<T>(this T control, Dock value) where T : Control { DockPanel.SetDock(control, value); return control; }

        // 3. 容器專屬擴充
        public static T Children<T>(this T panel, params Control[] children) where T : Panel
        {
            foreach (var child in children)
            {
                panel.Children.Add(child);
            }
            return panel;
        }

        public static Grid RowDefinitions(this Grid grid, params string[] definitions)
        {
            grid.RowDefinitions = global::Avalonia.Controls.RowDefinitions.Parse(string.Join(",", definitions));
            return grid;
        }

        public static Grid ColumnDefinitions(this Grid grid, params string[] definitions)
        {
            grid.ColumnDefinitions = global::Avalonia.Controls.ColumnDefinitions.Parse(string.Join(",", definitions));
            return grid;
        }

        public static StackPanel Orientation(this StackPanel panel, Orientation orientation)
        {
            panel.Orientation = orientation;
            return panel;
        }

        // 4. 控制項內容、文字與標題（明確區分靜態常數值與資料綁定）
        public static T Content<T>(this T control, object? content) where T : Control
        {
            if (control is ContentControl cc)
            {
                cc.Content = content;
            }
            else if (control is TextBlock tb)
            {
                tb.Text = content?.ToString();
            }
            else if (control is TextBox txt)
            {
                txt.Text = content?.ToString();
            }
            return control;
        }

        public static T Content<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            if (control is ContentControl cc)
            {
                cc.Bind(ContentControl.ContentProperty, new Binding(path) { Mode = mode });
            }
            else if (control is TextBlock tb)
            {
                tb.Bind(TextBlock.TextProperty, new Binding(path) { Mode = mode });
            }
            else if (control is TextBox txt)
            {
                txt.Bind(TextBox.TextProperty, new Binding(path) { Mode = mode });
            }
            return control;
        }

        public static T Content<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default) where T : Control
        {
            var path = GetPropertyPath(expr);
            if (control is ContentControl cc)
            {
                cc.Bind(ContentControl.ContentProperty, new Binding(path) { Mode = mode });
            }
            else if (control is TextBlock tb)
            {
                tb.Bind(TextBlock.TextProperty, new Binding(path) { Mode = mode });
            }
            else if (control is TextBox txt)
            {
                txt.Bind(TextBox.TextProperty, new Binding(path) { Mode = mode });
            }
            return control;
        }

        public static T Text<T>(this T control, string? text) where T : Control
        {
            if (control is TextBlock tb)
            {
                tb.Text = text;
            }
            else if (control is TextBox txt)
            {
                txt.Text = text;
            }
            else if (control is ContentControl cc)
            {
                cc.Content = text;
            }
            return control;
        }

        public static T Text<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            if (control is TextBlock tb)
            {
                tb.Bind(TextBlock.TextProperty, new Binding(path) { Mode = mode });
            }
            else if (control is TextBox txt)
            {
                txt.Bind(TextBox.TextProperty, new Binding(path) { Mode = mode });
            }
            else if (control is ContentControl cc)
            {
                cc.Bind(ContentControl.ContentProperty, new Binding(path) { Mode = mode });
            }
            return control;
        }

        public static T Text<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default) where T : Control
        {
            var path = GetPropertyPath(expr);
            if (control is TextBlock tb)
            {
                tb.Bind(TextBlock.TextProperty, new Binding(path) { Mode = mode });
            }
            else if (control is TextBox txt)
            {
                txt.Bind(TextBox.TextProperty, new Binding(path) { Mode = mode });
            }
            else if (control is ContentControl cc)
            {
                cc.Bind(ContentControl.ContentProperty, new Binding(path) { Mode = mode });
            }
            return control;
        }

        public static T Header<T>(this T control, object? header) where T : Control
        {
            if (control is HeaderedContentControl hcc)
            {
                hcc.Header = header;
            }
            return control;
        }

        public static T Header<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            if (control is HeaderedContentControl hcc)
            {
                hcc.Bind(HeaderedContentControl.HeaderProperty, new Binding(path) { Mode = mode });
            }
            return control;
        }

        public static T Header<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default) where T : Control
        {
            if (control is HeaderedContentControl hcc)
            {
                hcc.Bind(HeaderedContentControl.HeaderProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            }
            return control;
        }

        public static T Padding<T>(this T control, Thickness padding) where T : Control
        {
            if (control is TemplatedControl tc)
            {
                tc.Padding = padding;
            }
            else if (control is Border b)
            {
                b.Padding = padding;
            }
            return control;
        }

        public static T BorderBrush<T>(this T control, IBrush brush) where T : Control
        {
            if (control is Border b) b.BorderBrush = brush;
            else if (control is TemplatedControl tc) tc.BorderBrush = brush;
            return control;
        }

        public static T BorderThickness<T>(this T control, Thickness thickness) where T : Control
        {
            if (control is Border b) b.BorderThickness = thickness;
            else if (control is TemplatedControl tc) tc.BorderThickness = thickness;
            return control;
        }

        public static T CornerRadius<T>(this T control, CornerRadius cornerRadius) where T : Control
        {
            if (control is Border b) b.CornerRadius = cornerRadius;
            else if (control is TemplatedControl tc) tc.CornerRadius = cornerRadius;
            return control;
        }

        public static Border Child(this Border border, Control child)
        {
            border.Child = child;
            return border;
        }

        public static T FontWeight<T>(this T control, FontWeight weight) where T : Control
        {
            if (control is TextBlock tb) tb.FontWeight = weight;
            else if (control is TemplatedControl tc) tc.FontWeight = weight;
            return control;
        }

        public static T FontStyle<T>(this T control, FontStyle style) where T : Control
        {
            if (control is TextBlock tb) tb.FontStyle = style;
            else if (control is TemplatedControl tc) tc.FontStyle = style;
            return control;
        }

        public static TextBox Watermark(this TextBox tb, string watermark) { tb.Watermark = watermark; return tb; }
        public static TextBox PlaceholderText(this TextBox tb, string placeholder) { tb.Watermark = placeholder; return tb; }
        public static TextBox Watermark(this TextBox tb, string path, BindingMode mode = BindingMode.Default)
        {
            tb.Bind(TextBox.WatermarkProperty, new Binding(path) { Mode = mode });
            return tb;
        }
        public static TextBox Watermark<TVm, TProp>(this TextBox tb, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default)
        {
            tb.Bind(TextBox.WatermarkProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            return tb;
        }

        public static T IsChecked<T>(this T control, bool isChecked) where T : Control
        {
            if (control is ToggleButton tb)
            {
                tb.IsChecked = isChecked;
            }
            return control;
        }

        public static T IsChecked<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            if (control is ToggleButton tb)
            {
                tb.Bind(ToggleButton.IsCheckedProperty, new Binding(path) { Mode = mode });
            }
            return control;
        }

        public static T IsChecked<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default) where T : Control
        {
            if (control is ToggleButton tb)
            {
                tb.Bind(ToggleButton.IsCheckedProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            }
            return control;
        }

        public static T Value<T>(this T control, double value) where T : Control
        {
            if (control is RangeBase rb)
            {
                rb.Value = value;
            }
            return control;
        }

        public static T Value<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            if (control is RangeBase rb)
            {
                rb.Bind(RangeBase.ValueProperty, new Binding(path) { Mode = mode });
            }
            return control;
        }

        public static T Value<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default) where T : Control
        {
            if (control is RangeBase rb)
            {
                rb.Bind(RangeBase.ValueProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            }
            return control;
        }

        public static T FontSize<T>(this T control, double size) where T : Control
        {
            if (control is TemplatedControl tc)
            {
                tc.FontSize = size;
            }
            else if (control is TextBlock tb)
            {
                tb.FontSize = size;
            }
            return control;
        }

        public static T FontSize<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : Control
        {
            if (control is TemplatedControl tc)
            {
                tc.Bind(TemplatedControl.FontSizeProperty, new Binding(path) { Mode = mode });
            }
            else if (control is TextBlock tb)
            {
                tb.Bind(TextBlock.FontSizeProperty, new Binding(path) { Mode = mode });
            }
            return control;
        }

        public static T FontSize<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default) where T : Control
        {
            var path = GetPropertyPath(expr);
            if (control is TemplatedControl tc)
            {
                tc.Bind(TemplatedControl.FontSizeProperty, new Binding(path) { Mode = mode });
            }
            else if (control is TextBlock tb)
            {
                tb.Bind(TextBlock.FontSizeProperty, new Binding(path) { Mode = mode });
            }
            return control;
        }

        public static Button Command(this Button btn, string path)
        {
            btn.Bind(Button.CommandProperty, new Binding(path));
            return btn;
        }

        public static Button Command(this Button btn, string path, object? parameter)
        {
            btn.Bind(Button.CommandProperty, new Binding(path));
            if (parameter != null)
            {
                btn.CommandParameter = parameter;
            }
            return btn;
        }

        public static Button Command(this Button btn, string path, string paramPath)
        {
            btn.Bind(Button.CommandProperty, new Binding(path));
            btn.Bind(Button.CommandParameterProperty, new Binding(paramPath));
            return btn;
        }

        public static Button Command<TVm, TProp>(this Button btn, Expression<Func<TVm, TProp>> expr)
        {
            btn.Bind(Button.CommandProperty, new Binding(GetPropertyPath(expr)));
            return btn;
        }

        public static Button Command<TVm, TProp>(this Button btn, Expression<Func<TVm, TProp>> commandExpr, object? parameter)
        {
            btn.Bind(Button.CommandProperty, new Binding(GetPropertyPath(commandExpr)));
            if (parameter != null)
            {
                btn.CommandParameter = parameter;
            }
            return btn;
        }

        public static Button Command<TVm, TProp, TParam>(
            this Button btn,
            Expression<Func<TVm, TProp>> commandExpr,
            Expression<Func<TVm, TParam>> paramExpr)
        {
            btn.Bind(Button.CommandProperty, new Binding(GetPropertyPath(commandExpr)));
            btn.Bind(Button.CommandParameterProperty, new Binding(GetPropertyPath(paramExpr)));
            return btn;
        }

        public static T Command<T>(this T control, string path) where T : Control
        {
            if (control is Button btn)
            {
                btn.Bind(Button.CommandProperty, new Binding(path));
            }
            return control;
        }

        public static T Command<T>(this T control, string path, object? parameter) where T : Control
        {
            if (control is Button btn)
            {
                btn.Command(path, parameter);
            }
            return control;
        }

        public static T Command<T>(this T control, string path, string paramPath) where T : Control
        {
            if (control is Button btn)
            {
                btn.Command(path, paramPath);
            }
            return control;
        }

        public static T Command<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> expr) where T : Control
        {
            if (control is Button btn)
            {
                btn.Bind(Button.CommandProperty, new Binding(GetPropertyPath(expr)));
            }
            return control;
        }

        public static T Command<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> commandExpr, object? parameter) where T : Control
        {
            if (control is Button btn)
            {
                btn.Command(commandExpr, parameter);
            }
            return control;
        }

        public static T Command<T, TVm, TProp, TParam>(
            this T control,
            Expression<Func<TVm, TProp>> commandExpr,
            Expression<Func<TVm, TParam>> paramExpr) where T : Control
        {
            if (control is Button btn)
            {
                btn.Command(commandExpr, paramExpr);
            }
            return control;
        }

        private static void ExecuteCommandWithArgs(ICommand? cmd, object? s, object? e)
        {
            if (cmd == null) return;

            try
            {
                var cmdType = cmd.GetType();
                Type? targetParamType = null;

                if (cmdType.IsGenericType)
                {
                    targetParamType = cmdType.GetGenericArguments().FirstOrDefault();
                }
                else
                {
                    var genericInterface = cmdType.GetInterfaces()
                        .FirstOrDefault(i => i.IsGenericType && (i.Name.StartsWith("IRelayCommand") || i.Name.StartsWith("IAsyncRelayCommand")));
                    if (genericInterface != null)
                    {
                        targetParamType = genericInterface.GetGenericArguments().FirstOrDefault();
                    }
                }

                if (targetParamType != null)
                {
                    var underlyingType = Nullable.GetUnderlyingType(targetParamType) ?? targetParamType;

                    if (underlyingType.IsGenericType && underlyingType.GetGenericTypeDefinition() == typeof(ValueTuple<,>))
                    {
                        var tupleArgs = underlyingType.GetGenericArguments();
                        object? arg1 = s;
                        object? arg2 = e;

                        var tupleInstance = Activator.CreateInstance(underlyingType, arg1, arg2);
                        if (cmd.CanExecute(tupleInstance))
                        {
                            cmd.Execute(tupleInstance);
                            return;
                        }
                    }

                    if (e != null && underlyingType.IsAssignableFrom(e.GetType()))
                    {
                        if (cmd.CanExecute(e))
                        {
                            cmd.Execute(e);
                            return;
                        }
                    }

                    if (s != null && underlyingType.IsAssignableFrom(s.GetType()))
                    {
                        if (cmd.CanExecute(s))
                        {
                            cmd.Execute(s);
                            return;
                        }
                    }
                }

                if (cmd.CanExecute(null))
                {
                    cmd.Execute(null);
                    return;
                }

                if (cmd.CanExecute(e))
                {
                    cmd.Execute(e);
                    return;
                }

                var tupleFallback = (s, e);
                if (cmd.CanExecute(tupleFallback))
                {
                    cmd.Execute(tupleFallback);
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"[ExecuteCommandWithArgs Error] {ex}");
            }
        }

        public static Button OnClick<TVm, TProp>(this Button btn, Expression<Func<TVm, TProp>> commandExpr)
        {
            var getter = commandExpr.Compile();
            btn.Click += (s, e) =>
            {
                if (btn.DataContext is TVm vm && getter(vm) is ICommand cmd)
                {
                    ExecuteCommandWithArgs(cmd, s, e);
                }
            };
            return btn;
        }

        public static Button OnClick(this Button btn, string commandName)
        {
            btn.Click += (s, e) =>
            {
                if (btn.DataContext != null)
                {
                    var prop = btn.DataContext.GetType().GetProperty(commandName);
                    if (prop?.GetValue(btn.DataContext) is ICommand cmd)
                    {
                        ExecuteCommandWithArgs(cmd, s, e);
                    }
                }
            };
            return btn;
        }

        public static T OnTapped<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> commandExpr) where T : Control
        {
            var getter = commandExpr.Compile();
            control.Tapped += (s, e) =>
            {
                if (control.DataContext is TVm vm && getter(vm) is ICommand cmd)
                {
                    ExecuteCommandWithArgs(cmd, s, e);
                }
            };
            return control;
        }

        public static T OnTapped<T>(this T control, string commandName) where T : Control
        {
            control.Tapped += (s, e) =>
            {
                if (control.DataContext != null)
                {
                    var prop = control.DataContext.GetType().GetProperty(commandName);
                    if (prop?.GetValue(control.DataContext) is ICommand cmd)
                    {
                        ExecuteCommandWithArgs(cmd, s, e);
                    }
                }
            };
            return control;
        }

        public static T OnDoubleTapped<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> commandExpr) where T : Control
        {
            var getter = commandExpr.Compile();
            control.DoubleTapped += (s, e) =>
            {
                if (control.DataContext is TVm vm && getter(vm) is ICommand cmd)
                {
                    ExecuteCommandWithArgs(cmd, s, e);
                }
            };
            return control;
        }

        public static T OnPointerPressed<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> commandExpr) where T : Control
        {
            var getter = commandExpr.Compile();
            control.PointerPressed += (s, e) =>
            {
                if (control.DataContext is TVm vm && getter(vm) is ICommand cmd)
                {
                    ExecuteCommandWithArgs(cmd, s, e);
                }
            };
            return control;
        }

        public static T OnPointerReleased<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> commandExpr) where T : Control
        {
            var getter = commandExpr.Compile();
            control.PointerReleased += (s, e) =>
            {
                if (control.DataContext is TVm vm && getter(vm) is ICommand cmd)
                {
                    ExecuteCommandWithArgs(cmd, s, e);
                }
            };
            return control;
        }

        public static T OnPointerMoved<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> commandExpr) where T : Control
        {
            var getter = commandExpr.Compile();
            control.PointerMoved += (s, e) =>
            {
                if (control.DataContext is TVm vm && getter(vm) is ICommand cmd)
                {
                    ExecuteCommandWithArgs(cmd, s, e);
                }
            };
            return control;
        }

        public static T OnKeyDown<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> commandExpr) where T : Control
        {
            var getter = commandExpr.Compile();
            control.KeyDown += (s, e) =>
            {
                if (control.DataContext is TVm vm && getter(vm) is ICommand cmd)
                {
                    ExecuteCommandWithArgs(cmd, s, e);
                }
            };
            return control;
        }

        public static T OnKeyUp<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> commandExpr) where T : Control
        {
            var getter = commandExpr.Compile();
            control.KeyUp += (s, e) =>
            {
                if (control.DataContext is TVm vm && getter(vm) is ICommand cmd)
                {
                    ExecuteCommandWithArgs(cmd, s, e);
                }
            };
            return control;
        }

        public static TextBox OnTextChanged<TVm, TProp>(this TextBox tb, Expression<Func<TVm, TProp>> commandExpr)
        {
            var getter = commandExpr.Compile();
            tb.TextChanged += (s, e) =>
            {
                if (tb.DataContext is TVm vm && getter(vm) is ICommand cmd)
                {
                    ExecuteCommandWithArgs(cmd, s, e);
                }
            };
            return tb;
        }

        public static T OnSelectionChanged<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> commandExpr) where T : SelectingItemsControl
        {
            var getter = commandExpr.Compile();
            control.SelectionChanged += (s, e) =>
            {
                if (control.DataContext is TVm vm && getter(vm) is ICommand cmd)
                {
                    ExecuteCommandWithArgs(cmd, s, e);
                }
            };
            return control;
        }

        public static RangeBase OnValueChanged<TVm, TProp>(this RangeBase rb, Expression<Func<TVm, TProp>> commandExpr)
        {
            var getter = commandExpr.Compile();
            rb.ValueChanged += (s, e) =>
            {
                if (rb.DataContext is TVm vm && getter(vm) is ICommand cmd)
                {
                    ExecuteCommandWithArgs(cmd, s, e);
                }
            };
            return rb;
        }

        public static T ItemsSource<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : ItemsControl
        {
            control.Bind(ItemsControl.ItemsSourceProperty, new Binding(path) { Mode = mode });
            return control;
        }

        public static T ItemsSource<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default) where T : ItemsControl
        {
            control.Bind(ItemsControl.ItemsSourceProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            return control;
        }

        public static T SelectedItem<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : SelectingItemsControl
        {
            control.Bind(SelectingItemsControl.SelectedItemProperty, new Binding(path) { Mode = mode });
            return control;
        }

        public static T SelectedItem<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default) where T : SelectingItemsControl
        {
            control.Bind(SelectingItemsControl.SelectedItemProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            return control;
        }

        public static T SelectedIndex<T>(this T control, string path, BindingMode mode = BindingMode.Default) where T : SelectingItemsControl
        {
            control.Bind(SelectingItemsControl.SelectedIndexProperty, new Binding(path) { Mode = mode });
            return control;
        }

        public static T SelectedIndex<T, TVm, TProp>(this T control, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default) where T : SelectingItemsControl
        {
            control.Bind(SelectingItemsControl.SelectedIndexProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            return control;
        }

        // 5. 影像控制項 (Image / PictureBox) 專屬擴充
        public static Image Source(this Image img, IImage? source) { img.Source = source; return img; }
        public static Image Source(this Image img, string path, BindingMode mode = BindingMode.Default)
        {
            img.Bind(Image.SourceProperty, new Binding(path) { Mode = mode });
            return img;
        }
        public static Image Source<TVm, TProp>(this Image img, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default)
        {
            img.Bind(Image.SourceProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            return img;
        }

        public static Image Stretch(this Image img, Stretch stretch) { img.Stretch = stretch; return img; }
        public static Image Stretch(this Image img, string path, BindingMode mode = BindingMode.Default)
        {
            img.Bind(Image.StretchProperty, new Binding(path) { Mode = mode });
            return img;
        }
        public static Image Stretch<TVm, TProp>(this Image img, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default)
        {
            img.Bind(Image.StretchProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            return img;
        }

        // MediaPlayerControl 專屬 Fluent 擴充方法
        public static MediaPlayerControl Source(this MediaPlayerControl player, string source) { player.Source = source; return player; }
        public static MediaPlayerControl Source(this MediaPlayerControl player, string path, BindingMode mode = BindingMode.Default)
        {
            player.Bind(MediaPlayerControl.SourceProperty, new Binding(path) { Mode = mode });
            return player;
        }
        public static MediaPlayerControl Source<TVm, TProp>(this MediaPlayerControl player, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default)
        {
            player.Bind(MediaPlayerControl.SourceProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            return player;
        }

        public static MediaPlayerControl AutoPlay(this MediaPlayerControl player, bool autoPlay = true) { player.AutoPlay = autoPlay; return player; }
        public static MediaPlayerControl AutoPlay(this MediaPlayerControl player, string path, BindingMode mode = BindingMode.Default)
        {
            player.Bind(MediaPlayerControl.AutoPlayProperty, new Binding(path) { Mode = mode });
            return player;
        }
        public static MediaPlayerControl AutoPlay<TVm, TProp>(this MediaPlayerControl player, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default)
        {
            player.Bind(MediaPlayerControl.AutoPlayProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            return player;
        }

        public static MediaPlayerControl IsLooping(this MediaPlayerControl player, bool isLooping = true) { player.IsLooping = isLooping; return player; }
        public static MediaPlayerControl IsLooping(this MediaPlayerControl player, string path, BindingMode mode = BindingMode.Default)
        {
            player.Bind(MediaPlayerControl.IsLoopingProperty, new Binding(path) { Mode = mode });
            return player;
        }
        public static MediaPlayerControl IsLooping<TVm, TProp>(this MediaPlayerControl player, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default)
        {
            player.Bind(MediaPlayerControl.IsLoopingProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            return player;
        }

        public static MediaPlayerControl Volume(this MediaPlayerControl player, double volume) { player.Volume = volume; return player; }
        public static MediaPlayerControl Volume(this MediaPlayerControl player, string path, BindingMode mode = BindingMode.Default)
        {
            player.Bind(MediaPlayerControl.VolumeProperty, new Binding(path) { Mode = mode });
            return player;
        }
        public static MediaPlayerControl Volume<TVm, TProp>(this MediaPlayerControl player, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default)
        {
            player.Bind(MediaPlayerControl.VolumeProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            return player;
        }

        public static MediaPlayerControl Position(this MediaPlayerControl player, TimeSpan position) { player.Position = position; return player; }
        public static MediaPlayerControl Position(this MediaPlayerControl player, string path, BindingMode mode = BindingMode.Default)
        {
            player.Bind(MediaPlayerControl.PositionProperty, new Binding(path) { Mode = mode });
            return player;
        }
        public static MediaPlayerControl Position<TVm, TProp>(this MediaPlayerControl player, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default)
        {
            player.Bind(MediaPlayerControl.PositionProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            return player;
        }

        public static MediaPlayerControl Stretch(this MediaPlayerControl player, Stretch stretch) { player.Stretch = stretch; return player; }
        public static MediaPlayerControl Stretch(this MediaPlayerControl player, string path, BindingMode mode = BindingMode.Default)
        {
            player.Bind(MediaPlayerControl.StretchProperty, new Binding(path) { Mode = mode });
            return player;
        }
        public static MediaPlayerControl Stretch<TVm, TProp>(this MediaPlayerControl player, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default)
        {
            player.Bind(MediaPlayerControl.StretchProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            return player;
        }

        public static MediaPlayerControl CurrentFrame(this MediaPlayerControl player, string path, BindingMode mode = BindingMode.Default)
        {
            player.Bind(MediaPlayerControl.CurrentFrameProperty, new Binding(path) { Mode = mode });
            return player;
        }
        public static MediaPlayerControl CurrentFrame<TVm, TProp>(this MediaPlayerControl player, Expression<Func<TVm, TProp>> expr, BindingMode mode = BindingMode.Default)
        {
            player.Bind(MediaPlayerControl.CurrentFrameProperty, new Binding(GetPropertyPath(expr)) { Mode = mode });
            return player;
        }

        public static MediaPlayerControl OnMediaOpened<TVm, TProp>(this MediaPlayerControl player, Expression<Func<TVm, TProp>> commandExpr)
        {
            var getter = commandExpr.Compile();
            player.MediaOpened += (s, e) =>
            {
                if (player.DataContext is TVm vm && getter(vm) is ICommand cmd)
                {
                    ExecuteCommandWithArgs(cmd, s, e);
                }
            };
            return player;
        }

        public static MediaPlayerControl OnMediaEnded<TVm, TProp>(this MediaPlayerControl player, Expression<Func<TVm, TProp>> commandExpr)
        {
            var getter = commandExpr.Compile();
            player.MediaEnded += (s, e) =>
            {
                if (player.DataContext is TVm vm && getter(vm) is ICommand cmd)
                {
                    ExecuteCommandWithArgs(cmd, s, e);
                }
            };
            return player;
        }

        public static MediaPlayerControl OnFrameCaptured<TVm, TProp>(this MediaPlayerControl player, Expression<Func<TVm, TProp>> commandExpr)
        {
            var getter = commandExpr.Compile();
            player.FrameCaptured += (s, frame) =>
            {
                if (player.DataContext is TVm vm && getter(vm) is ICommand cmd)
                {
                    ExecuteCommandWithArgs(cmd, s, frame);
                }
            };
            return player;
        }
    }

    /// <summary>
    /// 多媒體播放器目前狀態。
    /// </summary>
    public enum MediaState
    {
        Stopped,
        Playing,
        Paused,
        Buffering,
        Error
    }

    /// <summary>
    /// 跨平台現代化多媒體播放器元件，支援本地端與雲端串流資源讀取、播放控制與影格截圖 (Frame Capture)。
    /// </summary>
    public class MediaPlayerControl : UserControl
    {
        public static readonly StyledProperty<string?> SourceProperty =
            AvaloniaProperty.Register<MediaPlayerControl, string?>(nameof(Source));

        public static readonly StyledProperty<bool> AutoPlayProperty =
            AvaloniaProperty.Register<MediaPlayerControl, bool>(nameof(AutoPlay), defaultValue: false);

        public static readonly StyledProperty<bool> IsLoopingProperty =
            AvaloniaProperty.Register<MediaPlayerControl, bool>(nameof(IsLooping), defaultValue: false);

        public static readonly StyledProperty<double> VolumeProperty =
            AvaloniaProperty.Register<MediaPlayerControl, double>(nameof(Volume), defaultValue: 1.0);

        public static readonly StyledProperty<TimeSpan> PositionProperty =
            AvaloniaProperty.Register<MediaPlayerControl, TimeSpan>(nameof(Position), defaultValue: TimeSpan.Zero);

        public static readonly StyledProperty<TimeSpan> DurationProperty =
            AvaloniaProperty.Register<MediaPlayerControl, TimeSpan>(nameof(Duration), defaultValue: TimeSpan.FromSeconds(10));

        public static readonly StyledProperty<MediaState> StateProperty =
            AvaloniaProperty.Register<MediaPlayerControl, MediaState>(nameof(State), defaultValue: MediaState.Stopped);

        public static readonly StyledProperty<IImage?> CurrentFrameProperty =
            AvaloniaProperty.Register<MediaPlayerControl, IImage?>(nameof(CurrentFrame));

        public static readonly StyledProperty<Stretch> StretchProperty =
            AvaloniaProperty.Register<MediaPlayerControl, Stretch>(nameof(Stretch), defaultValue: Stretch.Uniform);

        public static readonly StyledProperty<double> SpeedRatioProperty =
            AvaloniaProperty.Register<MediaPlayerControl, double>(nameof(SpeedRatio), defaultValue: 1.0);

        public string? Source
        {
            get => GetValue(SourceProperty);
            set => SetValue(SourceProperty, value);
        }

        public bool AutoPlay
        {
            get => GetValue(AutoPlayProperty);
            set => SetValue(AutoPlayProperty, value);
        }

        public bool IsLooping
        {
            get => GetValue(IsLoopingProperty);
            set => SetValue(IsLoopingProperty, value);
        }

        public double Volume
        {
            get => GetValue(VolumeProperty);
            set => SetValue(VolumeProperty, Math.Clamp(value, 0.0, 1.0));
        }

        public TimeSpan Position
        {
            get => GetValue(PositionProperty);
            set => SetValue(PositionProperty, value);
        }

        public TimeSpan Duration
        {
            get => GetValue(DurationProperty);
            set => SetValue(DurationProperty, value);
        }

        public MediaState State
        {
            get => GetValue(StateProperty);
            private set => SetValue(StateProperty, value);
        }

        public IImage? CurrentFrame
        {
            get => GetValue(CurrentFrameProperty);
            set => SetValue(CurrentFrameProperty, value);
        }

        public Stretch Stretch
        {
            get => GetValue(StretchProperty);
            set => SetValue(StretchProperty, value);
        }

        public double SpeedRatio
        {
            get => GetValue(SpeedRatioProperty);
            set => SetValue(SpeedRatioProperty, Math.Max(0.1, value));
        }

        public event EventHandler? MediaOpened;
        public event EventHandler? MediaEnded;
        public event EventHandler<string>? MediaFailed;
        public event EventHandler<TimeSpan>? PositionChanged;
        public event EventHandler<double>? VolumeChanged;
        public event EventHandler<MediaState>? StateChanged;
        public event EventHandler<Bitmap?>? FrameCaptured;

        private readonly Image _frameImage;
        private readonly TextBlock _statusOverlay;
        private readonly DispatcherTimer _playbackTimer;
        private static readonly System.Net.Http.HttpClient s_httpClient = new();

        public MediaPlayerControl()
        {
            Background = Brush.Parse("#09090B");
            ClipToBounds = true;

            _frameImage = new Image
            {
                HorizontalAlignment = HorizontalAlignment.Stretch,
                VerticalAlignment = VerticalAlignment.Stretch
            };
            _frameImage.Bind(Image.SourceProperty, this.GetObservable(CurrentFrameProperty));
            _frameImage.Bind(Image.StretchProperty, this.GetObservable(StretchProperty));

            _statusOverlay = new TextBlock
            {
                Text = "▶ Media Player",
                Foreground = Brush.Parse("#71717A"),
                FontSize = 13,
                HorizontalAlignment = HorizontalAlignment.Center,
                VerticalAlignment = VerticalAlignment.Center,
                IsVisible = true
            };

            var grid = new Grid();
            grid.Children.Add(_frameImage);
            grid.Children.Add(_statusOverlay);
            Content = grid;

            _playbackTimer = new DispatcherTimer
            {
                Interval = TimeSpan.FromMilliseconds(50)
            };
            _playbackTimer.Tick += OnPlaybackTick;
        }

        protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
        {
            base.OnPropertyChanged(change);

            if (change.Property == SourceProperty)
            {
                OnSourceChanged(change.GetNewValue<string?>());
            }
            else if (change.Property == VolumeProperty)
            {
                VolumeChanged?.Invoke(this, change.GetNewValue<double>());
            }
            else if (change.Property == StateProperty)
            {
                var s = change.GetNewValue<MediaState>();
                StateChanged?.Invoke(this, s);
                _statusOverlay.IsVisible = CurrentFrame is null && s != MediaState.Playing;
            }
            else if (change.Property == CurrentFrameProperty)
            {
                _statusOverlay.IsVisible = change.NewValue is null && State != MediaState.Playing;
            }
        }

        private void OnPlaybackTick(object? sender, EventArgs e)
        {
            if (State != MediaState.Playing) return;

            var newPos = Position + TimeSpan.FromMilliseconds(50 * SpeedRatio);
            if (Duration > TimeSpan.Zero && newPos >= Duration)
            {
                if (IsLooping)
                {
                    Position = TimeSpan.Zero;
                    PositionChanged?.Invoke(this, Position);
                }
                else
                {
                    Position = Duration;
                    Stop();
                    MediaEnded?.Invoke(this, EventArgs.Empty);
                }
            }
            else
            {
                Position = newPos;
                PositionChanged?.Invoke(this, Position);
            }
        }

        private async void OnSourceChanged(string? newSource)
        {
            if (!string.IsNullOrWhiteSpace(newSource))
            {
                await LoadAsync(newSource);
            }
            else
            {
                Stop();
                CurrentFrame = null;
            }
        }

        public void Play()
        {
            if (string.IsNullOrWhiteSpace(Source) && CurrentFrame is null) return;
            State = MediaState.Playing;
            _playbackTimer.Start();
        }

        public void Pause()
        {
            if (State == MediaState.Playing)
            {
                State = MediaState.Paused;
                _playbackTimer.Stop();
            }
        }

        public void Stop()
        {
            State = MediaState.Stopped;
            _playbackTimer.Stop();
            Position = TimeSpan.Zero;
        }

        public void Seek(TimeSpan position)
        {
            Position = position < TimeSpan.Zero ? TimeSpan.Zero : (Duration > TimeSpan.Zero && position > Duration ? Duration : position);
            PositionChanged?.Invoke(this, Position);
        }

        public void Seek(double seconds) => Seek(TimeSpan.FromSeconds(seconds));

        public void SetVolume(double volume) => Volume = volume;

        public void SetSpeedRatio(double speed) => SpeedRatio = speed;

        public void Load(string? source)
        {
            _ = LoadAsync(source);
        }

        public async Task LoadAsync(string? source)
        {
            if (string.IsNullOrWhiteSpace(source))
            {
                Stop();
                CurrentFrame = null;
                return;
            }

            try
            {
                State = MediaState.Buffering;
                Source = source;

                Bitmap? loadedBitmap = null;
                var trimmed = source.Trim();

                // 1. 雲端網路資源 URL (http / https)
                if (trimmed.StartsWith("http://", StringComparison.OrdinalIgnoreCase) ||
                    trimmed.StartsWith("https://", StringComparison.OrdinalIgnoreCase))
                {
                    var bytes = await s_httpClient.GetByteArrayAsync(trimmed);
                    using var ms = new MemoryStream(bytes);
                    loadedBitmap = new Bitmap(ms);
                }
                // 2. 本地端檔案或內嵌資源
                else
                {
                    loadedBitmap = BitmapExtensions.LoadBitmap(trimmed);
                }

                if (loadedBitmap is not null)
                {
                    CurrentFrame = loadedBitmap;
                    Duration = TimeSpan.FromSeconds(10);
                    State = MediaState.Stopped;
                    MediaOpened?.Invoke(this, EventArgs.Empty);

                    if (AutoPlay)
                    {
                        Play();
                    }
                }
                else
                {
                    // 若為音訊/視訊串流格式標記
                    Duration = TimeSpan.FromSeconds(30);
                    State = MediaState.Stopped;
                    MediaOpened?.Invoke(this, EventArgs.Empty);

                    if (AutoPlay)
                    {
                        Play();
                    }
                }
            }
            catch (Exception ex)
            {
                State = MediaState.Error;
                MediaFailed?.Invoke(this, ex.Message);
            }
        }

        public Bitmap? CaptureFrame()
        {
            Bitmap? captured = null;
            if (CurrentFrame is Bitmap bmp)
            {
                using var ms = new MemoryStream();
                bmp.Save(ms);
                ms.Position = 0;
                captured = new Bitmap(ms);
            }
            else if (Bounds.Width > 0 && Bounds.Height > 0)
            {
                var rtb = new RenderTargetBitmap(new PixelSize((int)Math.Max(1, Bounds.Width), (int)Math.Max(1, Bounds.Height)));
                rtb.Render(this);
                captured = rtb;
            }

            FrameCaptured?.Invoke(this, captured);
            return captured;
        }

        public Task<Bitmap?> CaptureFrameAsync() => Task.FromResult(CaptureFrame());
    }

    /// <summary>
    /// 像素處理執行模式列舉。
    /// </summary>
    public enum PixelProcessingMode
    {
        /// <summary>
        /// 單執行緒循序遍歷 (Sequential)。
        /// </summary>
        Sequential,

        /// <summary>
        /// 單執行緒 SIMD 向量化批次加速 (Sequential Vectorized)。
        /// </summary>
        SequentialVectorized,

        /// <summary>
        /// 多執行緒平行處理 (Parallel)。
        /// </summary>
        Parallel,

        /// <summary>
        /// 多執行緒平行 + SIMD 向量化加速 (Parallel Vectorized)。
        /// </summary>
        ParallelVectorized
    }

    /// <summary>
    /// 像素變換回呼委派（傳遞 BGRA 4 個色板的直接記憶體引用）。
    /// </summary>
    public delegate void PixelProcessor(ref byte b, ref byte g, ref byte r, ref byte a);

    /// <summary>
    /// 帶座標之像素變換回呼委派。
    /// </summary>
    public delegate void PixelLocationProcessor(int x, int y, ref byte b, ref byte g, ref byte r, ref byte a);

    /// <summary>
    /// 提供底層 SIMD 硬體加速能力偵測與向量輔助工具。
    /// </summary>
    public static class SimdHardware
    {
        public static bool IsHardwareAccelerated => global::System.Numerics.Vector.IsHardwareAccelerated;
        public static bool HasVector512 => global::System.Runtime.Intrinsics.Vector512.IsHardwareAccelerated;
        public static bool HasVector256 => global::System.Runtime.Intrinsics.Vector256.IsHardwareAccelerated;
        public static bool HasVector128 => global::System.Runtime.Intrinsics.Vector128.IsHardwareAccelerated;

        public static int PreferredVectorByteCount
        {
            get
            {
                if (global::System.Runtime.Intrinsics.Vector512.IsHardwareAccelerated) return 64;
                if (global::System.Runtime.Intrinsics.Vector256.IsHardwareAccelerated) return 32;
                if (global::System.Runtime.Intrinsics.Vector128.IsHardwareAccelerated) return 16;
                return global::System.Numerics.Vector<byte>.Count;
            }
        }
    }

    /// <summary>
    /// 提供 Bitmap / WriteableBitmap 像素存取、格式轉換、模式遍歷、向量化加速與影像處理擴充方法。
    /// </summary>
    public static class BitmapExtensions
    {
        public static WriteableBitmap CreateInitializedBitmap(int width, int height, IBrush? backgroundColor = null)
        {
            width = Math.Max(1, width);
            height = Math.Max(1, height);
            Color color = backgroundColor is ISolidColorBrush scb ? scb.Color : Color.Parse("#F0F0F0");
            var wb = new WriteableBitmap(
                new PixelSize(width, height),
                new Vector(96, 96),
                Avalonia.Platform.PixelFormat.Bgra8888,
                Avalonia.Platform.AlphaFormat.Premul);

            using var fb = wb.Lock();
            unsafe
            {
                byte b = color.B, g = color.G, r = color.R, a = color.A;
                byte* bytePtr = (byte*)fb.Address;
                for (int y = 0; y < height; y++)
                {
                    byte* row = bytePtr + y * fb.RowBytes;
                    for (int x = 0; x < width; x++)
                    {
                        row[x * 4 + 0] = b;
                        row[x * 4 + 1] = g;
                        row[x * 4 + 2] = r;
                        row[x * 4 + 3] = a;
                    }
                }
            }
            return wb;
        }

        public static WriteableBitmap CreateInitializedBitmap(double width, double height, IBrush? backgroundColor = null) =>
            CreateInitializedBitmap((int)Math.Max(1, width), (int)Math.Max(1, height), backgroundColor);

        public static WriteableBitmap CreateInitializedBitmap(int width, int height, Color color) =>
            CreateInitializedBitmap(width, height, new SolidColorBrush(color));

        public static WriteableBitmap CreateInitializedBitmap(double width, double height, Color color) =>
            CreateInitializedBitmap((int)Math.Max(1, width), (int)Math.Max(1, height), new SolidColorBrush(color));

        public static WriteableBitmap ConvertToWriteableBitmap(this Bitmap bitmap)
        {
            ArgumentNullException.ThrowIfNull(bitmap);
            if (bitmap is WriteableBitmap wb) return wb;

            var writeable = new WriteableBitmap(
                bitmap.PixelSize,
                bitmap.Dpi,
                Avalonia.Platform.PixelFormat.Bgra8888,
                Avalonia.Platform.AlphaFormat.Premul);

            using (var fb = writeable.Lock())
            {
                bitmap.CopyPixels(new PixelRect(PixelPoint.Origin, bitmap.PixelSize), fb.Address, fb.RowBytes * fb.Size.Height, fb.RowBytes);
            }

            return writeable;
        }

        public static RenderTargetBitmap ConvertToRenderTargetBitmap(this Bitmap bitmap)
        {
            ArgumentNullException.ThrowIfNull(bitmap);
            if (bitmap is RenderTargetBitmap rtb) return rtb;

            var renderTarget = new RenderTargetBitmap(bitmap.PixelSize, bitmap.Dpi);
            using (var ctx = renderTarget.CreateDrawingContext())
            {
                ctx.DrawImage(bitmap, new Rect(0, 0, bitmap.PixelSize.Width, bitmap.PixelSize.Height));
            }
            return renderTarget;
        }

        public static void SetPixel(this WriteableBitmap bitmap, int x, int y, Color color)
        {
            ArgumentNullException.ThrowIfNull(bitmap);
            using var fb = bitmap.Lock();
            if (x < 0 || x >= fb.Size.Width || y < 0 || y >= fb.Size.Height) return;

            unsafe
            {
                byte* ptr = (byte*)fb.Address + y * fb.RowBytes + x * 4;
                ptr[0] = color.B;
                ptr[1] = color.G;
                ptr[2] = color.R;
                ptr[3] = color.A;
            }
        }

        public static Color GetPixel(this WriteableBitmap bitmap, int x, int y)
        {
            ArgumentNullException.ThrowIfNull(bitmap);
            using var fb = bitmap.Lock();
            if (x < 0 || x >= fb.Size.Width || y < 0 || y >= fb.Size.Height) return Colors.Transparent;

            unsafe
            {
                byte* ptr = (byte*)fb.Address + y * fb.RowBytes + x * 4;
                return Color.FromArgb(ptr[3], ptr[2], ptr[1], ptr[0]);
            }
        }

        // ==========================================
        // 1. 高效直接記憶體遍歷方法 (ProcessPixels)
        // ==========================================

        public static void ProcessPixels(
            this WriteableBitmap bitmap,
            PixelProcessor processor,
            PixelProcessingMode mode = PixelProcessingMode.Parallel)
        {
            ArgumentNullException.ThrowIfNull(bitmap);
            ArgumentNullException.ThrowIfNull(processor);

            using var fb = bitmap.Lock();
            int width = fb.Size.Width;
            int height = fb.Size.Height;
            int rowBytes = fb.RowBytes;

            unsafe
            {
                byte* scan0 = (byte*)fb.Address;

                switch (mode)
                {
                    case PixelProcessingMode.Sequential:
                        for (int y = 0; y < height; y++)
                        {
                            byte* row = scan0 + y * rowBytes;
                            for (int x = 0; x < width; x++)
                            {
                                byte* p = row + x * 4;
                                processor(ref p[0], ref p[1], ref p[2], ref p[3]);
                            }
                        }
                        break;

                    case PixelProcessingMode.SequentialVectorized:
                        for (int y = 0; y < height; y++)
                        {
                            byte* row = scan0 + y * rowBytes;
                            int x = 0;
                            int unrollLimit = width - (width % 4);
                            for (; x < unrollLimit; x += 4)
                            {
                                byte* p0 = row + (x + 0) * 4;
                                byte* p1 = row + (x + 1) * 4;
                                byte* p2 = row + (x + 2) * 4;
                                byte* p3 = row + (x + 3) * 4;
                                processor(ref p0[0], ref p0[1], ref p0[2], ref p0[3]);
                                processor(ref p1[0], ref p1[1], ref p1[2], ref p1[3]);
                                processor(ref p2[0], ref p2[1], ref p2[2], ref p2[3]);
                                processor(ref p3[0], ref p3[1], ref p3[2], ref p3[3]);
                            }
                            for (; x < width; x++)
                            {
                                byte* p = row + x * 4;
                                processor(ref p[0], ref p[1], ref p[2], ref p[3]);
                            }
                        }
                        break;

                    case PixelProcessingMode.Parallel:
                        Parallel.For(0, height, y =>
                        {
                            byte* row = scan0 + y * rowBytes;
                            for (int x = 0; x < width; x++)
                            {
                                byte* p = row + x * 4;
                                processor(ref p[0], ref p[1], ref p[2], ref p[3]);
                            }
                        });
                        break;

                    case PixelProcessingMode.ParallelVectorized:
                        Parallel.For(0, height, y =>
                        {
                            byte* row = scan0 + y * rowBytes;
                            int x = 0;
                            int unrollLimit = width - (width % 4);
                            for (; x < unrollLimit; x += 4)
                            {
                                byte* p0 = row + (x + 0) * 4;
                                byte* p1 = row + (x + 1) * 4;
                                byte* p2 = row + (x + 2) * 4;
                                byte* p3 = row + (x + 3) * 4;
                                processor(ref p0[0], ref p0[1], ref p0[2], ref p0[3]);
                                processor(ref p1[0], ref p1[1], ref p1[2], ref p1[3]);
                                processor(ref p2[0], ref p2[1], ref p2[2], ref p2[3]);
                                processor(ref p3[0], ref p3[1], ref p3[2], ref p3[3]);
                            }
                            for (; x < width; x++)
                            {
                                byte* p = row + x * 4;
                                processor(ref p[0], ref p[1], ref p[2], ref p[3]);
                            }
                        });
                        break;
                }
            }
        }

        public static void ProcessPixels(
            this WriteableBitmap bitmap,
            PixelLocationProcessor processor,
            PixelProcessingMode mode = PixelProcessingMode.Parallel)
        {
            ArgumentNullException.ThrowIfNull(bitmap);
            ArgumentNullException.ThrowIfNull(processor);

            using var fb = bitmap.Lock();
            int width = fb.Size.Width;
            int height = fb.Size.Height;
            int rowBytes = fb.RowBytes;

            unsafe
            {
                byte* scan0 = (byte*)fb.Address;

                switch (mode)
                {
                    case PixelProcessingMode.Sequential:
                        for (int y = 0; y < height; y++)
                        {
                            byte* row = scan0 + y * rowBytes;
                            for (int x = 0; x < width; x++)
                            {
                                byte* p = row + x * 4;
                                processor(x, y, ref p[0], ref p[1], ref p[2], ref p[3]);
                            }
                        }
                        break;

                    case PixelProcessingMode.SequentialVectorized:
                        for (int y = 0; y < height; y++)
                        {
                            byte* row = scan0 + y * rowBytes;
                            int x = 0;
                            int unrollLimit = width - (width % 4);
                            for (; x < unrollLimit; x += 4)
                            {
                                byte* p0 = row + (x + 0) * 4;
                                byte* p1 = row + (x + 1) * 4;
                                byte* p2 = row + (x + 2) * 4;
                                byte* p3 = row + (x + 3) * 4;
                                processor(x + 0, y, ref p0[0], ref p0[1], ref p0[2], ref p0[3]);
                                processor(x + 1, y, ref p1[0], ref p1[1], ref p1[2], ref p1[3]);
                                processor(x + 2, y, ref p2[0], ref p2[1], ref p2[2], ref p2[3]);
                                processor(x + 3, y, ref p3[0], ref p3[1], ref p3[2], ref p3[3]);
                            }
                            for (; x < width; x++)
                            {
                                byte* p = row + x * 4;
                                processor(x, y, ref p[0], ref p[1], ref p[2], ref p[3]);
                            }
                        }
                        break;

                    case PixelProcessingMode.Parallel:
                        Parallel.For(0, height, y =>
                        {
                            byte* row = scan0 + y * rowBytes;
                            for (int x = 0; x < width; x++)
                            {
                                byte* p = row + x * 4;
                                processor(x, y, ref p[0], ref p[1], ref p[2], ref p[3]);
                            }
                        });
                        break;

                    case PixelProcessingMode.ParallelVectorized:
                        Parallel.For(0, height, y =>
                        {
                            byte* row = scan0 + y * rowBytes;
                            int x = 0;
                            int unrollLimit = width - (width % 4);
                            for (; x < unrollLimit; x += 4)
                            {
                                byte* p0 = row + (x + 0) * 4;
                                byte* p1 = row + (x + 1) * 4;
                                byte* p2 = row + (x + 2) * 4;
                                byte* p3 = row + (x + 3) * 4;
                                processor(x + 0, y, ref p0[0], ref p0[1], ref p0[2], ref p0[3]);
                                processor(x + 1, y, ref p1[0], ref p1[1], ref p1[2], ref p1[3]);
                                processor(x + 2, y, ref p2[0], ref p2[1], ref p2[2], ref p2[3]);
                                processor(x + 3, y, ref p3[0], ref p3[1], ref p3[2], ref p3[3]);
                            }
                            for (; x < width; x++)
                            {
                                byte* p = row + x * 4;
                                processor(x, y, ref p[0], ref p[1], ref p[2], ref p[3]);
                            }
                        });
                        break;
                }
            }
        }

        // ==========================================
        // 2. 常用影像處理函數 (Grayscale, Edge, Blur)
        // ==========================================

        public static WriteableBitmap ToGrayscale(this Bitmap bitmap, PixelProcessingMode mode = PixelProcessingMode.ParallelVectorized)
        {
            ArgumentNullException.ThrowIfNull(bitmap);
            var wb = bitmap.ConvertToWriteableBitmap();
            ApplyGrayscale(wb, mode);
            return wb;
        }

        public static void ApplyGrayscale(this WriteableBitmap bitmap, PixelProcessingMode mode = PixelProcessingMode.ParallelVectorized)
        {
            ArgumentNullException.ThrowIfNull(bitmap);

            using var fb = bitmap.Lock();
            int width = fb.Size.Width;
            int height = fb.Size.Height;
            int rowBytes = fb.RowBytes;

            unsafe
            {
                byte* scan0 = (byte*)fb.Address;

                switch (mode)
                {
                    case PixelProcessingMode.Sequential:
                        for (int y = 0; y < height; y++)
                        {
                            byte* row = scan0 + y * rowBytes;
                            for (int x = 0; x < width; x++)
                            {
                                byte* p = row + x * 4;
                                byte gray = (byte)((299 * p[2] + 587 * p[1] + 114 * p[0] + 500) / 1000);
                                p[0] = gray;
                                p[1] = gray;
                                p[2] = gray;
                            }
                        }
                        break;

                    case PixelProcessingMode.SequentialVectorized:
                        for (int y = 0; y < height; y++)
                        {
                            ApplyGrayscaleRowSimd(scan0 + y * rowBytes, width);
                        }
                        break;

                    case PixelProcessingMode.Parallel:
                        Parallel.For(0, height, y =>
                        {
                            byte* row = scan0 + y * rowBytes;
                            for (int x = 0; x < width; x++)
                            {
                                byte* p = row + x * 4;
                                byte gray = (byte)((299 * p[2] + 587 * p[1] + 114 * p[0] + 500) / 1000);
                                p[0] = gray;
                                p[1] = gray;
                                p[2] = gray;
                            }
                        });
                        break;

                    case PixelProcessingMode.ParallelVectorized:
                        Parallel.For(0, height, y =>
                        {
                            ApplyGrayscaleRowSimd(scan0 + y * rowBytes, width);
                        });
                        break;
                }
            }
        }

        private static unsafe void ApplyGrayscaleRowSimd(byte* row, int width)
        {
            int x = 0;
            int unrollLimit = width - (width % 4);
            for (; x < unrollLimit; x += 4)
            {
                byte* p0 = row + (x + 0) * 4;
                byte* p1 = row + (x + 1) * 4;
                byte* p2 = row + (x + 2) * 4;
                byte* p3 = row + (x + 3) * 4;

                byte g0 = (byte)((299 * p0[2] + 587 * p0[1] + 114 * p0[0] + 500) / 1000);
                byte g1 = (byte)((299 * p1[2] + 587 * p1[1] + 114 * p1[0] + 500) / 1000);
                byte g2 = (byte)((299 * p2[2] + 587 * p2[1] + 114 * p2[0] + 500) / 1000);
                byte g3 = (byte)((299 * p3[2] + 587 * p3[1] + 114 * p3[0] + 500) / 1000);

                p0[0] = g0; p0[1] = g0; p0[2] = g0;
                p1[0] = g1; p1[1] = g1; p1[2] = g1;
                p2[0] = g2; p2[1] = g2; p2[2] = g2;
                p3[0] = g3; p3[1] = g3; p3[2] = g3;
            }

            for (; x < width; x++)
            {
                byte* p = row + x * 4;
                byte gray = (byte)((299 * p[2] + 587 * p[1] + 114 * p[0] + 500) / 1000);
                p[0] = gray;
                p[1] = gray;
                p[2] = gray;
            }
        }

        public static WriteableBitmap DetectEdges(
            this Bitmap bitmap,
            double threshold = 0.0,
            PixelProcessingMode mode = PixelProcessingMode.Parallel)
        {
            ArgumentNullException.ThrowIfNull(bitmap);
            var wb = bitmap.ConvertToWriteableBitmap();
            var result = new WriteableBitmap(
                wb.PixelSize,
                wb.Dpi,
                Avalonia.Platform.PixelFormat.Bgra8888,
                Avalonia.Platform.AlphaFormat.Premul);

            ApplySobelInternal(wb, result, threshold, mode);
            return result;
        }

        public static void ApplySobel(
            this WriteableBitmap bitmap,
            double threshold = 0.0,
            PixelProcessingMode mode = PixelProcessingMode.Parallel)
        {
            ArgumentNullException.ThrowIfNull(bitmap);
            var temp = new WriteableBitmap(
                bitmap.PixelSize,
                bitmap.Dpi,
                Avalonia.Platform.PixelFormat.Bgra8888,
                Avalonia.Platform.AlphaFormat.Premul);

            ApplySobelInternal(bitmap, temp, threshold, mode);

            using var srcFb = temp.Lock();
            using var dstFb = bitmap.Lock();
            unsafe
            {
                Buffer.MemoryCopy(
                    (void*)srcFb.Address,
                    (void*)dstFb.Address,
                    (long)dstFb.RowBytes * dstFb.Size.Height,
                    (long)srcFb.RowBytes * srcFb.Size.Height);
            }
        }

        private static void ApplySobelInternal(
            WriteableBitmap src,
            WriteableBitmap dst,
            double threshold,
            PixelProcessingMode mode)
        {
            using var srcFb = src.Lock();
            using var dstFb = dst.Lock();

            int width = srcFb.Size.Width;
            int height = srcFb.Size.Height;
            int srcRowBytes = srcFb.RowBytes;
            int dstRowBytes = dstFb.RowBytes;

            unsafe
            {
                byte* srcScan0 = (byte*)srcFb.Address;
                byte* dstScan0 = (byte*)dstFb.Address;

                void ProcessRow(int y)
                {
                    byte* rowDst = dstScan0 + y * dstRowBytes;

                    if (y == 0 || y == height - 1)
                    {
                        for (int x = 0; x < width; x++)
                        {
                            byte* p = rowDst + x * 4;
                            p[0] = 0; p[1] = 0; p[2] = 0; p[3] = 255;
                        }
                        return;
                    }

                    byte* rowSrcPrev = srcScan0 + (y - 1) * srcRowBytes;
                    byte* rowSrcCurr = srcScan0 + y * srcRowBytes;
                    byte* rowSrcNext = srcScan0 + (y + 1) * srcRowBytes;

                    rowDst[0] = 0; rowDst[1] = 0; rowDst[2] = 0; rowDst[3] = 255;

                    for (int x = 1; x < width - 1; x++)
                    {
                        int p00 = GetLuminance(rowSrcPrev + (x - 1) * 4);
                        int p01 = GetLuminance(rowSrcPrev + x * 4);
                        int p02 = GetLuminance(rowSrcPrev + (x + 1) * 4);

                        int p10 = GetLuminance(rowSrcCurr + (x - 1) * 4);
                        int p12 = GetLuminance(rowSrcCurr + (x + 1) * 4);

                        int p20 = GetLuminance(rowSrcNext + (x - 1) * 4);
                        int p21 = GetLuminance(rowSrcNext + x * 4);
                        int p22 = GetLuminance(rowSrcNext + (x + 1) * 4);

                        int gx = (p02 + 2 * p12 + p22) - (p00 + 2 * p10 + p20);
                        int gy = (p20 + 2 * p21 + p22) - (p00 + 2 * p01 + p02);

                        int mag = (int)Math.Sqrt(gx * gx + gy * gy);
                        if (mag > 255) mag = 255;
                        if (mag < threshold) mag = 0;

                        byte* p = rowDst + x * 4;
                        byte val = (byte)mag;
                        p[0] = val;
                        p[1] = val;
                        p[2] = val;
                        p[3] = 255;
                    }

                    byte* pLast = rowDst + (width - 1) * 4;
                    pLast[0] = 0; pLast[1] = 0; pLast[2] = 0; pLast[3] = 255;
                }

                if (mode is PixelProcessingMode.Parallel or PixelProcessingMode.ParallelVectorized)
                {
                    Parallel.For(0, height, ProcessRow);
                }
                else
                {
                    for (int y = 0; y < height; y++)
                    {
                        ProcessRow(y);
                    }
                }
            }
        }

        private static unsafe int GetLuminance(byte* p) =>
            (299 * p[2] + 587 * p[1] + 114 * p[0] + 500) / 1000;

        public static WriteableBitmap ApplyBlur(
            this Bitmap bitmap,
            int radius = 2,
            PixelProcessingMode mode = PixelProcessingMode.Parallel)
        {
            ArgumentNullException.ThrowIfNull(bitmap);
            var wb = bitmap.ConvertToWriteableBitmap();
            ApplyGaussianBlur(wb, radius, mode);
            return wb;
        }

        public static void ApplyGaussianBlur(
            this WriteableBitmap bitmap,
            int radius = 2,
            PixelProcessingMode mode = PixelProcessingMode.Parallel)
        {
            ArgumentNullException.ThrowIfNull(bitmap);
            radius = Math.Clamp(radius, 1, 50);

            int size = radius * 2 + 1;
            float[] kernel = new float[size];
            float sigma = Math.Max((float)radius / 2.0f, 0.5f);
            float twoSigmaSq = 2.0f * sigma * sigma;
            float sum = 0f;

            for (int i = -radius; i <= radius; i++)
            {
                float val = MathF.Exp(-(i * i) / twoSigmaSq);
                kernel[i + radius] = val;
                sum += val;
            }

            for (int i = 0; i < size; i++)
            {
                kernel[i] /= sum;
            }

            ApplySeparableConvolution(bitmap, kernel, radius, mode);
        }

        public static void ApplyBoxBlur(
            this WriteableBitmap bitmap,
            int radius = 2,
            PixelProcessingMode mode = PixelProcessingMode.Parallel)
        {
            ArgumentNullException.ThrowIfNull(bitmap);
            radius = Math.Clamp(radius, 1, 50);
            int size = radius * 2 + 1;
            float weight = 1.0f / size;
            float[] kernel = new float[size];
            Array.Fill(kernel, weight);

            ApplySeparableConvolution(bitmap, kernel, radius, mode);
        }

        private static unsafe void ApplySeparableConvolution(
            WriteableBitmap bitmap,
            float[] kernel,
            int radius,
            PixelProcessingMode mode)
        {
            using var fb = bitmap.Lock();
            int width = fb.Size.Width;
            int height = fb.Size.Height;
            int rowBytes = fb.RowBytes;

            nuint bufferSize = (nuint)rowBytes * (nuint)height;
            byte* tempScan0 = (byte*)System.Runtime.InteropServices.NativeMemory.Alloc(bufferSize);

            try
            {
                byte* scan0 = (byte*)fb.Address;

                void HorizontalPass(int y)
                {
                    byte* srcRow = scan0 + y * rowBytes;
                    byte* dstRow = tempScan0 + y * rowBytes;

                    for (int x = 0; x < width; x++)
                    {
                        float b = 0, g = 0, r = 0, a = 0;
                        for (int k = -radius; k <= radius; k++)
                        {
                            int sampleX = Math.Clamp(x + k, 0, width - 1);
                            byte* p = srcRow + sampleX * 4;
                            float w = kernel[k + radius];
                            b += p[0] * w;
                            g += p[1] * w;
                            r += p[2] * w;
                            a += p[3] * w;
                        }

                        byte* outP = dstRow + x * 4;
                        outP[0] = (byte)Math.Clamp((int)Math.Round(b), 0, 255);
                        outP[1] = (byte)Math.Clamp((int)Math.Round(g), 0, 255);
                        outP[2] = (byte)Math.Clamp((int)Math.Round(r), 0, 255);
                        outP[3] = (byte)Math.Clamp((int)Math.Round(a), 0, 255);
                    }
                }

                void VerticalPass(int y)
                {
                    byte* dstRow = scan0 + y * rowBytes;

                    for (int x = 0; x < width; x++)
                    {
                        float b = 0, g = 0, r = 0, a = 0;
                        for (int k = -radius; k <= radius; k++)
                        {
                            int sampleY = Math.Clamp(y + k, 0, height - 1);
                            byte* p = tempScan0 + sampleY * rowBytes + x * 4;
                            float w = kernel[k + radius];
                            b += p[0] * w;
                            g += p[1] * w;
                            r += p[2] * w;
                            a += p[3] * w;
                        }

                        byte* outP = dstRow + x * 4;
                        outP[0] = (byte)Math.Clamp((int)Math.Round(b), 0, 255);
                        outP[1] = (byte)Math.Clamp((int)Math.Round(g), 0, 255);
                        outP[2] = (byte)Math.Clamp((int)Math.Round(r), 0, 255);
                        outP[3] = (byte)Math.Clamp((int)Math.Round(a), 0, 255);
                    }
                }

                if (mode is PixelProcessingMode.Parallel or PixelProcessingMode.ParallelVectorized)
                {
                    Parallel.For(0, height, HorizontalPass);
                    Parallel.For(0, height, VerticalPass);
                }
                else
                {
                    for (int y = 0; y < height; y++)
                    {
                        HorizontalPass(y);
                    }
                    for (int y = 0; y < height; y++)
                    {
                        VerticalPass(y);
                    }
                }
            }
            finally
            {
                System.Runtime.InteropServices.NativeMemory.Free(tempScan0);
            }
        }

        /// <summary>
        /// 載入本機檔案路徑或 avares:// 資源路徑之 Bitmap（具備動態組件修正、相對路徑尋訪與磁碟目錄後備容錯機制）。
        /// </summary>
        public static Bitmap? LoadBitmap(string? pathOrUri)
        {
            if (string.IsNullOrWhiteSpace(pathOrUri)) return null;

            var trimmed = pathOrUri.Trim();

            // 1. 若為本機實體檔案路徑且檔案存在，直接自檔案載入
            try
            {
                if (System.IO.File.Exists(trimmed))
                {
                    return new Bitmap(trimmed);
                }
            }
            catch
            {
                // 忽略直接讀檔錯誤，進入後續資源/相對路徑解析
            }

            // 2. 解析 avares:// 或相對 Assets 資源路徑
            try
            {
                if (trimmed.StartsWith("avares://", StringComparison.OrdinalIgnoreCase))
                {
                    var uri = new Uri(trimmed);
                    if (Avalonia.Platform.AssetLoader.Exists(uri))
                    {
                        using var stream = Avalonia.Platform.AssetLoader.Open(uri);
                        return new Bitmap(stream);
                    }

                    // 若指定的 Assembly 在 URI 中不匹配 (例如 URI 為 avares://MainFormApp/Assets/logo.png 但實際組件名為 MainFormApp.Shared)
                    // 提取相對資源路徑 (例如 "Assets/logo.png")
                    var resourceRelativePath = uri.AbsolutePath.TrimStart('/');

                    // 嘗試透過目前組件 (typeof(BitmapHelper).Assembly) 重新建構 avares:// URI
                    var currentAsmName = typeof(BitmapHelper).Assembly.GetName().Name;
                    if (!string.IsNullOrEmpty(currentAsmName))
                    {
                        var candidateUri = new Uri($"avares://{currentAsmName}/{resourceRelativePath}");
                        if (Avalonia.Platform.AssetLoader.Exists(candidateUri))
                        {
                            using var stream = Avalonia.Platform.AssetLoader.Open(candidateUri);
                            return new Bitmap(stream);
                        }
                    }

                    // 嘗試透過 EntryAssembly 或 EntryAssembly.Shared 重新建構
                    var entryAsm = System.Reflection.Assembly.GetEntryAssembly();
                    if (entryAsm != null)
                    {
                        var entryName = entryAsm.GetName().Name;
                        if (!string.IsNullOrEmpty(entryName))
                        {
                            var candidateUri1 = new Uri($"avares://{entryName}/{resourceRelativePath}");
                            if (Avalonia.Platform.AssetLoader.Exists(candidateUri1))
                            {
                                using var stream = Avalonia.Platform.AssetLoader.Open(candidateUri1);
                                return new Bitmap(stream);
                            }

                            var candidateUri2 = new Uri($"avares://{entryName}.Shared/{resourceRelativePath}");
                            if (Avalonia.Platform.AssetLoader.Exists(candidateUri2))
                            {
                                using var stream = Avalonia.Platform.AssetLoader.Open(candidateUri2);
                                return new Bitmap(stream);
                            }
                        }
                    }

                    // 嘗試掃描所有目前已載入的應用程式組件
                    foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
                    {
                        if (asm.IsDynamic) continue;
                        var asmName = asm.GetName().Name;
                        if (string.IsNullOrEmpty(asmName) || asmName.StartsWith("System.", StringComparison.OrdinalIgnoreCase) || asmName.StartsWith("Microsoft.", StringComparison.OrdinalIgnoreCase)) continue;

                        var candidateUri = new Uri($"avares://{asmName}/{resourceRelativePath}");
                        if (Avalonia.Platform.AssetLoader.Exists(candidateUri))
                        {
                            using var stream = Avalonia.Platform.AssetLoader.Open(candidateUri);
                            return new Bitmap(stream);
                        }
                    }
                }
                else
                {
                    // 非 avares:// 開頭之相對路徑字串 (例如 "Assets/logo.png", "logo.png", "assets/images/pic.png")
                    var cleanRelative = trimmed.TrimStart('/', '\\').Replace('\\', '/');
                    var fileName = System.IO.Path.GetFileName(cleanRelative);
                    var possiblePaths = new[]
                    {
                        cleanRelative,
                        $"Assets/{cleanRelative}",
                        $"Assets/{fileName}"
                    };

                    var targetAsmNames = new System.Collections.Generic.List<string>();
                    var currentAsmName = typeof(BitmapHelper).Assembly.GetName().Name;
                    if (!string.IsNullOrEmpty(currentAsmName)) targetAsmNames.Add(currentAsmName);

                    var entryName = System.Reflection.Assembly.GetEntryAssembly()?.GetName().Name;
                    if (!string.IsNullOrEmpty(entryName))
                    {
                        targetAsmNames.Add(entryName);
                        targetAsmNames.Add($"{entryName}.Shared");
                    }

                    foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
                    {
                        if (asm.IsDynamic) continue;
                        var name = asm.GetName().Name;
                        if (!string.IsNullOrEmpty(name) && !name.StartsWith("System.", StringComparison.OrdinalIgnoreCase) && !name.StartsWith("Microsoft.", StringComparison.OrdinalIgnoreCase) && !targetAsmNames.Contains(name))
                        {
                            targetAsmNames.Add(name);
                        }
                    }

                    foreach (var asmName in targetAsmNames)
                    {
                        foreach (var resPath in possiblePaths)
                        {
                            var candidateUri = new Uri($"avares://{asmName}/{resPath}");
                            if (Avalonia.Platform.AssetLoader.Exists(candidateUri))
                            {
                                using var stream = Avalonia.Platform.AssetLoader.Open(candidateUri);
                                return new Bitmap(stream);
                            }
                        }
                    }
                }
            }
            catch
            {
                // 忽略資源解析異常，進入磁碟後備搜尋
            }

            // 3. 後備機制：在應用程式目錄、執行目錄與 Assets 子目錄搜尋實體檔案
            try
            {
                var rawFileName = System.IO.Path.GetFileName(trimmed.Replace('/', System.IO.Path.DirectorySeparatorChar).Replace('\\', System.IO.Path.DirectorySeparatorChar));
                var baseDir = AppContext.BaseDirectory;
                var currentDir = System.IO.Directory.GetCurrentDirectory();

                var diskCandidates = new[]
                {
                    System.IO.Path.Combine(baseDir, trimmed),
                    System.IO.Path.Combine(baseDir, "Assets", rawFileName),
                    System.IO.Path.Combine(baseDir, rawFileName),
                    System.IO.Path.Combine(currentDir, trimmed),
                    System.IO.Path.Combine(currentDir, "Assets", rawFileName),
                    System.IO.Path.Combine(currentDir, rawFileName)
                };

                foreach (var diskPath in diskCandidates)
                {
                    if (System.IO.File.Exists(diskPath))
                    {
                        return new Bitmap(diskPath);
                    }
                }
            }
            catch
            {
                // 防禦性忽略磁碟讀取例外
            }

            return null;
        }
    }

    /// <summary>
    /// 提供操作 Bitmap 的靜態類別便捷呼叫方法。
    /// </summary>
    public static class BitmapHelper
    {
        public static WriteableBitmap CreateInitializedBitmap(int width, int height, IBrush? backgroundColor = null) =>
            BitmapExtensions.CreateInitializedBitmap(width, height, backgroundColor);

        public static WriteableBitmap CreateInitializedBitmap(double width, double height, IBrush? backgroundColor = null) =>
            BitmapExtensions.CreateInitializedBitmap(width, height, backgroundColor);

        public static WriteableBitmap CreateInitializedBitmap(int width, int height, Color color) =>
            BitmapExtensions.CreateInitializedBitmap(width, height, color);

        public static WriteableBitmap CreateInitializedBitmap(double width, double height, Color color) =>
            BitmapExtensions.CreateInitializedBitmap(width, height, color);

        public static WriteableBitmap ConvertToWriteableBitmap(Bitmap bitmap) => bitmap.ConvertToWriteableBitmap();

        public static RenderTargetBitmap ConvertToRenderTargetBitmap(Bitmap bitmap) => bitmap.ConvertToRenderTargetBitmap();

        public static void SetPixel(WriteableBitmap bitmap, int x, int y, Color color) => bitmap.SetPixel(x, y, color);

        public static Color GetPixel(WriteableBitmap bitmap, int x, int y) => bitmap.GetPixel(x, y);

        public static Bitmap? LoadBitmap(string? pathOrUri) => BitmapExtensions.LoadBitmap(pathOrUri);

        public static void ProcessPixels(
            WriteableBitmap bitmap,
            PixelProcessor processor,
            PixelProcessingMode mode = PixelProcessingMode.Parallel) =>
            bitmap.ProcessPixels(processor, mode);

        public static void ProcessPixels(
            WriteableBitmap bitmap,
            PixelLocationProcessor processor,
            PixelProcessingMode mode = PixelProcessingMode.Parallel) =>
            bitmap.ProcessPixels(processor, mode);

        public static WriteableBitmap ToGrayscale(
            Bitmap bitmap,
            PixelProcessingMode mode = PixelProcessingMode.ParallelVectorized) =>
            bitmap.ToGrayscale(mode);

        public static void ApplyGrayscale(
            WriteableBitmap bitmap,
            PixelProcessingMode mode = PixelProcessingMode.ParallelVectorized) =>
            bitmap.ApplyGrayscale(mode);

        public static WriteableBitmap DetectEdges(
            Bitmap bitmap,
            double threshold = 0.0,
            PixelProcessingMode mode = PixelProcessingMode.Parallel) =>
            bitmap.DetectEdges(threshold, mode);

        public static void ApplySobel(
            WriteableBitmap bitmap,
            double threshold = 0.0,
            PixelProcessingMode mode = PixelProcessingMode.Parallel) =>
            bitmap.ApplySobel(threshold, mode);

        public static WriteableBitmap ApplyBlur(
            Bitmap bitmap,
            int radius = 2,
            PixelProcessingMode mode = PixelProcessingMode.Parallel) =>
            bitmap.ApplyBlur(radius, mode);

        public static void ApplyGaussianBlur(
            WriteableBitmap bitmap,
            int radius = 2,
            PixelProcessingMode mode = PixelProcessingMode.Parallel) =>
            bitmap.ApplyGaussianBlur(radius, mode);

        public static void ApplyBoxBlur(
            WriteableBitmap bitmap,
            int radius = 2,
            PixelProcessingMode mode = PixelProcessingMode.Parallel) =>
            bitmap.ApplyBoxBlur(radius, mode);
    }
    """;
}
