// filepath: src/AFG.Generators/CSharpMarkup/CSharpMarkupViewGenerator.cs
using System.Globalization;
using System.Text;
using AFG.Generators.Roslyn;

namespace AFG.Generators.CSharpMarkup;

/// <summary>
/// 將 UI AST 中介語意模型遞迴轉譯為純 C# Declarative Markup View 程式碼的生成器。
/// </summary>
public sealed class CSharpMarkupViewGenerator : ICodeGenerator
{
    public GeneratedSourceFile Generate(FormDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using System.Linq.Expressions;");
        sb.AppendLine("using Avalonia;");
        sb.AppendLine("using Avalonia.Controls;");
        sb.AppendLine("using Avalonia.Data;");
        sb.AppendLine("using Avalonia.Input;");
        sb.AppendLine("using Avalonia.Interactivity;");
        sb.AppendLine("using Avalonia.Layout;");
        sb.AppendLine("using Avalonia.Media;");
        sb.AppendLine("using Avalonia.Media.Imaging;");
        sb.AppendLine("using Avalonia.Threading;");
        sb.AppendLine();
        sb.AppendLine($"namespace {document.RootNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {document.ViewClassName} : UserControl");
        sb.AppendLine("{");
        sb.AppendLine($"    public {document.ViewClassName}()");
        sb.AppendLine("    {");
        sb.AppendLine("        InitializeComponent();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private void InitializeComponent()");
        sb.AppendLine("    {");

        // 遞迴生成根節點
        var rootNodeName = !string.IsNullOrWhiteSpace(document.RootNode.Name) ? document.RootNode.Name.Trim() : document.RootNode.Type.ToString();
        sb.AppendLine($"        // {rootNodeName}");
        var rootCode = GenerateNodeCode(document.RootNode, indentLevel: 2, document.ViewModelClassName, document.UseCompiledBindings, parentNode: null, isRoot: true, rootNamespace: document.RootNamespace);
        sb.AppendLine($"        Content = {rootCode};");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return new GeneratedSourceFile(
            FileName: $"{document.ViewClassName}.cs",
            Content: sb.ToString(),
            FileType: SourceFileType.View);
    }

    /// <summary>
    /// 遞迴將 AST 節點轉換為 C# Fluent 鏈式調用語法。
    /// </summary>
    public static string GenerateNodeCode(AstNode node, int indentLevel, string viewModelClassName, bool useCompiledBindings = false, AstNode? parentNode = null, bool isRoot = false, string rootNamespace = "MainFormApp")
    {
        ArgumentNullException.ThrowIfNull(node);

        var indent = new string(' ', indentLevel * 4);
        var innerIndent = new string(' ', (indentLevel + 1) * 4);
        var sb = new StringBuilder();

        if (node.Type == ControlType.DebugConsole)
        {
            return GenerateDebugConsoleCode(node, indentLevel, viewModelClassName, useCompiledBindings, parentNode, isRoot);
        }

        var nodeName = !string.IsNullOrWhiteSpace(node.Name) ? node.Name.Trim() : node.Type.ToString();
        if (!isRoot)
        {
            sb.AppendLine($"{indent}// {nodeName}");
        }

        var controlTypeName = node.Type == ControlType.PictureBox ? "Image" : node.Type.ToString();
        if (isRoot)
        {
            sb.AppendLine($"new {controlTypeName}()");
        }
        else
        {
            sb.AppendLine($"{indent}new {controlTypeName}()");
        }

        // 1. 幾何與佈局屬性
        if (!node.AutoSize)
        {
            if (node.Width.HasValue)
            {
                sb.AppendLine($"{innerIndent}.Width({node.Width.Value.ToString(CultureInfo.InvariantCulture)})");
            }

            if (node.Height.HasValue)
            {
                sb.AppendLine($"{innerIndent}.Height({node.Height.Value.ToString(CultureInfo.InvariantCulture)})");
            }
        }

        if (node.MinWidth.HasValue)
        {
            sb.AppendLine($"{innerIndent}.MinWidth({node.MinWidth.Value.ToString(CultureInfo.InvariantCulture)})");
        }

        if (node.MinHeight.HasValue)
        {
            sb.AppendLine($"{innerIndent}.MinHeight({node.MinHeight.Value.ToString(CultureInfo.InvariantCulture)})");
        }

        if (node.MaxWidth.HasValue)
        {
            sb.AppendLine($"{innerIndent}.MaxWidth({node.MaxWidth.Value.ToString(CultureInfo.InvariantCulture)})");
        }

        if (node.MaxHeight.HasValue)
        {
            sb.AppendLine($"{innerIndent}.MaxHeight({node.MaxHeight.Value.ToString(CultureInfo.InvariantCulture)})");
        }

        if (node.Margin != ThicknessModel.Zero)
        {
            sb.AppendLine($"{innerIndent}.Margin(new Thickness({FormatThickness(node.Margin)}))");
        }

        if (node.Padding != ThicknessModel.Zero)
        {
            sb.AppendLine($"{innerIndent}.Padding(new Thickness({FormatThickness(node.Padding)}))");
        }

        if (node.HorizontalAlignment != HorizontalAlignment.Stretch)
        {
            sb.AppendLine($"{innerIndent}.HorizontalAlignment(HorizontalAlignment.{node.HorizontalAlignment})");
        }

        if (node.VerticalAlignment != VerticalAlignment.Stretch)
        {
            sb.AppendLine($"{innerIndent}.VerticalAlignment(VerticalAlignment.{node.VerticalAlignment})");
        }

        if (node.Opacity < 1.0)
        {
            sb.AppendLine($"{innerIndent}.Opacity({node.Opacity.ToString(CultureInfo.InvariantCulture)})");
        }

        if (!node.IsEnabled)
        {
            sb.AppendLine($"{innerIndent}.IsEnabled(false)");
        }

        if (!node.IsVisible)
        {
            sb.AppendLine($"{innerIndent}.IsVisible(false)");
        }

        if (node.ZIndex != 0)
        {
            sb.AppendLine($"{innerIndent}.ZIndex({node.ZIndex})");
        }

        // 2. 容器附屬屬性 (Attached Properties - 依據父容器型別精準輸出，避免語意矛盾)
        var isCanvasChild = parentNode is null || parentNode.Type == ControlType.Canvas;
        var isGridChild = parentNode?.Type == ControlType.Grid;
        var isDockChild = parentNode?.Type == ControlType.DockPanel;

        if (isCanvasChild)
        {
            if (node.CanvasLeft.HasValue)
            {
                sb.AppendLine($"{innerIndent}.CanvasLeft({node.CanvasLeft.Value.ToString(CultureInfo.InvariantCulture)})");
            }

            if (node.CanvasTop.HasValue)
            {
                sb.AppendLine($"{innerIndent}.CanvasTop({node.CanvasTop.Value.ToString(CultureInfo.InvariantCulture)})");
            }
        }

        if (isGridChild)
        {
            if (node.GridRow != 0)
            {
                sb.AppendLine($"{innerIndent}.GridRow({node.GridRow})");
            }

            if (node.GridColumn != 0)
            {
                sb.AppendLine($"{innerIndent}.GridColumn({node.GridColumn})");
            }

            if (node.GridRowSpan > 1)
            {
                sb.AppendLine($"{innerIndent}.GridRowSpan({node.GridRowSpan})");
            }

            if (node.GridColumnSpan > 1)
            {
                sb.AppendLine($"{innerIndent}.GridColumnSpan({node.GridColumnSpan})");
            }
        }

        if (isDockChild && node.Dock.HasValue)
        {
            sb.AppendLine($"{innerIndent}.Dock(Dock.{node.Dock.Value})");
        }

        // 3. 容器專屬設置
        if (node.RowDefinitions.Count > 0)
        {
            var rowDefs = string.Join(", ", node.RowDefinitions.Select(r => $"\"{CSharpSyntaxSanitizer.EscapeStringLiteral(r.ToString())}\""));
            sb.AppendLine($"{innerIndent}.RowDefinitions({rowDefs})");
        }

        if (node.ColumnDefinitions.Count > 0)
        {
            var colDefs = string.Join(", ", node.ColumnDefinitions.Select(c => $"\"{CSharpSyntaxSanitizer.EscapeStringLiteral(c.ToString())}\""));
            sb.AppendLine($"{innerIndent}.ColumnDefinitions({colDefs})");
        }

        if (node.Orientation.HasValue)
        {
            sb.AppendLine($"{innerIndent}.Orientation(Orientation.{node.Orientation.Value})");
        }

        // 4. 控制項專屬外觀與內容（採用 Roslyn 標準轉義防護特殊字元）
        var boundProps = new HashSet<string>(node.Bindings.Select(b => b.TargetProperty), StringComparer.Ordinal);

        if (!boundProps.Contains("Text") && !string.IsNullOrEmpty(node.Text))
        {
            sb.AppendLine($"{innerIndent}.Text(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(node.Text)}\")");
        }
        else if (!boundProps.Contains("Content") && !string.IsNullOrEmpty(node.Content))
        {
            sb.AppendLine($"{innerIndent}.Content(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(node.Content)}\")");
        }

        if (!boundProps.Contains("Header") && !string.IsNullOrEmpty(node.Header))
        {
            sb.AppendLine($"{innerIndent}.Header(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(node.Header)}\")");
        }

        if (!boundProps.Contains("Watermark") && !string.IsNullOrEmpty(node.Watermark))
        {
            sb.AppendLine($"{innerIndent}.Watermark(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(node.Watermark)}\")");
        }

        if (!boundProps.Contains("IsChecked") && node.IsChecked.HasValue)
        {
            sb.AppendLine($"{innerIndent}.IsChecked({(node.IsChecked.Value ? "true" : "false")})");
        }

        if (!boundProps.Contains("Value") && node.Value.HasValue)
        {
            sb.AppendLine($"{innerIndent}.Value({node.Value.Value.ToString(CultureInfo.InvariantCulture)})");
        }

        if (!boundProps.Contains("FontSize") && node.FontSize.HasValue)
        {
            sb.AppendLine($"{innerIndent}.FontSize({node.FontSize.Value.ToString(CultureInfo.InvariantCulture)})");
        }

        if (!string.IsNullOrWhiteSpace(node.Background))
        {
            sb.AppendLine($"{innerIndent}.Background(Brush.Parse(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(node.Background)}\"))");
        }

        if (!string.IsNullOrWhiteSpace(node.Foreground))
        {
            sb.AppendLine($"{innerIndent}.Foreground(Brush.Parse(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(node.Foreground)}\"))");
        }

        if (!boundProps.Contains("Source"))
        {
            if (node.InitBitmap)
            {
                var w = (node.Width ?? 200).ToString(CultureInfo.InvariantCulture);
                var h = (node.Height ?? 150).ToString(CultureInfo.InvariantCulture);
                var bg = string.IsNullOrWhiteSpace(node.BitmapBackgroundColor) ? "#F0F0F0" : node.BitmapBackgroundColor.Trim();
                sb.AppendLine($"{innerIndent}.Source(BitmapHelper.CreateInitializedBitmap({w}, {h}, Brush.Parse(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(bg)}\")))");
            }
            else if (!string.IsNullOrWhiteSpace(node.Source))
            {
                var sourcePath = node.Source.Trim();
                if (node.UseRelativePath)
                {
                    var fileName = System.IO.Path.GetFileName(sourcePath);
                    var sharedAsmName = rootNamespace.EndsWith(".Shared", StringComparison.OrdinalIgnoreCase)
                        ? rootNamespace
                        : $"{rootNamespace}.Shared";
                    var assetUri = sourcePath.StartsWith("avares://", StringComparison.OrdinalIgnoreCase) || sourcePath.StartsWith("http", StringComparison.OrdinalIgnoreCase)
                        ? sourcePath
                        : $"avares://{sharedAsmName}/Assets/{fileName}";
                    sb.AppendLine($"{innerIndent}.Source(BitmapHelper.LoadBitmap(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(assetUri)}\"))");
                }
                else
                {
                    sb.AppendLine($"{innerIndent}.Source(BitmapHelper.LoadBitmap(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(sourcePath)}\"))");
                }
            }
        }

        if (!boundProps.Contains("Stretch") && node.Stretch.HasValue)
        {
            sb.AppendLine($"{innerIndent}.Stretch(Stretch.{node.Stretch.Value})");
        }

        // 5. MVVM 綁定配置 (一律傳遞明確的 BindingMode 列舉參數，並進行關鍵字逃逸)
        foreach (var binding in node.Bindings)
        {
            var normalizedProp = Mvvm.MvvmViewModelGenerator.NormalizePropertyName(binding.ViewModelProperty);
            var safeProp = CSharpSyntaxSanitizer.EscapeIdentifier(normalizedProp);
            var modeName = binding.Mode switch
            {
                BindingMode.TwoWay => "BindingMode.TwoWay",
                BindingMode.OneWay => "BindingMode.OneWay",
                BindingMode.OneWayToSource => "BindingMode.OneWayToSource",
                BindingMode.OneTime => "BindingMode.OneTime",
                _ => (node.Type == ControlType.TextBox || binding.TargetProperty == "Text" || binding.TargetProperty == "IsChecked" || binding.TargetProperty == "Value")
                    ? "BindingMode.TwoWay"
                    : "BindingMode.Default"
            };

            var bindingCall = useCompiledBindings
                ? $".{binding.TargetProperty}(({viewModelClassName} vm) => vm.{safeProp}, {modeName})"
                : $".{binding.TargetProperty}(nameof({viewModelClassName}.{safeProp}), {modeName})";

            sb.AppendLine($"{innerIndent}{bindingCall}");
        }

        // 6. 事件映射至命令 (標準化 Command 名稱並進行關鍵字逃逸，支援 CommandParameter 傳遞)
        foreach (var evt in node.Events)
        {
            var normalizedCmd = Mvvm.MvvmViewModelGenerator.NormalizeCommandName(evt.CommandProperty);
            var safeCmd = CSharpSyntaxSanitizer.EscapeIdentifier(normalizedCmd);
            var effectiveParams = evt.GetEffectiveParameters();

            string cmdCall;
            var paramWithBinding = effectiveParams.FirstOrDefault(p => !string.IsNullOrWhiteSpace(p.ValueOrPath));

            if (paramWithBinding is null)
            {
                var eventMethod = evt.EventName switch
                {
                    "Click" => "OnClick",
                    "Tapped" => "OnTapped",
                    "DoubleTapped" => "OnDoubleTapped",
                    "PointerPressed" => "OnPointerPressed",
                    "PointerReleased" => "OnPointerReleased",
                    "PointerMoved" => "OnPointerMoved",
                    "KeyDown" => "OnKeyDown",
                    "KeyUp" => "OnKeyUp",
                    "TextChanged" => "OnTextChanged",
                    "SelectionChanged" => "OnSelectionChanged",
                    "ValueChanged" => "OnValueChanged",
                    _ => "Command"
                };

                cmdCall = useCompiledBindings
                    ? $".{eventMethod}(({viewModelClassName} vm) => vm.{safeCmd})"
                    : $".{eventMethod}(nameof({viewModelClassName}.{safeCmd}))";
            }
            else if (paramWithBinding.IsConstant)
            {
                var escapedParam = CSharpSyntaxSanitizer.EscapeStringLiteral(paramWithBinding.ValueOrPath!);
                cmdCall = useCompiledBindings
                    ? $".Command(({viewModelClassName} vm) => vm.{safeCmd}, \"{escapedParam}\")"
                    : $".Command(nameof({viewModelClassName}.{safeCmd}), \"{escapedParam}\")";
            }
            else
            {
                var normalizedParam = Mvvm.MvvmViewModelGenerator.NormalizePropertyName(paramWithBinding.ValueOrPath!);
                var safeParam = CSharpSyntaxSanitizer.EscapeIdentifier(normalizedParam);
                cmdCall = useCompiledBindings
                    ? $".Command(({viewModelClassName} vm) => vm.{safeCmd}, ({viewModelClassName} vm) => vm.{safeParam})"
                    : $".Command(nameof({viewModelClassName}.{safeCmd}), nameof({viewModelClassName}.{safeParam}))";
            }

            sb.AppendLine($"{innerIndent}{cmdCall}");
        }

        // 7. 遞迴生成子節點 (Children - 傳遞當前 node 作為 parentNode 參數)
        var visualChildren = node.Children
            .Where(c => !IsNonVisualComponent(c.Type))
            .ToList();

        if (visualChildren.Count > 0)
        {
            var isBorder = node.Type == ControlType.Border;
            var containerMethod = isBorder ? "Child" : "Children";
            sb.AppendLine($"{innerIndent}.{containerMethod}(");
            for (var i = 0; i < visualChildren.Count; i++)
            {
                var childCode = GenerateNodeCode(visualChildren[i], indentLevel + 2, viewModelClassName, useCompiledBindings, parentNode: node, rootNamespace: rootNamespace);
                var isLast = i == visualChildren.Count - 1;
                var trailingComma = isLast ? string.Empty : ",";
                sb.AppendLine($"{childCode}{trailingComma}");
            }
            sb.Append($"{innerIndent})");
        }

        return sb.ToString().TrimEnd();
    }

    private static string GenerateDebugConsoleCode(AstNode node, int indentLevel, string viewModelClassName, bool useCompiledBindings, AstNode? parentNode, bool isRoot)
    {
        var indent = new string(' ', indentLevel * 4);
        var innerIndent = new string(' ', (indentLevel + 1) * 4);
        var sb = new StringBuilder();

        var nodeName = !string.IsNullOrWhiteSpace(node.Name) ? node.Name.Trim() : "DebugConsole";
        if (!isRoot)
        {
            sb.AppendLine($"{indent}// {nodeName}");
            sb.AppendLine($"{indent}new Border()");
        }
        else
        {
            sb.AppendLine("new Border()");
        }
        sb.AppendLine($"{innerIndent}.Background(Brush.Parse(\"#09090B\"))");
        sb.AppendLine($"{innerIndent}.BorderBrush(Brush.Parse(\"#27272A\"))");
        sb.AppendLine($"{innerIndent}.BorderThickness(new Thickness(1))");
        sb.AppendLine($"{innerIndent}.CornerRadius(new CornerRadius(6))");
        sb.AppendLine($"{innerIndent}.Padding(new Thickness(6))");

        if (node.Width.HasValue)
        {
            sb.AppendLine($"{innerIndent}.Width({node.Width.Value.ToString(CultureInfo.InvariantCulture)})");
        }
        if (node.Height.HasValue)
        {
            sb.AppendLine($"{innerIndent}.Height({node.Height.Value.ToString(CultureInfo.InvariantCulture)})");
        }

        var isCanvasChild = parentNode is null || parentNode.Type == ControlType.Canvas;
        var isGridChild = parentNode?.Type == ControlType.Grid;
        var isDockChild = parentNode?.Type == ControlType.DockPanel;

        if (isCanvasChild)
        {
            if (node.CanvasLeft.HasValue)
                sb.AppendLine($"{innerIndent}.CanvasLeft({node.CanvasLeft.Value.ToString(CultureInfo.InvariantCulture)})");
            if (node.CanvasTop.HasValue)
                sb.AppendLine($"{innerIndent}.CanvasTop({node.CanvasTop.Value.ToString(CultureInfo.InvariantCulture)})");
        }

        if (isGridChild)
        {
            if (node.GridRow != 0) sb.AppendLine($"{innerIndent}.GridRow({node.GridRow})");
            if (node.GridColumn != 0) sb.AppendLine($"{innerIndent}.GridColumn({node.GridColumn})");
            if (node.GridRowSpan > 1) sb.AppendLine($"{innerIndent}.GridRowSpan({node.GridRowSpan})");
            if (node.GridColumnSpan > 1) sb.AppendLine($"{innerIndent}.GridColumnSpan({node.GridColumnSpan})");
        }

        if (isDockChild && node.Dock.HasValue)
        {
            sb.AppendLine($"{innerIndent}.Dock(Dock.{node.Dock.Value})");
        }

        var clearCmdExpr = useCompiledBindings
            ? $"({viewModelClassName} vm) => vm.ClearLogsCommand"
            : $"nameof({viewModelClassName}.ClearLogsCommand)";

        var logItemsExpr = useCompiledBindings
            ? $"({viewModelClassName} vm) => vm.LogEntries"
            : $"nameof({viewModelClassName}.LogEntries)";

        var title = string.IsNullOrWhiteSpace(node.Text) ? "Debug Console" : node.Text;

        sb.AppendLine($"{innerIndent}.Child(");
        sb.AppendLine($"{innerIndent}    new Grid()");
        sb.AppendLine($"{innerIndent}        .RowDefinitions(\"Auto, *\")");
        sb.AppendLine($"{innerIndent}        .Children(");
        sb.AppendLine($"{innerIndent}            new DockPanel()");
        sb.AppendLine($"{innerIndent}                .Margin(new Thickness(0, 0, 0, 4))");
        sb.AppendLine($"{innerIndent}                .Children(");
        sb.AppendLine($"{innerIndent}                    new TextBlock()");
        sb.AppendLine($"{innerIndent}                        .Text(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(title)}\")");
        sb.AppendLine($"{innerIndent}                        .FontSize(11)");
        sb.AppendLine($"{innerIndent}                        .FontWeight(FontWeight.Bold)");
        sb.AppendLine($"{innerIndent}                        .Foreground(Brush.Parse(\"#E4E4E7\"))");
        sb.AppendLine($"{innerIndent}                        .VerticalAlignment(VerticalAlignment.Center)");
        sb.AppendLine($"{innerIndent}                        .Dock(Dock.Left),");
        sb.AppendLine($"{innerIndent}                    new Button()");
        sb.AppendLine($"{innerIndent}                        .Content(\"Clear\")");
        sb.AppendLine($"{innerIndent}                        .FontSize(10)");
        sb.AppendLine($"{innerIndent}                        .Padding(new Thickness(8, 2))");
        sb.AppendLine($"{innerIndent}                        .Background(Brush.Parse(\"#27272A\"))");
        sb.AppendLine($"{innerIndent}                        .Foreground(Brushes.White)");
        sb.AppendLine($"{innerIndent}                        .HorizontalAlignment(HorizontalAlignment.Right)");
        sb.AppendLine($"{innerIndent}                        .Command({clearCmdExpr})");
        sb.AppendLine($"{innerIndent}                ),");
        sb.AppendLine($"{innerIndent}            new ListBox()");
        sb.AppendLine($"{innerIndent}                .GridRow(1)");
        sb.AppendLine($"{innerIndent}                .Background(Brushes.Transparent)");
        sb.AppendLine($"{innerIndent}                .Foreground(Brush.Parse(\"#A1A1AA\"))");
        sb.AppendLine($"{innerIndent}                .FontSize(10)");
        sb.AppendLine($"{innerIndent}                .ItemsSource({logItemsExpr})");
        sb.AppendLine($"{innerIndent}        )");
        sb.Append($"{innerIndent})");

        return sb.ToString().TrimEnd();
    }

    public static bool IsNonVisualComponent(ControlType type) => type switch
    {
        ControlType.DispatcherTimer or ControlType.BackgroundWorker or
        ControlType.BluetoothClient or ControlType.SerialPortService or
        ControlType.OpenFileDialog or ControlType.SaveFileDialog or ControlType.MessageBox => true,
        _ => false
    };

    private static string FormatThickness(ThicknessModel thickness) =>
        $"{thickness.Left.ToString(CultureInfo.InvariantCulture)}, {thickness.Top.ToString(CultureInfo.InvariantCulture)}, {thickness.Right.ToString(CultureInfo.InvariantCulture)}, {thickness.Bottom.ToString(CultureInfo.InvariantCulture)}";
}
