// filepath: src/AFG.Generators/CSharpMarkup/CSharpMarkupViewGenerator.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using AFG.Core.Enums;
using AFG.Core.Models.Ast;
using AFG.Generators.Roslyn;

namespace AFG.Generators.CSharpMarkup;

/// <summary>
/// 表示 Code-Behind 強型別欄位中繼資訊。
/// </summary>
public sealed record CodeBehindFieldInfo(
    string NodeId,
    string FieldName,
    string ControlTypeName,
    string ElementName,
    bool HasConflict,
    string? ConflictWarning);

/// <summary>
/// 將 UI AST 中介語意模型遞迴轉譯為純 C# Declarative Markup View 程式碼的生成器。
/// 支援 Code-Behind / Event-Driven 模式、Pure MVVM 模式與 Hybrid 混合模式。
/// </summary>
public sealed class CSharpMarkupViewGenerator : ICodeGenerator
{
    public GeneratedSourceFile Generate(FormDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        var isCodeBehindMode = document.ArchitectureMode == ArchitectureMode.CodeBehind;
        var fieldMap = document.GenerateCodeBehindFields
            ? CollectCodeBehindFields(document.RootNode)
            : new Dictionary<string, CodeBehindFieldInfo>(StringComparer.Ordinal);

        var codeBehindMethodStubs = new List<string>();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {document.RootNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {document.ViewClassName} : UserControl");
        sb.AppendLine("{");

        // 輸出 Code-Behind 強型別欄位宣告
        if (fieldMap.Count > 0)
        {
            sb.AppendLine("    // 提供編譯期強型別欄位，方便 Code-Behind 使用者 (Code-Behind Friendly Fields)");
            foreach (var field in fieldMap.Values)
            {
                if (field.HasConflict && !string.IsNullOrWhiteSpace(field.ConflictWarning))
                {
                    sb.AppendLine($"    {field.ConflictWarning}");
                }
                sb.AppendLine($"    private {field.ControlTypeName} {field.FieldName};");
            }
            sb.AppendLine();
        }

        sb.AppendLine($"    public {document.ViewClassName}()");
        sb.AppendLine("    {");
        sb.AppendLine("        InitializeComponent();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private void InitializeComponent()");
        sb.AppendLine("    {");
        if (!string.IsNullOrWhiteSpace(document.BackgroundColor))
        {
            sb.AppendLine($"        Background = Brush.Parse(\"{document.BackgroundColor}\");");
        }

        // 遞迴生成根節點
        var rootNodeName = !string.IsNullOrWhiteSpace(document.RootNode.Name) ? document.RootNode.Name.Trim() : document.RootNode.Type.ToString();
        sb.AppendLine($"        // {rootNodeName}");
        var rootCode = GenerateNodeCode(
            document.RootNode,
            indentLevel: 2,
            document.ViewModelClassName,
            document.UseCompiledBindings,
            parentNode: null,
            isRoot: true,
            rootNamespace: document.RootNamespace,
            fieldMap: fieldMap,
            architectureMode: document.ArchitectureMode,
            codeBehindMethodStubs: codeBehindMethodStubs);
        sb.AppendLine($"        Content = {rootCode};");

        // 表單與視窗生命週期事件監聽綁定
        if (document.Events.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("        // 表單事件 (Form Events)");
            foreach (var evt in document.Events)
            {
                if (isCodeBehindMode)
                {
                    var handlerName = $"{document.ViewClassName}_{evt.EventName.Trim()}";
                    sb.AppendLine($"        {evt.EventName} += {handlerName};");
                    codeBehindMethodStubs.Add($$"""
    private void {{handlerName}}(object? sender, EventArgs e)
    {
        // TODO: 在此實作表單 {{evt.EventName}} 事件邏輯
    }
""");
                }
                else
                {
                    if (string.IsNullOrWhiteSpace(evt.CommandProperty)) continue;
                    var normalizedCmd = Mvvm.MvvmViewModelGenerator.NormalizeCommandName(evt.CommandProperty);
                    var safeCmd = CSharpSyntaxSanitizer.EscapeIdentifier(normalizedCmd);
                    sb.AppendLine($"        {evt.EventName} += (sender, e) => (DataContext as {document.ViewModelClassName})?.{safeCmd}.Execute(e);");
                }
            }
        }

        sb.AppendLine("    }");

        // 在 Code-Behind 模式下，產出事件處理方法 Stub
        if (isCodeBehindMode && codeBehindMethodStubs.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("    #region 事件處理常式 (Event Handlers)");
            foreach (var stub in codeBehindMethodStubs.Distinct())
            {
                sb.AppendLine(stub);
            }
            sb.AppendLine("    #endregion");
        }

        sb.AppendLine("}");

        return new GeneratedSourceFile(
            FileName: $"{document.ViewClassName}.cs",
            Content: sb.ToString(),
            FileType: SourceFileType.View);
    }

    /// <summary>
    /// 遍歷 AST 節點並過濾收集所有需要生成 Code-Behind 欄位的控制項，並處理命名衝突保護。
    /// </summary>
    public static Dictionary<string, CodeBehindFieldInfo> CollectCodeBehindFields(AstNode rootNode)
    {
        var fieldMap = new Dictionary<string, CodeBehindFieldInfo>(StringComparer.Ordinal);
        var usedFieldNames = new HashSet<string>(StringComparer.Ordinal);
        var conflictCounter = 1;

        void Traverse(AstNode node, bool isRoot)
        {
            if (ShouldGenerateFieldForNode(node, isRoot))
            {
                var rawName = node.Name!.Trim();
                var cleanName = CSharpSyntaxSanitizer.SanitizeIdentifier(rawName);

                string baseField;
                if (cleanName.StartsWith('_'))
                {
                    baseField = cleanName;
                }
                else
                {
                    baseField = "_" + char.ToLowerInvariant(cleanName[0]) + cleanName[1..];
                }

                var cleanElementName = cleanName.TrimStart('_');
                var baseElement = cleanElementName.Length > 0
                    ? char.ToLowerInvariant(cleanElementName[0]) + cleanElementName[1..]
                    : "element";

                var controlTypeName = node.Type switch
                {
                    ControlType.PictureBox => "Image",
                    ControlType.MediaPlayer => "MediaPlayerControl",
                    ControlType.DebugConsole => "Border",
                    _ => node.Type.ToString()
                };

                string finalField;
                string finalElement;
                bool hasConflict = false;
                string? warningMessage = null;

                if (usedFieldNames.Contains(baseField))
                {
                    hasConflict = true;
                    var safeId = !string.IsNullOrWhiteSpace(node.Id)
                        ? CSharpSyntaxSanitizer.SanitizeIdentifier(node.Id.Trim())
                        : $"item{conflictCounter++}";

                    finalField = $"{baseField}_{safeId}";
                    finalElement = $"{baseElement}_{safeId}";

                    while (usedFieldNames.Contains(finalField))
                    {
                        finalField = $"{baseField}_{safeId}_{conflictCounter++}";
                        finalElement = $"{baseElement}_{safeId}_{conflictCounter}";
                    }

                    warningMessage = $"// 提示: 控制項名稱 '{rawName}' 發生重複，已自動附加 ID 後綴 '{safeId}' 以消除衝突保護編譯安全";
                }
                else
                {
                    finalField = baseField;
                    finalElement = baseElement;
                }

                usedFieldNames.Add(finalField);
                var nodeId = node.Id ?? Guid.NewGuid().ToString("N");
                fieldMap[nodeId] = new CodeBehindFieldInfo(nodeId, finalField, controlTypeName, finalElement, hasConflict, warningMessage);
            }

            foreach (var child in node.Children)
            {
                Traverse(child, isRoot: false);
            }
        }

        Traverse(rootNode, isRoot: true);
        return fieldMap;
    }

    /// <summary>
    /// 判定指定節點是否符合生成 Code-Behind 強型別欄位之條件（過濾未命名的純靜態裝飾容器）。
    /// </summary>
    public static bool ShouldGenerateFieldForNode(AstNode node, bool isRoot)
    {
        if (isRoot) return false;
        if (IsNonVisualComponent(node.Type)) return false;
        if (string.IsNullOrWhiteSpace(node.Name)) return false;

        var name = node.Name.Trim();

        // 匿名/未命名的靜態佈局容器與純裝飾 TextBlock，若無任何綁定與事件則維持 Inline 宣告
        if (node.Type is ControlType.Grid or ControlType.StackPanel or ControlType.Canvas or ControlType.DockPanel or ControlType.WrapPanel or ControlType.ScrollViewer or ControlType.Border or ControlType.TextBlock)
        {
            if (name.Equals(node.Type.ToString(), StringComparison.OrdinalIgnoreCase) &&
                node.Events.Count == 0 && node.Bindings.Count == 0)
            {
                return false;
            }
        }

        return true;
    }

    /// <summary>
    /// 遞迴將 AST 節點轉換為 C# Fluent 鏈式調用語法。
    /// </summary>
    public static string GenerateNodeCode(
        AstNode node,
        int indentLevel,
        string viewModelClassName,
        bool useCompiledBindings = false,
        AstNode? parentNode = null,
        bool isRoot = false,
        string rootNamespace = "MainFormApp",
        IReadOnlyDictionary<string, CodeBehindFieldInfo>? fieldMap = null,
        ArchitectureMode architectureMode = ArchitectureMode.Hybrid,
        List<string>? codeBehindMethodStubs = null)
    {
        ArgumentNullException.ThrowIfNull(node);

        var indent = new string(' ', indentLevel * 4);
        var innerIndent = new string(' ', (indentLevel + 1) * 4);
        var sb = new StringBuilder();

        if (node.Type == ControlType.DebugConsole)
        {
            return GenerateDebugConsoleCode(node, indentLevel, viewModelClassName, useCompiledBindings, parentNode, isRoot, fieldMap, architectureMode);
        }

        var nodeName = !string.IsNullOrWhiteSpace(node.Name) ? node.Name.Trim() : node.Type.ToString();
        if (!isRoot)
        {
            sb.AppendLine($"{indent}// {nodeName}");
        }

        var controlTypeName = node.Type switch
        {
            ControlType.PictureBox => "Image",
            ControlType.MediaPlayer => "MediaPlayerControl",
            _ => node.Type.ToString()
        };

        CodeBehindFieldInfo? fieldInfo = null;
        if (fieldMap is not null && !string.IsNullOrWhiteSpace(node.Id))
        {
            fieldMap.TryGetValue(node.Id, out fieldInfo);
        }

        if (fieldInfo is not null)
        {
            if (isRoot)
            {
                sb.AppendLine($"{fieldInfo.FieldName} = new {fieldInfo.ControlTypeName}()");
            }
            else
            {
                sb.AppendLine($"{indent}{fieldInfo.FieldName} = new {fieldInfo.ControlTypeName}()");
            }
            sb.AppendLine($"{innerIndent}.Name(\"{fieldInfo.ElementName}\")");
        }
        else
        {
            if (isRoot)
            {
                sb.AppendLine($"new {controlTypeName}()");
            }
            else
            {
                sb.AppendLine($"{indent}new {controlTypeName}()");
            }
        }

        // 1. 幾何與佈局屬性
        if (!node.AutoSize)
        {
            if (node.Width.HasValue)
            {
                sb.AppendLine($"{innerIndent}.Width({node.Width.Value.ToString(CultureInfo.InvariantCulture)})");
            }

            if (node.Height.HasValue)
            {
                sb.AppendLine($"{innerIndent}.Height({node.Height.Value.ToString(CultureInfo.InvariantCulture)})");
            }
        }

        if (node.MinWidth.HasValue)
        {
            sb.AppendLine($"{innerIndent}.MinWidth({node.MinWidth.Value.ToString(CultureInfo.InvariantCulture)})");
        }

        if (node.MinHeight.HasValue)
        {
            sb.AppendLine($"{innerIndent}.MinHeight({node.MinHeight.Value.ToString(CultureInfo.InvariantCulture)})");
        }

        if (node.MaxWidth.HasValue)
        {
            sb.AppendLine($"{innerIndent}.MaxWidth({node.MaxWidth.Value.ToString(CultureInfo.InvariantCulture)})");
        }

        if (node.MaxHeight.HasValue)
        {
            sb.AppendLine($"{innerIndent}.MaxHeight({node.MaxHeight.Value.ToString(CultureInfo.InvariantCulture)})");
        }

        if (node.Margin != ThicknessModel.Zero)
        {
            sb.AppendLine($"{innerIndent}.Margin(new Thickness({FormatThickness(node.Margin)}))");
        }

        if (node.Padding != ThicknessModel.Zero)
        {
            sb.AppendLine($"{innerIndent}.Padding(new Thickness({FormatThickness(node.Padding)}))");
        }

        if (node.HorizontalAlignment != HorizontalAlignment.Stretch)
        {
            sb.AppendLine($"{innerIndent}.HorizontalAlignment(HorizontalAlignment.{node.HorizontalAlignment})");
        }

        if (node.VerticalAlignment != VerticalAlignment.Stretch)
        {
            sb.AppendLine($"{innerIndent}.VerticalAlignment(VerticalAlignment.{node.VerticalAlignment})");
        }

        if (node.Opacity < 1.0)
        {
            sb.AppendLine($"{innerIndent}.Opacity({node.Opacity.ToString(CultureInfo.InvariantCulture)})");
        }

        if (!node.IsEnabled)
        {
            sb.AppendLine($"{innerIndent}.IsEnabled(false)");
        }

        if (!node.IsVisible)
        {
            sb.AppendLine($"{innerIndent}.IsVisible(false)");
        }

        if (node.ZIndex != 0)
        {
            sb.AppendLine($"{innerIndent}.ZIndex({node.ZIndex})");
        }

        // 2. 容器附屬屬性 (Attached Properties)
        var isCanvasChild = parentNode is null || parentNode.Type == ControlType.Canvas;
        var isGridChild = parentNode?.Type == ControlType.Grid;
        var isDockChild = parentNode?.Type == ControlType.DockPanel;

        if (isCanvasChild)
        {
            if (node.CanvasLeft.HasValue)
            {
                sb.AppendLine($"{innerIndent}.CanvasLeft({node.CanvasLeft.Value.ToString(CultureInfo.InvariantCulture)})");
            }

            if (node.CanvasTop.HasValue)
            {
                sb.AppendLine($"{innerIndent}.CanvasTop({node.CanvasTop.Value.ToString(CultureInfo.InvariantCulture)})");
            }
        }

        if (isGridChild)
        {
            if (node.GridRow != 0)
            {
                sb.AppendLine($"{innerIndent}.GridRow({node.GridRow})");
            }

            if (node.GridColumn != 0)
            {
                sb.AppendLine($"{innerIndent}.GridColumn({node.GridColumn})");
            }

            if (node.GridRowSpan > 1)
            {
                sb.AppendLine($"{innerIndent}.GridRowSpan({node.GridRowSpan})");
            }

            if (node.GridColumnSpan > 1)
            {
                sb.AppendLine($"{innerIndent}.GridColumnSpan({node.GridColumnSpan})");
            }
        }

        if (isDockChild && node.Dock.HasValue)
        {
            sb.AppendLine($"{innerIndent}.Dock(Dock.{node.Dock.Value})");
        }

        // 3. 容器專屬設置
        if (node.RowDefinitions.Count > 0)
        {
            var rowDefs = string.Join(", ", node.RowDefinitions.Select(r => $"\"{CSharpSyntaxSanitizer.EscapeStringLiteral(r.ToString())}\""));
            sb.AppendLine($"{innerIndent}.RowDefinitions({rowDefs})");
        }

        if (node.ColumnDefinitions.Count > 0)
        {
            var colDefs = string.Join(", ", node.ColumnDefinitions.Select(c => $"\"{CSharpSyntaxSanitizer.EscapeStringLiteral(c.ToString())}\""));
            sb.AppendLine($"{innerIndent}.ColumnDefinitions({colDefs})");
        }

        if (node.Orientation.HasValue)
        {
            sb.AppendLine($"{innerIndent}.Orientation(Orientation.{node.Orientation.Value})");
        }

        // 4. 控制項專屬外觀與內容
        var boundProps = architectureMode != ArchitectureMode.CodeBehind
            ? new HashSet<string>(node.Bindings.Select(b => b.TargetProperty), StringComparer.Ordinal)
            : new HashSet<string>(StringComparer.Ordinal);

        if (!boundProps.Contains("Text") && !string.IsNullOrEmpty(node.Text))
        {
            sb.AppendLine($"{innerIndent}.Text(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(node.Text)}\")");
        }
        else if (!boundProps.Contains("Content") && !string.IsNullOrEmpty(node.Content))
        {
            sb.AppendLine($"{innerIndent}.Content(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(node.Content)}\")");
        }

        if (!boundProps.Contains("Header") && !string.IsNullOrEmpty(node.Header))
        {
            sb.AppendLine($"{innerIndent}.Header(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(node.Header)}\")");
        }

        if (!boundProps.Contains("Watermark") && !string.IsNullOrEmpty(node.Watermark))
        {
            sb.AppendLine($"{innerIndent}.Watermark(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(node.Watermark)}\")");
        }

        if (!boundProps.Contains("IsChecked") && node.IsChecked.HasValue)
        {
            sb.AppendLine($"{innerIndent}.IsChecked({(node.IsChecked.Value ? "true" : "false")})");
        }

        if (!boundProps.Contains("Value") && node.Value.HasValue)
        {
            sb.AppendLine($"{innerIndent}.Value({node.Value.Value.ToString(CultureInfo.InvariantCulture)})");
        }

        if (!boundProps.Contains("FontSize") && node.FontSize.HasValue)
        {
            sb.AppendLine($"{innerIndent}.FontSize({node.FontSize.Value.ToString(CultureInfo.InvariantCulture)})");
        }

        if (!string.IsNullOrWhiteSpace(node.Background))
        {
            sb.AppendLine($"{innerIndent}.Background(Brush.Parse(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(node.Background)}\"))");
        }

        if (!string.IsNullOrWhiteSpace(node.Foreground))
        {
            sb.AppendLine($"{innerIndent}.Foreground(Brush.Parse(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(node.Foreground)}\"))");
        }

        if (node.Type == ControlType.MediaPlayer)
        {
            if (!boundProps.Contains("Source") && !string.IsNullOrWhiteSpace(node.Source))
            {
                sb.AppendLine($"{innerIndent}.Source(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(node.Source.Trim())}\")");
            }
            if (!boundProps.Contains("AutoPlay") && node.AutoPlay == true)
            {
                sb.AppendLine($"{innerIndent}.AutoPlay(true)");
            }
            if (!boundProps.Contains("IsLooping") && node.IsLooping == true)
            {
                sb.AppendLine($"{innerIndent}.IsLooping(true)");
            }
            if (!boundProps.Contains("Volume") && node.Volume.HasValue)
            {
                sb.AppendLine($"{innerIndent}.Volume({node.Volume.Value.ToString(CultureInfo.InvariantCulture)})");
            }
        }
        else if (!boundProps.Contains("Source"))
        {
            if (node.InitBitmap)
            {
                var w = (node.Width ?? 200).ToString(CultureInfo.InvariantCulture);
                var h = (node.Height ?? 150).ToString(CultureInfo.InvariantCulture);
                var bg = string.IsNullOrWhiteSpace(node.BitmapBackgroundColor) ? "#F0F0F0" : node.BitmapBackgroundColor.Trim();
                sb.AppendLine($"{innerIndent}.Source(BitmapHelper.CreateInitializedBitmap({w}, {h}, Brush.Parse(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(bg)}\")))");
            }
            else if (!string.IsNullOrWhiteSpace(node.Source))
            {
                var sourcePath = node.Source.Trim();
                if (node.UseRelativePath)
                {
                    var fileName = System.IO.Path.GetFileName(sourcePath.Replace('\\', '/'));
                    var sharedAsmName = rootNamespace.EndsWith(".Shared", StringComparison.OrdinalIgnoreCase)
                        ? rootNamespace
                        : $"{rootNamespace}.Shared";
                    var assetUri = sourcePath.StartsWith("avares://", StringComparison.OrdinalIgnoreCase) || sourcePath.StartsWith("http", StringComparison.OrdinalIgnoreCase)
                        ? sourcePath
                        : $"avares://{sharedAsmName}/Assets/{fileName}";
                    sb.AppendLine($"{innerIndent}.Source(BitmapHelper.LoadBitmap(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(assetUri)}\"))");
                }
                else
                {
                    sb.AppendLine($"{innerIndent}.Source(BitmapHelper.LoadBitmap(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(sourcePath)}\"))");
                }
            }
        }

        if (!boundProps.Contains("Stretch") && node.Stretch.HasValue)
        {
            sb.AppendLine($"{innerIndent}.Stretch(Stretch.{node.Stretch.Value})");
        }

        // 5. MVVM 綁定配置（僅在 PureMvvm 與 Hybrid 模式下輸出）
        if (architectureMode != ArchitectureMode.CodeBehind)
        {
            foreach (var binding in node.Bindings)
            {
                if (string.IsNullOrWhiteSpace(binding.TargetProperty) || string.IsNullOrWhiteSpace(binding.ViewModelProperty))
                {
                    continue;
                }

                var normalizedProp = Mvvm.MvvmViewModelGenerator.NormalizePropertyName(binding.ViewModelProperty);
                var safeProp = CSharpSyntaxSanitizer.EscapeIdentifier(normalizedProp);
                var modeName = binding.Mode switch
                {
                    BindingMode.TwoWay => "BindingMode.TwoWay",
                    BindingMode.OneWay => "BindingMode.OneWay",
                    BindingMode.OneWayToSource => "BindingMode.OneWayToSource",
                    BindingMode.OneTime => "BindingMode.OneTime",
                    _ => (node.Type == ControlType.TextBox || binding.TargetProperty == "Text" || binding.TargetProperty == "IsChecked" || binding.TargetProperty == "Value")
                        ? "BindingMode.TwoWay"
                        : "BindingMode.Default"
                };

                var bindingCall = useCompiledBindings
                    ? $".{binding.TargetProperty.Trim()}(({viewModelClassName} vm) => vm.{safeProp}, {modeName})"
                    : $".{binding.TargetProperty.Trim()}(nameof({viewModelClassName}.{safeProp}), {modeName})";

                sb.AppendLine($"{innerIndent}{bindingCall}");
            }
        }

        // 6. 事件映射 (CodeBehind 模式綁定 View 內部事件處理常式，MVVM / Hybrid 模式轉譯為 Command)
        foreach (var evt in node.Events)
        {
            if (string.IsNullOrWhiteSpace(evt.EventName))
            {
                continue;
            }

            var eventMethod = evt.EventName.Trim() switch
            {
                "Click" => "OnClick",
                "Tapped" => "OnTapped",
                "DoubleTapped" => "OnDoubleTapped",
                "PointerPressed" => "OnPointerPressed",
                "PointerReleased" => "OnPointerReleased",
                "PointerMoved" => "OnPointerMoved",
                "KeyDown" => "OnKeyDown",
                "KeyUp" => "OnKeyUp",
                "TextChanged" => "OnTextChanged",
                "SelectionChanged" => "OnSelectionChanged",
                "ValueChanged" => "OnValueChanged",
                "MediaOpened" => "OnMediaOpened",
                "MediaEnded" => "OnMediaEnded",
                "FrameCaptured" => "OnFrameCaptured",
                _ => "Command"
            };

            if (architectureMode == ArchitectureMode.CodeBehind)
            {
                var rawPrefix = fieldInfo != null ? fieldInfo.ElementName : CSharpSyntaxSanitizer.SanitizeIdentifier(node.Name ?? node.Type.ToString());
                var cleanPrefix = rawPrefix.TrimStart('_');
                if (cleanPrefix.Length > 0) cleanPrefix = char.ToUpperInvariant(cleanPrefix[0]) + cleanPrefix[1..];
                else cleanPrefix = "Control";

                var handlerName = $"{cleanPrefix}_{evt.EventName.Trim()}";
                sb.AppendLine($"{innerIndent}.{eventMethod}({handlerName})");

                var (argsType, argName) = GetEventArgsInfo(evt.EventName);
                codeBehindMethodStubs?.Add($$"""
    private void {{handlerName}}(object? sender, {{argsType}} {{argName}})
    {
        // TODO: 在此實作 {{cleanPrefix}} 的 {{evt.EventName}} 事件邏輯
    }
""");
            }
            else
            {
                if (string.IsNullOrWhiteSpace(evt.CommandProperty))
                {
                    continue;
                }

                var normalizedCmd = Mvvm.MvvmViewModelGenerator.NormalizeCommandName(evt.CommandProperty);
                var safeCmd = CSharpSyntaxSanitizer.EscapeIdentifier(normalizedCmd);
                var effectiveParams = evt.GetEffectiveParameters();

                string cmdCall;
                var paramWithBinding = effectiveParams.FirstOrDefault(p => !string.IsNullOrWhiteSpace(p.ValueOrPath));

                if (paramWithBinding is null)
                {
                    cmdCall = useCompiledBindings
                        ? $".{eventMethod}(({viewModelClassName} vm) => vm.{safeCmd})"
                        : $".{eventMethod}(nameof({viewModelClassName}.{safeCmd}))";
                }
                else if (paramWithBinding.IsConstant)
                {
                    cmdCall = useCompiledBindings
                        ? $".Command(({viewModelClassName} vm) => vm.{safeCmd}, \"{CSharpSyntaxSanitizer.EscapeStringLiteral(paramWithBinding.ValueOrPath!)}\")"
                        : $".Command(nameof({viewModelClassName}.{safeCmd}), \"{CSharpSyntaxSanitizer.EscapeStringLiteral(paramWithBinding.ValueOrPath!)}\")";
                }
                else
                {
                    var normalizedParam = Mvvm.MvvmViewModelGenerator.NormalizePropertyName(paramWithBinding.ValueOrPath!);
                    var safeParam = CSharpSyntaxSanitizer.EscapeIdentifier(normalizedParam);
                    cmdCall = useCompiledBindings
                        ? $".Command(({viewModelClassName} vm) => vm.{safeCmd}, ({viewModelClassName} vm) => vm.{safeParam})"
                        : $".Command(nameof({viewModelClassName}.{safeCmd}), nameof({viewModelClassName}.{safeParam}))";
                }

                sb.AppendLine($"{innerIndent}{cmdCall}");
            }
        }

        // 7. 遞迴生成子節點
        var visualChildren = node.Children
            .Where(c => !IsNonVisualComponent(c.Type))
            .ToList();

        if (visualChildren.Count > 0)
        {
            var isBorder = node.Type == ControlType.Border;
            var containerMethod = isBorder ? "Child" : "Children";
            sb.AppendLine($"{innerIndent}.{containerMethod}(");
            for (var i = 0; i < visualChildren.Count; i++)
            {
                var childCode = GenerateNodeCode(
                    visualChildren[i],
                    indentLevel + 2,
                    viewModelClassName,
                    useCompiledBindings,
                    parentNode: node,
                    rootNamespace: rootNamespace,
                    fieldMap: fieldMap,
                    architectureMode: architectureMode,
                    codeBehindMethodStubs: codeBehindMethodStubs);
                var isLast = i == visualChildren.Count - 1;
                var trailingComma = isLast ? string.Empty : ",";
                sb.AppendLine($"{childCode}{trailingComma}");
            }
            sb.Append($"{innerIndent})");
        }

        return sb.ToString().TrimEnd();
    }

    private static string GenerateDebugConsoleCode(
        AstNode node,
        int indentLevel,
        string viewModelClassName,
        bool useCompiledBindings,
        AstNode? parentNode,
        bool isRoot,
        IReadOnlyDictionary<string, CodeBehindFieldInfo>? fieldMap = null,
        ArchitectureMode architectureMode = ArchitectureMode.Hybrid)
    {
        var indent = new string(' ', indentLevel * 4);
        var innerIndent = new string(' ', (indentLevel + 1) * 4);
        var sb = new StringBuilder();

        var nodeName = !string.IsNullOrWhiteSpace(node.Name) ? node.Name.Trim() : "DebugConsole";
        if (!isRoot)
        {
            sb.AppendLine($"{indent}// {nodeName}");
        }

        CodeBehindFieldInfo? fieldInfo = null;
        if (fieldMap is not null && !string.IsNullOrWhiteSpace(node.Id))
        {
            fieldMap.TryGetValue(node.Id, out fieldInfo);
        }

        if (fieldInfo is not null)
        {
            if (isRoot)
            {
                sb.AppendLine($"{fieldInfo.FieldName} = new Border()");
            }
            else
            {
                sb.AppendLine($"{indent}{fieldInfo.FieldName} = new Border()");
            }
            sb.AppendLine($"{innerIndent}.Name(\"{fieldInfo.ElementName}\")");
        }
        else
        {
            if (isRoot)
            {
                sb.AppendLine("new Border()");
            }
            else
            {
                sb.AppendLine($"{indent}new Border()");
            }
        }

        sb.AppendLine($"{innerIndent}.Background(Brush.Parse(\"#09090B\"))");
        sb.AppendLine($"{innerIndent}.BorderBrush(Brush.Parse(\"#27272A\"))");
        sb.AppendLine($"{innerIndent}.BorderThickness(new Thickness(1))");
        sb.AppendLine($"{innerIndent}.CornerRadius(new CornerRadius(6))");
        sb.AppendLine($"{innerIndent}.Padding(new Thickness(6))");

        if (node.Width.HasValue)
        {
            sb.AppendLine($"{innerIndent}.Width({node.Width.Value.ToString(CultureInfo.InvariantCulture)})");
        }
        if (node.Height.HasValue)
        {
            sb.AppendLine($"{innerIndent}.Height({node.Height.Value.ToString(CultureInfo.InvariantCulture)})");
        }

        var isCanvasChild = parentNode is null || parentNode.Type == ControlType.Canvas;
        var isGridChild = parentNode?.Type == ControlType.Grid;
        var isDockChild = parentNode?.Type == ControlType.DockPanel;

        if (isCanvasChild)
        {
            if (node.CanvasLeft.HasValue)
                sb.AppendLine($"{innerIndent}.CanvasLeft({node.CanvasLeft.Value.ToString(CultureInfo.InvariantCulture)})");
            if (node.CanvasTop.HasValue)
                sb.AppendLine($"{innerIndent}.CanvasTop({node.CanvasTop.Value.ToString(CultureInfo.InvariantCulture)})");
        }

        if (isGridChild)
        {
            if (node.GridRow != 0) sb.AppendLine($"{innerIndent}.GridRow({node.GridRow})");
            if (node.GridColumn != 0) sb.AppendLine($"{innerIndent}.GridColumn({node.GridColumn})");
            if (node.GridRowSpan > 1) sb.AppendLine($"{innerIndent}.GridRowSpan({node.GridRowSpan})");
            if (node.GridColumnSpan > 1) sb.AppendLine($"{innerIndent}.GridColumnSpan({node.GridColumnSpan})");
        }

        if (isDockChild && node.Dock.HasValue)
        {
            sb.AppendLine($"{innerIndent}.Dock(Dock.{node.Dock.Value})");
        }

        var clearCmdExpr = architectureMode != ArchitectureMode.CodeBehind
            ? (useCompiledBindings
                ? $".Command(({viewModelClassName} vm) => vm.ClearLogsCommand)"
                : $".Command(nameof({viewModelClassName}.ClearLogsCommand))")
            : string.Empty;

        var logItemsExpr = architectureMode != ArchitectureMode.CodeBehind
            ? (useCompiledBindings
                ? $".ItemsSource(({viewModelClassName} vm) => vm.LogEntries)"
                : $".ItemsSource(nameof({viewModelClassName}.LogEntries))")
            : string.Empty;

        var title = string.IsNullOrWhiteSpace(node.Text) ? "Debug Console" : node.Text;

        sb.AppendLine($"{innerIndent}.Child(");
        sb.AppendLine($"{innerIndent}    new Grid()");
        sb.AppendLine($"{innerIndent}        .RowDefinitions(\"Auto, *\")");
        sb.AppendLine($"{innerIndent}        .Children(");
        sb.AppendLine($"{innerIndent}            new DockPanel()");
        sb.AppendLine($"{innerIndent}                .Margin(new Thickness(0, 0, 0, 4))");
        sb.AppendLine($"{innerIndent}                .Children(");
        sb.AppendLine($"{innerIndent}                    new TextBlock()");
        sb.AppendLine($"{innerIndent}                        .Text(\"{CSharpSyntaxSanitizer.EscapeStringLiteral(title)}\")");
        sb.AppendLine($"{innerIndent}                        .FontSize(11)");
        sb.AppendLine($"{innerIndent}                        .FontWeight(FontWeight.Bold)");
        sb.AppendLine($"{innerIndent}                        .Foreground(Brush.Parse(\"#E4E4E7\"))");
        sb.AppendLine($"{innerIndent}                        .VerticalAlignment(VerticalAlignment.Center)");
        sb.AppendLine($"{innerIndent}                        .Dock(Dock.Left),");
        sb.AppendLine($"{innerIndent}                    new Button()");
        sb.AppendLine($"{innerIndent}                        .Content(\"Clear\")");
        sb.AppendLine($"{innerIndent}                        .FontSize(10)");
        sb.AppendLine($"{innerIndent}                        .Padding(new Thickness(8, 2))");
        sb.AppendLine($"{innerIndent}                        .Background(Brush.Parse(\"#27272A\"))");
        sb.AppendLine($"{innerIndent}                        .Foreground(Brushes.White)");
        sb.AppendLine($"{innerIndent}                        .HorizontalAlignment(HorizontalAlignment.Right)");
        if (!string.IsNullOrEmpty(clearCmdExpr))
        {
            sb.AppendLine($"{innerIndent}                        {clearCmdExpr}");
        }
        sb.AppendLine($"{innerIndent}                ),");
        sb.AppendLine($"{innerIndent}            new ListBox()");
        sb.AppendLine($"{innerIndent}                .GridRow(1)");
        sb.AppendLine($"{innerIndent}                .Background(Brushes.Transparent)");
        sb.AppendLine($"{innerIndent}                .Foreground(Brush.Parse(\"#A1A1AA\"))");
        sb.AppendLine($"{innerIndent}                .FontSize(10)");
        if (!string.IsNullOrEmpty(logItemsExpr))
        {
            sb.AppendLine($"{innerIndent}                {logItemsExpr}");
        }
        sb.AppendLine($"{innerIndent}        )");
        sb.Append($"{innerIndent})");

        return sb.ToString().TrimEnd();
    }

    public static bool IsNonVisualComponent(ControlType type) => type switch
    {
        ControlType.DispatcherTimer or ControlType.BackgroundWorker or
        ControlType.BluetoothClient or ControlType.SerialPortService or
        ControlType.OpenFileDialog or ControlType.SaveFileDialog or ControlType.MessageBox => true,
        _ => false
    };

    public static (string ArgsType, string ArgName) GetEventArgsInfo(string eventName) => eventName.Trim() switch
    {
        "Click" => ("RoutedEventArgs", "e"),
        "Tapped" => ("TappedEventArgs", "e"),
        "DoubleTapped" => ("TappedEventArgs", "e"),
        "PointerPressed" => ("PointerPressedEventArgs", "e"),
        "PointerReleased" => ("PointerReleasedEventArgs", "e"),
        "PointerMoved" => ("PointerEventArgs", "e"),
        "KeyDown" => ("KeyEventArgs", "e"),
        "KeyUp" => ("KeyEventArgs", "e"),
        "TextChanged" => ("TextChangedEventArgs", "e"),
        "SelectionChanged" => ("SelectionChangedEventArgs", "e"),
        "ValueChanged" => ("RangeBaseValueChangedEventArgs", "e"),
        "MediaOpened" => ("EventArgs", "e"),
        "MediaEnded" => ("EventArgs", "e"),
        "FrameCaptured" => ("Bitmap", "e"),
        _ => ("RoutedEventArgs", "e")
    };

    private static string FormatThickness(ThicknessModel thickness) =>
        $"{thickness.Left.ToString(CultureInfo.InvariantCulture)}, {thickness.Top.ToString(CultureInfo.InvariantCulture)}, {thickness.Right.ToString(CultureInfo.InvariantCulture)}, {thickness.Bottom.ToString(CultureInfo.InvariantCulture)}";
}
