// filepath: src/AFG.Generators/ProjectExport/ProjectExportService.cs
namespace AFG.Generators.ProjectExport;

/// <summary>
/// 產出符合 Visual Studio 2022/2026 現代化方案格式 (包含 .slnx) 之獨立可編譯 Avalonia .NET 10 MVVM 專案的匯出服務。
/// </summary>
public sealed class ProjectExportService(FormCodeGenerator? codeGenerator = null)
{
    private readonly FormCodeGenerator _codeGenerator = codeGenerator ?? new FormCodeGenerator();

    /// <summary>
    /// 生成包含 Visual Studio 方案檔 (.slnx)、專案檔 (.csproj)、進入點、樣式與 View/ViewModel 的檔案集合。
    /// </summary>
    public IReadOnlyList<GeneratedSourceFile> GenerateFullProject(FormDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        var result = _codeGenerator.GenerateAll(document);
        var files = new List<GeneratedSourceFile>(result.Files);

        var projectName = string.IsNullOrWhiteSpace(document.ViewClassName)
            ? "GeneratedApp"
            : document.ViewClassName.Replace("View", "", StringComparison.Ordinal) + "App";

        // 1. 生成 Visual Studio 現代化方案檔 (.slnx)
        var slnxContent = $"""
        <Solution>
          <Project Path="{projectName}.csproj" />
        </Solution>
        """;

        files.Add(new GeneratedSourceFile($"{projectName}.slnx", slnxContent, SourceFileType.SolutionFile));

        // 2. 生成 .csproj 專案檔
        var csprojContent = $"""
        <Project Sdk="Microsoft.NET.Sdk">
          <PropertyGroup>
            <OutputType>WinExe</OutputType>
            <TargetFramework>net10.0</TargetFramework>
            <Nullable>enable</Nullable>
            <ImplicitUsings>enable</ImplicitUsings>
            <LangVersion>latest</LangVersion>
            <RootNamespace>{document.RootNamespace}</RootNamespace>
          </PropertyGroup>

          <ItemGroup>
            <PackageReference Include="Avalonia" Version="11.2.5" />
            <PackageReference Include="Avalonia.Desktop" Version="11.2.5" />
            <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.5" />
            <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.5" />
            <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
          </ItemGroup>
        </Project>
        """;

        files.Add(new GeneratedSourceFile($"{projectName}.csproj", csprojContent, SourceFileType.ProjectFile));

        // 3. 生成 Program.cs
        var programContent = $$"""
        // <auto-generated />
        using System;
        using Avalonia;

        namespace {{document.RootNamespace}};

        internal static class Program
        {
            [STAThread]
            public static void Main(string[] args) =>
                BuildAvaloniaApp().StartWithClassicDesktopLifetime(args);

            public static AppBuilder BuildAvaloniaApp() =>
                AppBuilder.Configure<App>()
                    .UsePlatformDetect()
                    .WithInterFont()
                    .LogToTrace();
        }
        """;

        files.Add(new GeneratedSourceFile("Program.cs", programContent, SourceFileType.ProjectFile));

        // 4. 生成 App.axaml 與 App.axaml.cs
        var appAxaml = $$"""
        <Application xmlns="https://github.com/avaloniaui"
                     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                     x:Class="{{document.RootNamespace}}.App"
                     RequestedThemeVariant="Dark">
            <Application.Styles>
                <FluentTheme />
            </Application.Styles>
        </Application>
        """;

        var appCs = $$"""
        // <auto-generated />
        using Avalonia;
        using Avalonia.Controls.ApplicationLifetimes;
        using Avalonia.Markup.Xaml;

        namespace {{document.RootNamespace}};

        public partial class App : Application
        {
            public override void Initialize() => AvaloniaXamlLoader.Load(this);

            public override void OnFrameworkInitializationCompleted()
            {
                if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
                {
                    var view = new {{document.ViewClassName}}();
                    view.DataContext = new {{document.ViewModelClassName}}();

                    desktop.MainWindow = new Avalonia.Controls.Window
                    {
                        Title = "{{document.Title}}",
                        Width = {{document.CanvasWidth}},
                        Height = {{document.CanvasHeight}},
                        Content = view
                    };
                }

                base.OnFrameworkInitializationCompleted();
            }
        }
        """;

        files.Add(new GeneratedSourceFile("App.axaml", appAxaml, SourceFileType.ProjectFile));
        files.Add(new GeneratedSourceFile("App.axaml.cs", appCs, SourceFileType.ProjectFile));

        // 5. 生成 Visual Studio .gitignore
        var gitignoreContent = """
        ## Visual Studio
        .vs/
        [Bb]in/
        [Oo]bj/
        *.user
        *.suo
        *.userosscache
        *.sln.docstates
        """;

        files.Add(new GeneratedSourceFile(".gitignore", gitignoreContent, SourceFileType.ProjectFile));

        // 6. 生成 Visual Studio .editorconfig
        var editorconfigContent = """
        root = true

        [*]
        indent_style = space
        indent_size = 4
        end_of_line = crlf
        charset = utf-8
        trim_trailing_whitespace = true
        insert_final_newline = true

        [*.cs]
        csharp_prefer_braces = true:suggestion
        csharp_style_namespace_declarations = file_scoped:suggestion
        """;

        files.Add(new GeneratedSourceFile(".editorconfig", editorconfigContent, SourceFileType.ProjectFile));

        return files.ToImmutableList();
    }

    /// <summary>
    /// 將完整專案檔案寫出至本機資料夾。
    /// </summary>
    public async Task ExportToFolderAsync(FormDocument document, string destinationDirectory, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(document);
        ArgumentException.ThrowIfNullOrWhiteSpace(destinationDirectory);

        if (!Directory.Exists(destinationDirectory))
        {
            Directory.CreateDirectory(destinationDirectory);
        }

        var files = GenerateFullProject(document);
        foreach (var file in files)
        {
            var filePath = Path.Combine(destinationDirectory, file.FileName);
            await File.WriteAllTextAsync(filePath, file.Content, Encoding.UTF8, cancellationToken);
        }
    }
}
