// filepath: src/AFG.Generators/ProjectExport/ProjectExportService.cs
using AFG.Generators.CSharpMarkup;

namespace AFG.Generators.ProjectExport;

/// <summary>
/// 產出符合 Visual Studio 2022+ 現代化解決方案與純 C# 宣告式架構 (含 .slnx, App.cs, Config.cs, GlobalUsings.cs, Services, ViewModels, Views) 之專案匯出服務。
/// </summary>
public sealed class ProjectExportService(FormCodeGenerator? codeGenerator = null)
{
    private readonly FormCodeGenerator _codeGenerator = codeGenerator ?? new FormCodeGenerator();

    /// <summary>
    /// 生成包含 Visual Studio 現代化方案檔 (.slnx)、專案子資料夾、純 C# App 初始化與分層目錄之檔案集合。
    /// </summary>
    public IReadOnlyList<GeneratedSourceFile> GenerateFullProject(FormDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        var result = _codeGenerator.GenerateAll(document);
        var files = new List<GeneratedSourceFile>();

        var projectName = string.IsNullOrWhiteSpace(document.ViewClassName)
            ? "GeneratedApp"
            : document.ViewClassName.Replace("View", "", StringComparison.Ordinal) + "App";

        var projectDir = projectName;

        // 1. 方案根目錄：Visual Studio 現代化方案檔 (.slnx)
        var slnxContent = $"""
        <Solution>
          <Project Path="{projectName}/{projectName}.csproj" />
        </Solution>
        """;
        files.Add(new GeneratedSourceFile($"{projectName}.slnx", slnxContent, SourceFileType.SolutionFile));

        // 2. 方案根目錄：.gitignore 與 .editorconfig
        var gitignoreContent = """
        ## Visual Studio
        .vs/
        [Bb]in/
        [Oo]bj/
        *.user
        *.suo
        *.userosscache
        *.sln.docstates
        """;
        files.Add(new GeneratedSourceFile(".gitignore", gitignoreContent, SourceFileType.ProjectFile));

        var editorconfigContent = """
        root = true

        [*]
        indent_style = space
        indent_size = 4
        end_of_line = crlf
        charset = utf-8
        trim_trailing_whitespace = true
        insert_final_newline = true

        [*.cs]
        csharp_prefer_braces = true:suggestion
        csharp_style_namespace_declarations = file_scoped:suggestion
        """;
        files.Add(new GeneratedSourceFile(".editorconfig", editorconfigContent, SourceFileType.ProjectFile));

        // 3. 專案檔：{projectName}/{projectName}.csproj
        var csprojContent = $"""
        <Project Sdk="Microsoft.NET.Sdk">
          <PropertyGroup>
            <OutputType>WinExe</OutputType>
            <TargetFramework>net10.0</TargetFramework>
            <Nullable>enable</Nullable>
            <ImplicitUsings>enable</ImplicitUsings>
            <LangVersion>latest</LangVersion>
            <RootNamespace>{document.RootNamespace}</RootNamespace>
          </PropertyGroup>

          <ItemGroup>
            <PackageReference Include="Avalonia" Version="11.2.5" />
            <PackageReference Include="Avalonia.Desktop" Version="11.2.5" />
            <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.5" />
            <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.5" />
            <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
          </ItemGroup>
        </Project>
        """;
        files.Add(new GeneratedSourceFile(Path.Combine(projectDir, $"{projectName}.csproj"), csprojContent, SourceFileType.ProjectFile));

        // 4. 純 C# 應用程式初始化：App.cs
        var appCs = $$"""
        // <auto-generated />
        using Avalonia;
        using Avalonia.Controls;
        using Avalonia.Controls.ApplicationLifetimes;
        using Avalonia.Styling;
        using Avalonia.Themes.Fluent;

        namespace {{document.RootNamespace}};

        /// <summary>
        /// 應用程式初始化與跨平台 UI 生命週期配置。
        /// </summary>
        public partial class App : Application
        {
            public override void Initialize()
            {
                Styles.Add(new FluentTheme());
                RequestedThemeVariant = ThemeVariant.Dark;
            }

            public override void OnFrameworkInitializationCompleted()
            {
                if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
                {
                    var view = new {{document.ViewClassName}}();
                    view.DataContext = new {{document.ViewModelClassName}}();

                    desktop.MainWindow = new Window
                    {
                        Title = Config.AppTitle,
                        Width = Config.DefaultWindowWidth,
                        Height = Config.DefaultWindowHeight,
                        Content = view
                    };
                }

                base.OnFrameworkInitializationCompleted();
            }
        }
        """;
        files.Add(new GeneratedSourceFile(Path.Combine(projectDir, "App.cs"), appCs, SourceFileType.ProjectFile));

        // 5. 全域靜態組態配置：Config.cs
        var configCs = $$"""
        // <auto-generated />
        namespace {{document.RootNamespace}};

        /// <summary>
        /// 全域靜態組態配置（視窗大小、標題、版本等）。
        /// </summary>
        public static class Config
        {
            public const string AppTitle = "{{document.Title}}";
            public const string Version = "1.0.0";
            public const double DefaultWindowWidth = {{document.CanvasWidth}};
            public const double DefaultWindowHeight = {{document.CanvasHeight}};
        }
        """;
        files.Add(new GeneratedSourceFile(Path.Combine(projectDir, "Config.cs"), configCs, SourceFileType.ProjectFile));

        // 6. 共享專案全域引用配置：GlobalUsings.cs
        var globalUsingsCs = $$"""
        // <auto-generated />
        global using System;
        global using System.Collections.Generic;
        global using System.Collections.ObjectModel;
        global using System.ComponentModel;
        global using System.Threading.Tasks;
        global using Avalonia;
        global using Avalonia.Controls;
        global using Avalonia.Data;
        global using Avalonia.Layout;
        global using Avalonia.Media;
        global using Avalonia.Styling;
        global using Avalonia.Themes.Fluent;
        global using CommunityToolkit.Mvvm.ComponentModel;
        global using CommunityToolkit.Mvvm.Input;
        global using {{document.RootNamespace}};
        global using {{document.RootNamespace}}.Services;
        """;
        files.Add(new GeneratedSourceFile(Path.Combine(projectDir, "GlobalUsings.cs"), globalUsingsCs, SourceFileType.ProjectFile));

        // 7. 桌面端程式載入點：Program.cs
        var programCs = $$"""
        // <auto-generated />
        using System;
        using Avalonia;

        namespace {{document.RootNamespace}};

        internal static class Program
        {
            [STAThread]
            public static void Main(string[] args) =>
                BuildAvaloniaApp().StartWithClassicDesktopLifetime(args);

            public static AppBuilder BuildAvaloniaApp() =>
                AppBuilder.Configure<App>()
                    .UsePlatformDetect()
                    .WithInterFont()
                    .LogToTrace();
        }
        """;
        files.Add(new GeneratedSourceFile(Path.Combine(projectDir, "Program.cs"), programCs, SourceFileType.ProjectFile));

        // 8. C# Declarative UI 擴充方法：Markup/AvaloniaMarkupExtensions.cs
        files.Add(new GeneratedSourceFile(
            Path.Combine(projectDir, "Markup", "AvaloniaMarkupExtensions.cs"),
            AvaloniaMarkupExtensionsSource.Code,
            SourceFileType.ProjectFile));

        // 9. 服務層 / Model：Services/GreetingService.cs
        var greetingServiceCs = $$"""
        // <auto-generated />
        namespace {{document.RootNamespace}}.Services;

        /// <summary>
        /// 提供展示資料的服務實例。
        /// </summary>
        public sealed class GreetingService
        {
            public string GetGreeting(string name) =>
                string.IsNullOrWhiteSpace(name) ? "歡迎使用 Avalonia Declarative UI!" : $"你好, {name}!";
        }
        """;
        files.Add(new GeneratedSourceFile(Path.Combine(projectDir, "Services", "GreetingService.cs"), greetingServiceCs, SourceFileType.ProjectFile));

        // 10. 檢視層與檢視模型層：Views 與 ViewModels
        var viewFile = result.Files.FirstOrDefault(f => f.FileType == SourceFileType.View);
        if (viewFile is not null)
        {
            files.Add(new GeneratedSourceFile(
                Path.Combine(projectDir, "Views", viewFile.FileName),
                viewFile.Content,
                SourceFileType.View));
        }

        var vmFile = result.Files.FirstOrDefault(f => f.FileType == SourceFileType.ViewModel);
        if (vmFile is not null)
        {
            files.Add(new GeneratedSourceFile(
                Path.Combine(projectDir, "ViewModels", vmFile.FileName),
                vmFile.Content,
                SourceFileType.ViewModel));
        }

        return files.ToImmutableList();
    }

    /// <summary>
    /// 將完整專案檔案寫出至本機資料夾，並自動建立分層子資料夾階層。
    /// </summary>
    public async Task ExportToFolderAsync(FormDocument document, string destinationDirectory, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(document);
        ArgumentException.ThrowIfNullOrWhiteSpace(destinationDirectory);

        if (!Directory.Exists(destinationDirectory))
        {
            Directory.CreateDirectory(destinationDirectory);
        }

        var files = GenerateFullProject(document);
        foreach (var file in files)
        {
            var filePath = Path.Combine(destinationDirectory, file.FileName);
            var fileDir = Path.GetDirectoryName(filePath);
            if (!string.IsNullOrEmpty(fileDir) && !Directory.Exists(fileDir))
            {
                Directory.CreateDirectory(fileDir);
            }

            await File.WriteAllTextAsync(filePath, file.Content, Encoding.UTF8, cancellationToken);
        }
    }
}
