// filepath: src/AFG.Generators/ProjectExport/ProjectExportService.cs
using AFG.Generators.CSharpMarkup;

namespace AFG.Generators.ProjectExport;

/// <summary>
/// 產出符合 Visual Studio 2022/2026 方案慣例（含 .slnx 與 src/{ProjectName}/ 子資料夾）之獨立可編譯 Avalonia .NET 10 MVVM 專案的匯出服務。
/// </summary>
public sealed class ProjectExportService(FormCodeGenerator? codeGenerator = null)
{
    private readonly FormCodeGenerator _codeGenerator = codeGenerator ?? new FormCodeGenerator();

    /// <summary>
    /// 生成包含 Visual Studio 現代化方案檔 (.slnx)、子資料夾專案檔 (.csproj)、進入點、擴充方法與 View/ViewModel 的檔案集合。
    /// </summary>
    public IReadOnlyList<GeneratedSourceFile> GenerateFullProject(FormDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        var result = _codeGenerator.GenerateAll(document);
        var files = new List<GeneratedSourceFile>();

        var projectName = string.IsNullOrWhiteSpace(document.ViewClassName)
            ? "GeneratedApp"
            : document.ViewClassName.Replace("View", "", StringComparison.Ordinal) + "App";

        var projectDir = Path.Combine("src", projectName);

        // 1. 方案根目錄：Visual Studio 現代化方案檔 (.slnx)
        var slnxContent = $"""
        <Solution>
          <Project Path="src/{projectName}/{projectName}.csproj" />
        </Solution>
        """;
        files.Add(new GeneratedSourceFile($"{projectName}.slnx", slnxContent, SourceFileType.SolutionFile));

        // 2. 方案根目錄：.gitignore 與 .editorconfig
        var gitignoreContent = """
        ## Visual Studio
        .vs/
        [Bb]in/
        [Oo]bj/
        *.user
        *.suo
        *.userosscache
        *.sln.docstates
        """;
        files.Add(new GeneratedSourceFile(".gitignore", gitignoreContent, SourceFileType.ProjectFile));

        var editorconfigContent = """
        root = true

        [*]
        indent_style = space
        indent_size = 4
        end_of_line = crlf
        charset = utf-8
        trim_trailing_whitespace = true
        insert_final_newline = true

        [*.cs]
        csharp_prefer_braces = true:suggestion
        csharp_style_namespace_declarations = file_scoped:suggestion
        """;
        files.Add(new GeneratedSourceFile(".editorconfig", editorconfigContent, SourceFileType.ProjectFile));

        // 3. 子資料夾專案檔：src/{projectName}/{projectName}.csproj
        var csprojContent = $"""
        <Project Sdk="Microsoft.NET.Sdk">
          <PropertyGroup>
            <OutputType>WinExe</OutputType>
            <TargetFramework>net10.0</TargetFramework>
            <Nullable>enable</Nullable>
            <ImplicitUsings>enable</ImplicitUsings>
            <LangVersion>latest</LangVersion>
            <RootNamespace>{document.RootNamespace}</RootNamespace>
          </PropertyGroup>

          <ItemGroup>
            <PackageReference Include="Avalonia" Version="11.2.5" />
            <PackageReference Include="Avalonia.Desktop" Version="11.2.5" />
            <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.5" />
            <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.5" />
            <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
          </ItemGroup>
        </Project>
        """;
        files.Add(new GeneratedSourceFile(Path.Combine(projectDir, $"{projectName}.csproj"), csprojContent, SourceFileType.ProjectFile));

        // 4. 子資料夾：Program.cs
        var programContent = $$"""
        // <auto-generated />
        using System;
        using Avalonia;

        namespace {{document.RootNamespace}};

        internal static class Program
        {
            [STAThread]
            public static void Main(string[] args) =>
                BuildAvaloniaApp().StartWithClassicDesktopLifetime(args);

            public static AppBuilder BuildAvaloniaApp() =>
                AppBuilder.Configure<App>()
                    .UsePlatformDetect()
                    .WithInterFont()
                    .LogToTrace();
        }
        """;
        files.Add(new GeneratedSourceFile(Path.Combine(projectDir, "Program.cs"), programContent, SourceFileType.ProjectFile));

        // 5. 子資料夾：App.axaml 與 App.axaml.cs
        var appAxaml = $$"""
        <Application xmlns="https://github.com/avaloniaui"
                     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                     x:Class="{{document.RootNamespace}}.App"
                     RequestedThemeVariant="Dark">
            <Application.Styles>
                <FluentTheme />
            </Application.Styles>
        </Application>
        """;
        var appCs = $$"""
        // <auto-generated />
        using Avalonia;
        using Avalonia.Controls.ApplicationLifetimes;
        using Avalonia.Markup.Xaml;

        namespace {{document.RootNamespace}};

        public partial class App : Application
        {
            public override void Initialize() => AvaloniaXamlLoader.Load(this);

            public override void OnFrameworkInitializationCompleted()
            {
                if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
                {
                    var view = new {{document.ViewClassName}}();
                    view.DataContext = new {{document.ViewModelClassName}}();

                    desktop.MainWindow = new Avalonia.Controls.Window
                    {
                        Title = "{{document.Title}}",
                        Width = {{document.CanvasWidth}},
                        Height = {{document.CanvasHeight}},
                        Content = view
                    };
                }

                base.OnFrameworkInitializationCompleted();
            }
        }
        """;
        files.Add(new GeneratedSourceFile(Path.Combine(projectDir, "App.axaml"), appAxaml, SourceFileType.ProjectFile));
        files.Add(new GeneratedSourceFile(Path.Combine(projectDir, "App.axaml.cs"), appCs, SourceFileType.ProjectFile));

        // 6. 子資料夾：C# Declarative UI 擴充方法 Markup/AvaloniaMarkupExtensions.cs
        files.Add(new GeneratedSourceFile(
            Path.Combine(projectDir, "Markup", "AvaloniaMarkupExtensions.cs"),
            AvaloniaMarkupExtensionsSource.Code,
            SourceFileType.ProjectFile));

        // 7. 子資料夾：Views 與 ViewModels
        var viewFile = result.Files.FirstOrDefault(f => f.FileType == SourceFileType.View);
        if (viewFile is not null)
        {
            files.Add(new GeneratedSourceFile(
                Path.Combine(projectDir, "Views", viewFile.FileName),
                viewFile.Content,
                SourceFileType.View));
        }

        var vmFile = result.Files.FirstOrDefault(f => f.FileType == SourceFileType.ViewModel);
        if (vmFile is not null)
        {
            files.Add(new GeneratedSourceFile(
                Path.Combine(projectDir, "ViewModels", vmFile.FileName),
                vmFile.Content,
                SourceFileType.ViewModel));
        }

        return files.ToImmutableList();
    }

    /// <summary>
    /// 將完整專案檔案寫出至本機資料夾，並自動建立子資料夾階層。
    /// </summary>
    public async Task ExportToFolderAsync(FormDocument document, string destinationDirectory, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(document);
        ArgumentException.ThrowIfNullOrWhiteSpace(destinationDirectory);

        if (!Directory.Exists(destinationDirectory))
        {
            Directory.CreateDirectory(destinationDirectory);
        }

        var files = GenerateFullProject(document);
        foreach (var file in files)
        {
            var filePath = Path.Combine(destinationDirectory, file.FileName);
            var fileDir = Path.GetDirectoryName(filePath);
            if (!string.IsNullOrEmpty(fileDir) && !Directory.Exists(fileDir))
            {
                Directory.CreateDirectory(fileDir);
            }

            await File.WriteAllTextAsync(filePath, file.Content, Encoding.UTF8, cancellationToken);
        }
    }
}
