// filepath: src/AFG.Generators/Logic/CppLogicGenerator.cs
using System.Text;
using AFG.Core.Models.Logic;

namespace AFG.Generators.Logic;

/// <summary>
/// 將邏輯服務與函數定義轉譯為標準 Native C++ 標頭檔 (.h)、實作檔 (.cpp)、CMakeLists.txt，
/// 以及對應主專案程式語言 (C#, F#, VB) 之 P/Invoke Interop Bridge 封裝類別。
/// </summary>
public static class CppLogicGenerator
{
    public static (GeneratedSourceFile HeaderFile, GeneratedSourceFile CppFile, GeneratedSourceFile CMakeFile) GenerateNative(
        LogicServiceDefinition service,
        string libraryName)
    {
        ArgumentNullException.ThrowIfNull(service);

        var className = service.ServiceName;
        var headerGuard = $"{className.ToUpperInvariant()}_H";

        // 1. 生成 C++ 標頭檔 (.h)
        var hSb = new StringBuilder();
        hSb.AppendLine("// <auto-generated />");
        hSb.AppendLine($"#ifndef {headerGuard}");
        hSb.AppendLine($"#define {headerGuard}");
        hSb.AppendLine();
        hSb.AppendLine("#include <cstdint>");
        hSb.AppendLine("#include <string>");
        hSb.AppendLine("#include <vector>");
        hSb.AppendLine();
        hSb.AppendLine("#if defined(_WIN32) || defined(_WIN64)");
        hSb.AppendLine("    #define AFG_API __declspec(dllexport)");
        hSb.AppendLine("#else");
        hSb.AppendLine("    #define AFG_API __attribute__((visibility(\"default\")))");
        hSb.AppendLine("#endif");
        hSb.AppendLine();
        hSb.AppendLine("extern \"C\" {");
        hSb.AppendLine();

        foreach (var func in service.Functions)
        {
            var retType = ConvertToCppType(func.ReturnType);
            var paramList = BuildCppParamList(func.Parameters);
            var exportName = $"{className}_{func.Name}";

            if (!string.IsNullOrWhiteSpace(func.Description))
            {
                hSb.AppendLine($"// {func.Description}");
            }
            hSb.AppendLine($"AFG_API {retType} {exportName}({paramList});");
            hSb.AppendLine();
        }

        hSb.AppendLine("}");
        hSb.AppendLine();
        hSb.AppendLine($"#endif // {headerGuard}");

        var headerFile = new GeneratedSourceFile(
            $"{className}.h",
            hSb.ToString().TrimEnd() + Environment.NewLine,
            SourceFileType.Service);

        // 2. 生成 C++ 實作檔 (.cpp)
        var cppSb = new StringBuilder();
        cppSb.AppendLine("// <auto-generated />");
        cppSb.AppendLine($"#include \"{className}.h\"");
        cppSb.AppendLine("#include <iostream>");
        cppSb.AppendLine("#include <cstring>");
        cppSb.AppendLine();
        cppSb.AppendLine("extern \"C\" {");
        cppSb.AppendLine();

        foreach (var func in service.Functions)
        {
            var retType = ConvertToCppType(func.ReturnType);
            var paramList = BuildCppParamList(func.Parameters);
            var exportName = $"{className}_{func.Name}";

            cppSb.AppendLine($"AFG_API {retType} {exportName}({paramList}) {{");
            if (!string.IsNullOrWhiteSpace(func.CustomImplementation))
            {
                var lines = func.CustomImplementation.Split(["\r\n", "\r", "\n"], StringSplitOptions.None);
                foreach (var line in lines)
                {
                    cppSb.AppendLine($"    {line}");
                }
            }
            else
            {
                if (retType == "void")
                {
                    cppSb.AppendLine("    // TODO: Implement native C++ logic");
                }
                else
                {
                    var defVal = GetCppDefaultValue(func.ReturnType);
                    cppSb.AppendLine("    // TODO: Implement native C++ logic");
                    cppSb.AppendLine($"    return {defVal};");
                }
            }
            cppSb.AppendLine("}");
            cppSb.AppendLine();
        }

        cppSb.AppendLine("}");

        var cppFile = new GeneratedSourceFile(
            $"{className}.cpp",
            cppSb.ToString().TrimEnd() + Environment.NewLine,
            SourceFileType.Service);

        // 3. 生成 CMakeLists.txt
        var cmakeSb = new StringBuilder();
        cmakeSb.AppendLine("cmake_minimum_required(VERSION 3.16)");
        cmakeSb.AppendLine($"project({libraryName} LANGUAGES C CXX)");
        cmakeSb.AppendLine();
        cmakeSb.AppendLine("set(CMAKE_CXX_STANDARD 17)");
        cmakeSb.AppendLine("set(CMAKE_CXX_STANDARD_REQUIRED ON)");
        cmakeSb.AppendLine();
        cmakeSb.AppendLine($"add_library({libraryName} SHARED {className}.cpp)");
        cmakeSb.AppendLine();
        cmakeSb.AppendLine($"set_target_properties({libraryName} PROPERTIES");
        cmakeSb.AppendLine($"    OUTPUT_NAME \"{libraryName}\"");
        cmakeSb.AppendLine("    PREFIX \"\"");
        cmakeSb.AppendLine(")");

        var cmakeFile = new GeneratedSourceFile(
            "CMakeLists.txt",
            cmakeSb.ToString().TrimEnd() + Environment.NewLine,
            SourceFileType.ProjectFile);

        return (headerFile, cppFile, cmakeFile);
    }

    /// <summary>
    /// 生成 C# 呼叫 C++ 原生 DLL 之 P/Invoke Bridge 類別（實作 I{ServiceName}）。
    /// </summary>
    public static GeneratedSourceFile GenerateCSharpBridge(LogicServiceDefinition service, string libraryName)
    {
        var interfaceName = service.InterfaceName;
        var className = $"{service.ServiceName}NativeBridge";
        var nativeClass = service.ServiceName;
        var ns = !string.IsNullOrWhiteSpace(service.Namespace) ? service.Namespace : "App.Services";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"public class {className} : {interfaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    private const string LibName = \"{libraryName}\";");
        sb.AppendLine();

        // 原生 DllImport 宣告
        foreach (var func in service.Functions)
        {
            var exportName = $"{nativeClass}_{func.Name}";
            var retType = GetCSharpPrimitiveType(func.ReturnType);
            var pinvokeParams = BuildCSharpPinvokeParams(func.Parameters);

            sb.AppendLine($"    [DllImport(LibName, EntryPoint = \"{exportName}\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine($"    private static extern {retType} Native_{func.Name}({pinvokeParams});");
            sb.AppendLine();
        }

        // 介面實作
        foreach (var func in service.Functions)
        {
            var retType = GetCSharpReturnType(func.ReturnType, func.IsAsync);
            var paramList = BuildCSharpParamList(func.Parameters, func.IsAsync);
            var callArgs = string.Join(", ", func.Parameters.Select(p => p.Name));
            var methodName = func.Name;
            if (func.IsAsync && !methodName.EndsWith("Async", StringComparison.OrdinalIgnoreCase))
            {
                methodName += "Async";
            }

            if (func.IsAsync)
            {
                if (func.ReturnType.Equals("void", StringComparison.OrdinalIgnoreCase))
                {
                    sb.AppendLine($"    public Task {methodName}({paramList})");
                    sb.AppendLine("    {");
                    sb.AppendLine($"        return Task.Run(() => Native_{func.Name}({callArgs}));");
                    sb.AppendLine("    }");
                }
                else
                {
                    sb.AppendLine($"    public Task<{func.ReturnType}> {methodName}({paramList})");
                    sb.AppendLine("    {");
                    sb.AppendLine($"        return Task.Run(() => Native_{func.Name}({callArgs}));");
                    sb.AppendLine("    }");
                }
            }
            else
            {
                if (func.ReturnType.Equals("void", StringComparison.OrdinalIgnoreCase))
                {
                    sb.AppendLine($"    public void {methodName}({paramList})");
                    sb.AppendLine("    {");
                    sb.AppendLine($"        Native_{func.Name}({callArgs});");
                    sb.AppendLine("    }");
                }
                else
                {
                    sb.AppendLine($"    public {func.ReturnType} {methodName}({paramList})");
                    sb.AppendLine("    {");
                    sb.AppendLine($"        return Native_{func.Name}({callArgs});");
                    sb.AppendLine("    }");
                }
            }
            sb.AppendLine();
        }

        sb.AppendLine("}");

        return new GeneratedSourceFile(
            $"{className}.cs",
            sb.ToString().TrimEnd() + Environment.NewLine,
            SourceFileType.Service);
    }

    /// <summary>
    /// 生成 F# 呼叫 C++ 原生 DLL 之 P/Invoke Bridge 類別（實作 I{ServiceName}）。
    /// </summary>
    public static GeneratedSourceFile GenerateFSharpBridge(LogicServiceDefinition service, string libraryName)
    {
        var interfaceName = service.InterfaceName;
        var className = $"{service.ServiceName}NativeBridge";
        var nativeClass = service.ServiceName;
        var ns = !string.IsNullOrWhiteSpace(service.Namespace) ? service.Namespace : "App.Services";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nowarn \"3261\" \"3262\" \"3263\" \"1183\" \"0020\" \"0044\" \"0009\"");
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine();
        sb.AppendLine("open System");
        sb.AppendLine("open System.Runtime.InteropServices");
        sb.AppendLine("open System.Threading");
        sb.AppendLine("open System.Threading.Tasks");
        sb.AppendLine();
        sb.AppendLine($"module private {className}Native =");
        sb.AppendLine($"    [<Literal>]");
        sb.AppendLine($"    let LibName = \"{libraryName}\"");
        sb.AppendLine();

        foreach (var func in service.Functions)
        {
            var exportName = $"{nativeClass}_{func.Name}";
            var retType = GetCSharpPrimitiveType(func.ReturnType);
            var pinvokeParams = BuildCSharpPinvokeParams(func.Parameters);
            sb.AppendLine($"    [<DllImport(LibName, EntryPoint = \"{exportName}\", CallingConvention = CallingConvention.Cdecl)>]");
            sb.AppendLine($"    extern {retType} Native_{func.Name}({pinvokeParams})");
            sb.AppendLine();
        }

        sb.AppendLine($"type {className}() =");
        sb.AppendLine($"    interface {interfaceName} with");

        foreach (var func in service.Functions)
        {
            var paramArgs = string.Join(", ", func.Parameters.Select(p => $"{p.Name}"));
            if (func.IsAsync)
            {
                paramArgs = string.IsNullOrWhiteSpace(paramArgs) ? "?cancellationToken" : $"{paramArgs}, ?cancellationToken";
            }
            var callArgs = string.Join(", ", func.Parameters.Select(p => p.Name));
            var methodName = func.Name;
            if (func.IsAsync && !methodName.EndsWith("Async", StringComparison.OrdinalIgnoreCase))
            {
                methodName += "Async";
            }

            if (func.IsAsync)
            {
                if (func.ReturnType.Equals("void", StringComparison.OrdinalIgnoreCase))
                {
                    sb.AppendLine($"        member this.{methodName}({paramArgs}) =");
                    sb.AppendLine($"            Task.Run(fun () -> {className}Native.Native_{func.Name}({callArgs})) :> Task");
                }
                else
                {
                    sb.AppendLine($"        member this.{methodName}({paramArgs}) =");
                    sb.AppendLine($"            Task.Run(fun () -> {className}Native.Native_{func.Name}({callArgs}))");
                }
            }
            else
            {
                if (func.ReturnType.Equals("void", StringComparison.OrdinalIgnoreCase))
                {
                    sb.AppendLine($"        member this.{methodName}({paramArgs}) =");
                    sb.AppendLine($"            {className}Native.Native_{func.Name}({callArgs}) |> ignore");
                }
                else
                {
                    sb.AppendLine($"        member this.{methodName}({paramArgs}) =");
                    sb.AppendLine($"            {className}Native.Native_{func.Name}({callArgs})");
                }
            }
            sb.AppendLine();
        }

        return new GeneratedSourceFile(
            $"{className}.fs",
            sb.ToString().TrimEnd() + Environment.NewLine,
            SourceFileType.Service);
    }

    /// <summary>
    /// 生成 Visual Basic 呼叫 C++ 原生 DLL 之 P/Invoke Bridge 類別（實作 I{ServiceName}）。
    /// </summary>
    public static GeneratedSourceFile GenerateVisualBasicBridge(LogicServiceDefinition service, string libraryName)
    {
        var interfaceName = service.InterfaceName;
        var className = $"{service.ServiceName}NativeBridge";
        var nativeClass = service.ServiceName;
        var ns = !string.IsNullOrWhiteSpace(service.Namespace) ? service.Namespace : "App.Services";

        var sb = new StringBuilder();
        sb.AppendLine("' <auto-generated />");
        sb.AppendLine("Option Explicit On");
        sb.AppendLine("Option Strict On");
        sb.AppendLine();
        sb.AppendLine("Imports System");
        sb.AppendLine("Imports System.Runtime.InteropServices");
        sb.AppendLine("Imports System.Threading");
        sb.AppendLine("Imports System.Threading.Tasks");
        sb.AppendLine();
        sb.AppendLine($"Namespace {ns}");
        sb.AppendLine($"    Public Class {className}");
        sb.AppendLine($"        Implements {interfaceName}");
        sb.AppendLine();
        sb.AppendLine($"        Private Const LibName As String = \"{libraryName}\"");
        sb.AppendLine();

        foreach (var func in service.Functions)
        {
            var exportName = $"{nativeClass}_{func.Name}";
            var isVoid = func.ReturnType.Equals("void", StringComparison.OrdinalIgnoreCase);
            var pinvokeParams = BuildVbParamList(func.Parameters, false);

            if (isVoid)
            {
                sb.AppendLine($"        <DllImport(LibName, EntryPoint:=\"{exportName}\", CallingConvention:=CallingConvention.Cdecl)>");
                sb.AppendLine($"        Private Shared Sub Native_{func.Name}({pinvokeParams})");
                sb.AppendLine("        End Sub");
            }
            else
            {
                var vbRet = ConvertToVbType(func.ReturnType);
                sb.AppendLine($"        <DllImport(LibName, EntryPoint:=\"{exportName}\", CallingConvention:=CallingConvention.Cdecl)>");
                sb.AppendLine($"        Private Shared Function Native_{func.Name}({pinvokeParams}) As {vbRet}");
                sb.AppendLine("        End Function");
            }
            sb.AppendLine();
        }

        foreach (var func in service.Functions)
        {
            var isVoid = func.ReturnType.Equals("void", StringComparison.OrdinalIgnoreCase);
            var methodName = func.Name;
            if (func.IsAsync && !methodName.EndsWith("Async", StringComparison.OrdinalIgnoreCase))
            {
                methodName += "Async";
            }
            var paramList = BuildVbParamList(func.Parameters, func.IsAsync);
            var callArgs = string.Join(", ", func.Parameters.Select(p => p.Name));

            if (func.IsAsync)
            {
                if (isVoid)
                {
                    sb.AppendLine($"        Public Function {methodName}({paramList}) As Task Implements {interfaceName}.{methodName}");
                    sb.AppendLine($"            Return Task.Run(Sub() Native_{func.Name}({callArgs}))");
                    sb.AppendLine("        End Function");
                }
                else
                {
                    var vbRet = ConvertToVbType(func.ReturnType);
                    sb.AppendLine($"        Public Function {methodName}({paramList}) As Task(Of {vbRet}) Implements {interfaceName}.{methodName}");
                    sb.AppendLine($"            Return Task.Run(Function() Native_{func.Name}({callArgs}))");
                    sb.AppendLine("        End Function");
                }
            }
            else
            {
                if (isVoid)
                {
                    sb.AppendLine($"        Public Sub {methodName}({paramList}) Implements {interfaceName}.{methodName}");
                    sb.AppendLine($"            Native_{func.Name}({callArgs})");
                    sb.AppendLine("        End Sub");
                }
                else
                {
                    var vbRet = ConvertToVbType(func.ReturnType);
                    sb.AppendLine($"        Public Function {methodName}({paramList}) As {vbRet} Implements {interfaceName}.{methodName}");
                    sb.AppendLine($"            Return Native_{func.Name}({callArgs})");
                    sb.AppendLine("        End Function");
                }
            }
            sb.AppendLine();
        }

        sb.AppendLine("    End Class");
        sb.AppendLine("End Namespace");

        return new GeneratedSourceFile(
            $"{className}.vb",
            sb.ToString().TrimEnd() + Environment.NewLine,
            SourceFileType.Service);
    }

    private static string ConvertToCppType(string returnType)
    {
        var t = (string.IsNullOrWhiteSpace(returnType) ? "void" : returnType.Trim()).ToLowerInvariant();
        return t switch
        {
            "void" => "void",
            "int" or "int32" => "int32_t",
            "short" or "int16" => "int16_t",
            "long" or "int64" => "int64_t",
            "float" or "single" => "float",
            "double" or "decimal" => "double",
            "bool" or "boolean" => "bool",
            "string" => "const char*",
            "byte" or "uint8" => "uint8_t",
            "byte[]" => "const uint8_t*",
            _ => "void*"
        };
    }

    private static string BuildCppParamList(ImmutableList<FunctionParameter> parameters)
    {
        if (parameters.Count == 0) return "";
        var list = new List<string>();
        foreach (var p in parameters)
        {
            var cppType = ConvertToCppType(p.Type);
            list.Add($"{cppType} {p.Name}");
        }
        return string.Join(", ", list);
    }

    private static string GetCppDefaultValue(string returnType)
    {
        var t = ConvertToCppType(returnType);
        return t switch
        {
            "int32_t" or "int16_t" or "int64_t" or "uint8_t" => "0",
            "float" => "0.0f",
            "double" => "0.0",
            "bool" => "false",
            "const char*" => "\"\"",
            _ => "nullptr"
        };
    }

    private static string GetCSharpPrimitiveType(string type)
    {
        var t = (string.IsNullOrWhiteSpace(type) ? "void" : type.Trim()).ToLowerInvariant();
        return t switch
        {
            "void" => "void",
            "int" or "int32" => "int",
            "short" or "int16" => "short",
            "long" or "int64" => "long",
            "float" or "single" => "float",
            "double" or "decimal" => "double",
            "bool" or "boolean" => "bool",
            "string" => "string",
            "byte" => "byte",
            "byte[]" => "byte[]",
            _ => type.Trim()
        };
    }

    private static string GetCSharpReturnType(string returnType, bool isAsync)
    {
        var cleanType = string.IsNullOrWhiteSpace(returnType) ? "void" : returnType.Trim();
        if (!isAsync)
        {
            return cleanType;
        }

        return cleanType.Equals("void", StringComparison.OrdinalIgnoreCase)
            ? "Task"
            : $"Task<{cleanType}>";
    }

    private static string BuildCSharpPinvokeParams(ImmutableList<FunctionParameter> parameters)
    {
        var list = new List<string>();
        foreach (var p in parameters)
        {
            var pType = GetCSharpPrimitiveType(p.Type);
            list.Add($"{pType} {p.Name}");
        }
        return string.Join(", ", list);
    }

    private static string BuildCSharpParamList(ImmutableList<FunctionParameter> parameters, bool isAsync)
    {
        var list = new List<string>();
        foreach (var p in parameters)
        {
            var pType = string.IsNullOrWhiteSpace(p.Type) ? "object" : p.Type.Trim();
            var def = !string.IsNullOrWhiteSpace(p.DefaultValue) ? $" = {p.DefaultValue}" : "";
            list.Add($"{pType} {p.Name}{def}");
        }

        if (isAsync)
        {
            list.Add("CancellationToken cancellationToken = default");
        }

        return string.Join(", ", list);
    }

    private static string ConvertToVbType(string returnType)
    {
        var t = (string.IsNullOrWhiteSpace(returnType) ? "void" : returnType.Trim()).ToLowerInvariant();
        return t switch
        {
            "void" => "Void",
            "int" or "int32" => "Integer",
            "short" or "int16" => "Short",
            "long" or "int64" => "Long",
            "float" or "single" => "Single",
            "double" => "Double",
            "decimal" => "Decimal",
            "bool" or "boolean" => "Boolean",
            "string" => "String",
            "byte" => "Byte",
            "byte[]" => "Byte()",
            _ => returnType.Trim()
        };
    }

    private static string BuildVbParamList(ImmutableList<FunctionParameter> parameters, bool isAsync)
    {
        var list = new List<string>();
        foreach (var p in parameters)
        {
            var pType = ConvertToVbType(p.Type);
            var isOptional = !string.IsNullOrWhiteSpace(p.DefaultValue);
            var optPrefix = isOptional ? "Optional " : "";
            var defSuffix = isOptional ? $" = {p.DefaultValue}" : "";
            list.Add($"{optPrefix}ByVal {p.Name} As {pType}{defSuffix}");
        }

        if (isAsync)
        {
            list.Add("Optional ByVal cancellationToken As CancellationToken = Nothing");
        }

        return string.Join(", ", list);
    }
}
