// filepath: src/AFG.Generators/Logic/CSharpLogicGenerator.cs
using System.Text;
using AFG.Core.Models.Logic;

namespace AFG.Generators.Logic;

/// <summary>
/// 將邏輯服務與函數定義轉譯為標準 C# 介面與實作類別。
/// </summary>
public static class CSharpLogicGenerator
{
    public static (GeneratedSourceFile InterfaceFile, GeneratedSourceFile ImplementationFile) Generate(LogicServiceDefinition service)
    {
        ArgumentNullException.ThrowIfNull(service);

        var interfaceName = service.InterfaceName;
        var className = service.ServiceName;
        var ns = !string.IsNullOrWhiteSpace(service.Namespace) ? service.Namespace : "App.Services";

        // 1. 生成介面 (Interface)
        var ifaceSb = new StringBuilder();
        ifaceSb.AppendLine("// <auto-generated />");
        ifaceSb.AppendLine("#nullable enable");
        ifaceSb.AppendLine();
        ifaceSb.AppendLine("using System;");
        ifaceSb.AppendLine("using System.Collections.Generic;");
        ifaceSb.AppendLine("using System.Threading;");
        ifaceSb.AppendLine("using System.Threading.Tasks;");
        ifaceSb.AppendLine();
        ifaceSb.AppendLine($"namespace {ns};");
        ifaceSb.AppendLine();
        if (!string.IsNullOrWhiteSpace(service.Description))
        {
            ifaceSb.AppendLine("/// <summary>");
            ifaceSb.AppendLine($"/// {service.Description}");
            ifaceSb.AppendLine("/// </summary>");
        }
        ifaceSb.AppendLine($"public interface {interfaceName}");
        ifaceSb.AppendLine("{");

        foreach (var func in service.Functions)
        {
            if (!string.IsNullOrWhiteSpace(func.Description))
            {
                ifaceSb.AppendLine("    /// <summary>");
                ifaceSb.AppendLine($"    /// {func.Description}");
                ifaceSb.AppendLine("    /// </summary>");
            }
            foreach (var p in func.Parameters)
            {
                if (!string.IsNullOrWhiteSpace(p.Description))
                {
                    ifaceSb.AppendLine($"    /// <param name=\"{p.Name}\">{p.Description}</param>");
                }
            }

            var retType = GetCSharpReturnType(func.ReturnType, func.IsAsync);
            var paramList = BuildCSharpParamList(func.Parameters, func.IsAsync);
            var methodName = func.Name;
            if (func.IsAsync && !methodName.EndsWith("Async", StringComparison.OrdinalIgnoreCase))
            {
                methodName += "Async";
            }

            ifaceSb.AppendLine($"    {retType} {methodName}({paramList});");
            ifaceSb.AppendLine();
        }

        ifaceSb.AppendLine("}");

        var interfaceFile = new GeneratedSourceFile(
            $"{interfaceName}.cs",
            ifaceSb.ToString().TrimEnd() + Environment.NewLine,
            SourceFileType.Service);

        // 2. 生成實作類別 (Implementation Class)
        var implSb = new StringBuilder();
        implSb.AppendLine("// <auto-generated />");
        implSb.AppendLine("#nullable enable");
        implSb.AppendLine();
        implSb.AppendLine("using System;");
        implSb.AppendLine("using System.Collections.Generic;");
        implSb.AppendLine("using System.Threading;");
        implSb.AppendLine("using System.Threading.Tasks;");
        implSb.AppendLine();
        implSb.AppendLine($"namespace {ns};");
        implSb.AppendLine();
        if (!string.IsNullOrWhiteSpace(service.Description))
        {
            implSb.AppendLine("/// <summary>");
            implSb.AppendLine($"/// {service.Description} 實作類別。");
            implSb.AppendLine("/// </summary>");
        }
        implSb.AppendLine($"public class {className} : {interfaceName}");
        implSb.AppendLine("{");

        foreach (var func in service.Functions)
        {
            var retType = GetCSharpReturnType(func.ReturnType, func.IsAsync);
            var paramList = BuildCSharpParamList(func.Parameters, func.IsAsync);
            var methodName = func.Name;
            if (func.IsAsync && !methodName.EndsWith("Async", StringComparison.OrdinalIgnoreCase))
            {
                methodName += "Async";
            }

            var asyncKeyword = func.IsAsync ? "async " : "";
            implSb.AppendLine($"    public {asyncKeyword}{retType} {methodName}({paramList})");
            implSb.AppendLine("    {");

            if (!string.IsNullOrWhiteSpace(func.CustomImplementation))
            {
                var lines = func.CustomImplementation.Split(["\r\n", "\r", "\n"], StringSplitOptions.None);
                foreach (var line in lines)
                {
                    implSb.AppendLine($"        {line}");
                }
            }
            else
            {
                if (func.IsAsync)
                {
                    implSb.AppendLine("        await Task.Yield();");
                    if (func.ReturnType.Equals("void", StringComparison.OrdinalIgnoreCase))
                    {
                        implSb.AppendLine("        // TODO: 請實作業務邏輯");
                    }
                    else
                    {
                        var defVal = GetCSharpDefaultValue(func.ReturnType);
                        implSb.AppendLine($"        // TODO: 請實作業務邏輯");
                        implSb.AppendLine($"        return {defVal};");
                    }
                }
                else
                {
                    if (func.ReturnType.Equals("void", StringComparison.OrdinalIgnoreCase))
                    {
                        implSb.AppendLine("        // TODO: 請實作業務邏輯");
                    }
                    else
                    {
                        var defVal = GetCSharpDefaultValue(func.ReturnType);
                        implSb.AppendLine($"        // TODO: 請實作業務邏輯");
                        implSb.AppendLine($"        return {defVal};");
                    }
                }
            }

            implSb.AppendLine("    }");
            implSb.AppendLine();
        }

        implSb.AppendLine("}");

        var implementationFile = new GeneratedSourceFile(
            $"{className}.cs",
            implSb.ToString().TrimEnd() + Environment.NewLine,
            SourceFileType.Service);

        return (interfaceFile, implementationFile);
    }

    private static string GetCSharpReturnType(string returnType, bool isAsync)
    {
        var cleanType = string.IsNullOrWhiteSpace(returnType) ? "void" : returnType.Trim();
        if (!isAsync)
        {
            return cleanType;
        }

        return cleanType.Equals("void", StringComparison.OrdinalIgnoreCase)
            ? "Task"
            : $"Task<{cleanType}>";
    }

    private static string BuildCSharpParamList(ImmutableList<FunctionParameter> parameters, bool isAsync)
    {
        var list = new List<string>();
        foreach (var p in parameters)
        {
            var pType = string.IsNullOrWhiteSpace(p.Type) ? "object" : p.Type.Trim();
            var def = !string.IsNullOrWhiteSpace(p.DefaultValue) ? $" = {p.DefaultValue}" : "";
            list.Add($"{pType} {p.Name}{def}");
        }

        if (isAsync)
        {
            list.Add("CancellationToken cancellationToken = default");
        }

        return string.Join(", ", list);
    }

    private static string GetCSharpDefaultValue(string returnType)
    {
        var t = returnType.Trim().ToLowerInvariant();
        return t switch
        {
            "int" or "int32" or "short" or "int16" or "byte" or "sbyte" or "long" or "int64" => "0",
            "float" or "single" => "0.0f",
            "double" => "0.0",
            "decimal" => "0m",
            "bool" or "boolean" => "false",
            "string" => "string.Empty",
            "datetime" => "DateTime.Now",
            "guid" => "Guid.Empty",
            _ => "default!"
        };
    }
}
