// filepath: src/AFG.Generators/Logic/FSharpLogicGenerator.cs
using System.Text;
using AFG.Core.Models.Logic;

namespace AFG.Generators.Logic;

/// <summary>
/// 將邏輯服務與函數定義轉譯為標準 F# 介面與實作模組/型別。
/// </summary>
public static class FSharpLogicGenerator
{
    public static GeneratedSourceFile Generate(LogicServiceDefinition service)
    {
        ArgumentNullException.ThrowIfNull(service);

        var interfaceName = service.InterfaceName;
        var className = service.ServiceName;
        var ns = !string.IsNullOrWhiteSpace(service.Namespace) ? service.Namespace : "App.Services";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nowarn \"3261\" \"3262\" \"3263\" \"1183\" \"0020\"");
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine();
        sb.AppendLine("open System");
        sb.AppendLine("open System.Collections.Generic");
        sb.AppendLine("open System.Threading");
        sb.AppendLine("open System.Threading.Tasks");
        sb.AppendLine();

        // 1. 介面定義 (Interface)
        sb.AppendLine($"type {interfaceName} =");
        if (service.Functions.Count == 0)
        {
            sb.AppendLine("    interface end");
        }
        else
        {
            foreach (var func in service.Functions)
            {
                var retType = GetFSharpReturnType(func.ReturnType, func.IsAsync);
                var paramList = BuildFSharpInterfaceParamList(func.Parameters, func.IsAsync);
                var methodName = func.Name;
                if (func.IsAsync && !methodName.EndsWith("Async", StringComparison.OrdinalIgnoreCase))
                {
                    methodName += "Async";
                }

                sb.AppendLine($"    abstract member {methodName} : {paramList} -> {retType}");
            }
        }
        sb.AppendLine();

        // 2. 實作類別 (Class Implementation)
        sb.AppendLine($"type {className}() =");
        sb.AppendLine($"    interface {interfaceName} with");

        if (service.Functions.Count == 0)
        {
            // Empty interface implementation
        }
        else
        {
            foreach (var func in service.Functions)
            {
                var retType = GetFSharpReturnType(func.ReturnType, func.IsAsync);
                var paramArgs = BuildFSharpMethodParamArgs(func.Parameters, func.IsAsync);
                var methodName = func.Name;
                if (func.IsAsync && !methodName.EndsWith("Async", StringComparison.OrdinalIgnoreCase))
                {
                    methodName += "Async";
                }

                sb.AppendLine($"        member this.{methodName}({paramArgs}) =");

                if (!string.IsNullOrWhiteSpace(func.CustomImplementation))
                {
                    var lines = func.CustomImplementation.Split(["\r\n", "\r", "\n"], StringSplitOptions.None);
                    foreach (var line in lines)
                    {
                        sb.AppendLine($"            {line}");
                    }
                }
                else
                {
                    if (func.IsAsync)
                    {
                        sb.AppendLine("            task {");
                        sb.AppendLine("                do! Task.Yield()");
                        if (func.ReturnType.Equals("void", StringComparison.OrdinalIgnoreCase))
                        {
                            sb.AppendLine("                ()");
                        }
                        else
                        {
                            var defVal = GetFSharpDefaultValue(func.ReturnType);
                            sb.AppendLine($"                return {defVal}");
                        }
                        sb.AppendLine("            }");
                    }
                    else
                    {
                        if (func.ReturnType.Equals("void", StringComparison.OrdinalIgnoreCase))
                        {
                            sb.AppendLine("            ()");
                        }
                        else
                        {
                            var defVal = GetFSharpDefaultValue(func.ReturnType);
                            sb.AppendLine($"            {defVal}");
                        }
                    }
                }
                sb.AppendLine();
            }
        }

        return new GeneratedSourceFile(
            $"{className}.fs",
            sb.ToString().TrimEnd() + Environment.NewLine,
            SourceFileType.Service);
    }

    private static string GetFSharpReturnType(string returnType, bool isAsync)
    {
        var cleanType = ConvertToFSharpType(returnType);
        if (!isAsync)
        {
            return cleanType;
        }

        return cleanType.Equals("unit", StringComparison.OrdinalIgnoreCase)
            ? "Task"
            : $"Task<{cleanType}>";
    }

    private static string ConvertToFSharpType(string returnType)
    {
        var t = (string.IsNullOrWhiteSpace(returnType) ? "void" : returnType.Trim()).ToLowerInvariant();
        return t switch
        {
            "void" or "unit" => "unit",
            "int" or "int32" => "int",
            "short" or "int16" => "int16",
            "long" or "int64" => "int64",
            "float" or "single" => "float32",
            "double" => "float",
            "decimal" => "decimal",
            "bool" or "boolean" => "bool",
            "string" => "string",
            "byte[]" => "byte[]",
            _ => returnType.Trim()
        };
    }

    private static string BuildFSharpInterfaceParamList(ImmutableList<FunctionParameter> parameters, bool isAsync)
    {
        var list = new List<string>();
        foreach (var p in parameters)
        {
            var pType = ConvertToFSharpType(p.Type);
            list.Add($"{p.Name}: {pType}");
        }

        if (isAsync)
        {
            list.Add("?cancellationToken: CancellationToken");
        }

        return list.Count == 0 ? "unit" : string.Join(" * ", list);
    }

    private static string BuildFSharpMethodParamArgs(ImmutableList<FunctionParameter> parameters, bool isAsync)
    {
        var list = new List<string>();
        foreach (var p in parameters)
        {
            var pType = ConvertToFSharpType(p.Type);
            list.Add($"{p.Name}: {pType}");
        }

        if (isAsync)
        {
            list.Add("?cancellationToken: CancellationToken");
        }

        return string.Join(", ", list);
    }

    private static string GetFSharpDefaultValue(string returnType)
    {
        var t = ConvertToFSharpType(returnType).ToLowerInvariant();
        return t switch
        {
            "unit" => "()",
            "int" or "int16" or "int64" or "byte" => "0",
            "float32" => "0.0f",
            "float" => "0.0",
            "decimal" => "0M",
            "bool" => "false",
            "string" => "\"\"",
            _ => "Unchecked.defaultof<_>"
        };
    }
}
