// filepath: src/AFG.Generators/Logic/VisualBasicLogicGenerator.cs
using System.Text;
using AFG.Core.Models.Logic;

namespace AFG.Generators.Logic;

/// <summary>
/// 將邏輯服務與函數定義轉譯為標準 Visual Basic (.vb) 介面與實作類別。
/// </summary>
public static class VisualBasicLogicGenerator
{
    public static (GeneratedSourceFile InterfaceFile, GeneratedSourceFile ImplementationFile) Generate(LogicServiceDefinition service)
    {
        ArgumentNullException.ThrowIfNull(service);

        var interfaceName = service.InterfaceName;
        var className = service.ServiceName;
        var ns = !string.IsNullOrWhiteSpace(service.Namespace) ? service.Namespace : "App.Services";

        // 1. 生成介面 (Interface)
        var ifaceSb = new StringBuilder();
        ifaceSb.AppendLine("' <auto-generated />");
        ifaceSb.AppendLine("Option Explicit On");
        ifaceSb.AppendLine("Option Strict On");
        ifaceSb.AppendLine();
        ifaceSb.AppendLine("Imports System");
        ifaceSb.AppendLine("Imports System.Collections.Generic");
        ifaceSb.AppendLine("Imports System.Threading");
        ifaceSb.AppendLine("Imports System.Threading.Tasks");
        ifaceSb.AppendLine();
        ifaceSb.AppendLine($"Namespace {ns}");
        if (!string.IsNullOrWhiteSpace(service.Description))
        {
            ifaceSb.AppendLine("    ''' <summary>");
            ifaceSb.AppendLine($"    ''' {service.Description}");
            ifaceSb.AppendLine("    ''' </summary>");
        }
        ifaceSb.AppendLine($"    Public Interface {interfaceName}");

        foreach (var func in service.Functions)
        {
            var isVoid = func.ReturnType.Equals("void", StringComparison.OrdinalIgnoreCase);
            var methodName = func.Name;
            if (func.IsAsync && !methodName.EndsWith("Async", StringComparison.OrdinalIgnoreCase))
            {
                methodName += "Async";
            }
            var paramList = BuildVbParamList(func.Parameters, func.IsAsync);

            if (func.IsAsync)
            {
                if (isVoid)
                {
                    ifaceSb.AppendLine($"        Function {methodName}({paramList}) As Task");
                }
                else
                {
                    var vbRet = ConvertToVbType(func.ReturnType);
                    ifaceSb.AppendLine($"        Function {methodName}({paramList}) As Task(Of {vbRet})");
                }
            }
            else
            {
                if (isVoid)
                {
                    ifaceSb.AppendLine($"        Sub {methodName}({paramList})");
                }
                else
                {
                    var vbRet = ConvertToVbType(func.ReturnType);
                    ifaceSb.AppendLine($"        Function {methodName}({paramList}) As {vbRet}");
                }
            }
        }

        ifaceSb.AppendLine("    End Interface");
        ifaceSb.AppendLine("End Namespace");

        var interfaceFile = new GeneratedSourceFile(
            $"{interfaceName}.vb",
            ifaceSb.ToString().TrimEnd() + Environment.NewLine,
            SourceFileType.Service);

        // 2. 生成實作類別 (Implementation Class)
        var implSb = new StringBuilder();
        implSb.AppendLine("' <auto-generated />");
        implSb.AppendLine("Option Explicit On");
        implSb.AppendLine("Option Strict On");
        implSb.AppendLine();
        implSb.AppendLine("Imports System");
        implSb.AppendLine("Imports System.Collections.Generic");
        implSb.AppendLine("Imports System.Threading");
        implSb.AppendLine("Imports System.Threading.Tasks");
        implSb.AppendLine();
        implSb.AppendLine($"Namespace {ns}");
        if (!string.IsNullOrWhiteSpace(service.Description))
        {
            implSb.AppendLine("    ''' <summary>");
            implSb.AppendLine($"    ''' {service.Description} 實作類別。");
            implSb.AppendLine("    ''' </summary>");
        }
        implSb.AppendLine($"    Public Class {className}");
        implSb.AppendLine($"        Implements {interfaceName}");
        implSb.AppendLine();

        foreach (var func in service.Functions)
        {
            var isVoid = func.ReturnType.Equals("void", StringComparison.OrdinalIgnoreCase);
            var methodName = func.Name;
            if (func.IsAsync && !methodName.EndsWith("Async", StringComparison.OrdinalIgnoreCase))
            {
                methodName += "Async";
            }
            var paramList = BuildVbParamList(func.Parameters, func.IsAsync);

            if (func.IsAsync)
            {
                if (isVoid)
                {
                    implSb.AppendLine($"        Public Async Function {methodName}({paramList}) As Task Implements {interfaceName}.{methodName}");
                    implSb.AppendLine("            Await Task.Yield()");
                    if (!string.IsNullOrWhiteSpace(func.CustomImplementation))
                    {
                        var lines = func.CustomImplementation.Split(["\r\n", "\r", "\n"], StringSplitOptions.None);
                        foreach (var line in lines)
                        {
                            implSb.AppendLine($"            {line}");
                        }
                    }
                    else
                    {
                        implSb.AppendLine("            ' TODO: 請實作業務邏輯");
                    }
                    implSb.AppendLine("        End Function");
                }
                else
                {
                    var vbRet = ConvertToVbType(func.ReturnType);
                    implSb.AppendLine($"        Public Async Function {methodName}({paramList}) As Task(Of {vbRet}) Implements {interfaceName}.{methodName}");
                    implSb.AppendLine("            Await Task.Yield()");
                    if (!string.IsNullOrWhiteSpace(func.CustomImplementation))
                    {
                        var lines = func.CustomImplementation.Split(["\r\n", "\r", "\n"], StringSplitOptions.None);
                        foreach (var line in lines)
                        {
                            implSb.AppendLine($"            {line}");
                        }
                    }
                    else
                    {
                        var defVal = GetVbDefaultValue(func.ReturnType);
                        implSb.AppendLine("            ' TODO: 請實作業務邏輯");
                        implSb.AppendLine($"            Return {defVal}");
                    }
                    implSb.AppendLine("        End Function");
                }
            }
            else
            {
                if (isVoid)
                {
                    implSb.AppendLine($"        Public Sub {methodName}({paramList}) Implements {interfaceName}.{methodName}");
                    if (!string.IsNullOrWhiteSpace(func.CustomImplementation))
                    {
                        var lines = func.CustomImplementation.Split(["\r\n", "\r", "\n"], StringSplitOptions.None);
                        foreach (var line in lines)
                        {
                            implSb.AppendLine($"            {line}");
                        }
                    }
                    else
                    {
                        implSb.AppendLine("            ' TODO: 請實作業務邏輯");
                    }
                    implSb.AppendLine("        End Sub");
                }
                else
                {
                    var vbRet = ConvertToVbType(func.ReturnType);
                    implSb.AppendLine($"        Public Function {methodName}({paramList}) As {vbRet} Implements {interfaceName}.{methodName}");
                    if (!string.IsNullOrWhiteSpace(func.CustomImplementation))
                    {
                        var lines = func.CustomImplementation.Split(["\r\n", "\r", "\n"], StringSplitOptions.None);
                        foreach (var line in lines)
                        {
                            implSb.AppendLine($"            {line}");
                        }
                    }
                    else
                    {
                        var defVal = GetVbDefaultValue(func.ReturnType);
                        implSb.AppendLine("            ' TODO: 請實作業務邏輯");
                        implSb.AppendLine($"            Return {defVal}");
                    }
                    implSb.AppendLine("        End Function");
                }
            }
            implSb.AppendLine();
        }

        implSb.AppendLine("    End Class");
        implSb.AppendLine("End Namespace");

        var implementationFile = new GeneratedSourceFile(
            $"{className}.vb",
            implSb.ToString().TrimEnd() + Environment.NewLine,
            SourceFileType.Service);

        return (interfaceFile, implementationFile);
    }

    private static string ConvertToVbType(string returnType)
    {
        var t = (string.IsNullOrWhiteSpace(returnType) ? "void" : returnType.Trim()).ToLowerInvariant();
        return t switch
        {
            "void" => "Void",
            "int" or "int32" => "Integer",
            "short" or "int16" => "Short",
            "long" or "int64" => "Long",
            "float" or "single" => "Single",
            "double" => "Double",
            "decimal" => "Decimal",
            "bool" or "boolean" => "Boolean",
            "string" => "String",
            "byte" => "Byte",
            "byte[]" => "Byte()",
            _ => returnType.Trim()
        };
    }

    private static string BuildVbParamList(ImmutableList<FunctionParameter> parameters, bool isAsync)
    {
        var list = new List<string>();
        foreach (var p in parameters)
        {
            var pType = ConvertToVbType(p.Type);
            var isOptional = !string.IsNullOrWhiteSpace(p.DefaultValue);
            var optPrefix = isOptional ? "Optional " : "";
            var defSuffix = isOptional ? $" = {p.DefaultValue}" : "";
            list.Add($"{optPrefix}ByVal {p.Name} As {pType}{defSuffix}");
        }

        if (isAsync)
        {
            list.Add("Optional ByVal cancellationToken As CancellationToken = Nothing");
        }

        return string.Join(", ", list);
    }

    private static string GetVbDefaultValue(string returnType)
    {
        var t = ConvertToVbType(returnType).ToLowerInvariant();
        return t switch
        {
            "integer" or "short" or "long" or "byte" => "0",
            "single" => "0.0F",
            "double" => "0.0R",
            "decimal" => "0D",
            "boolean" => "False",
            "string" => "String.Empty",
            _ => "Nothing"
        };
    }
}
