// filepath: src/AFG.Generators/VisualBasic/VisualBasicViewModelGenerator.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using AFG.Core.Enums;
using AFG.Core.Models.Ast;
using AFG.Generators.Abstractions;

namespace AFG.Generators.VisualBasic;

/// <summary>
/// 掃描 UI AST 中的資料綁定與事件命令，生成符合 Visual Basic (.NET) 與 CommunityToolkit.Mvvm 規範之 ViewModel 原始碼。
/// </summary>
public sealed class VisualBasicViewModelGenerator : ICodeGenerator
{
    public GeneratedSourceFile Generate(FormDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        var allNodes = AstTreeOperations.Flatten(document.RootNode);
        var properties = new Dictionary<string, (string VBType, string DefaultValue)>(StringComparer.Ordinal);

        foreach (var node in allNodes)
        {
            foreach (var binding in node.Bindings)
            {
                if (string.IsNullOrWhiteSpace(binding.ViewModelProperty)) continue;
                var propName = NormalizePropertyName(binding.ViewModelProperty);
                if (!properties.ContainsKey(propName))
                {
                    var (vbType, defVal) = InferVBPropertyType(binding.TargetProperty, node.Type, binding.CustomDataType);
                    properties[propName] = (vbType, defVal);
                }
            }
        }

        var commands = new Dictionary<string, (bool IsAsync, string? ParamType)>(StringComparer.Ordinal);
        var allEvents = allNodes.SelectMany(n => n.Events).Concat(document.Events);
        foreach (var evt in allEvents)
        {
            if (!string.IsNullOrWhiteSpace(evt.CommandProperty))
            {
                var cmdName = NormalizeCommandName(evt.CommandProperty);
                var param = evt.GetEffectiveParameters().FirstOrDefault();
                var paramType = param is not null && !string.IsNullOrWhiteSpace(param.Type)
                    ? MapToVBType(param.Type)
                    : null;

                if (!commands.ContainsKey(cmdName))
                {
                    commands[cmdName] = (evt.IsAsync, paramType);
                }
            }
        }

        var services = document.InjectedServices ?? [];
        var sb = new StringBuilder();

        sb.AppendLine("' <auto-generated />");
        sb.AppendLine("Option Explicit On");
        sb.AppendLine("Option Strict On");
        sb.AppendLine();
        sb.AppendLine("Imports System");
        sb.AppendLine("Imports System.Collections.ObjectModel");
        sb.AppendLine("Imports System.ComponentModel");
        sb.AppendLine("Imports System.Threading.Tasks");
        sb.AppendLine("Imports CommunityToolkit.Mvvm.ComponentModel");
        sb.AppendLine("Imports CommunityToolkit.Mvvm.Input");
        sb.AppendLine();

        sb.AppendLine($"Namespace {document.RootNamespace}");
        sb.AppendLine($"    Public Class {document.ViewModelClassName}");
        sb.AppendLine("        Inherits ObservableObject");
        sb.AppendLine();

        // 注入服務私有欄位
        if (services.Count > 0)
        {
            sb.AppendLine("        ' 注入服務相依性");
            foreach (var svc in services)
            {
                var pName = ToCamelCase(svc.InterfaceName.StartsWith('I') ? svc.InterfaceName[1..] : svc.InterfaceName);
                sb.AppendLine($"        Private ReadOnly _{pName} As {svc.InterfaceName}");
            }
            sb.AppendLine();
        }

        // 可觀察屬性後盾欄位
        if (properties.Count > 0)
        {
            sb.AppendLine("        ' 可觀察屬性後盾欄位");
            foreach (var (propName, (vbType, defVal)) in properties)
            {
                var fieldName = $"_{ToCamelCase(propName)}";
                sb.AppendLine($"        Private {fieldName} As {vbType} = {defVal}");
            }
            sb.AppendLine();
        }

        // 建構子
        if (services.Count > 0)
        {
            sb.AppendLine("        Public Sub New(" + string.Join(", ", services.Select(s => $"{ToCamelCase(s.InterfaceName.StartsWith('I') ? s.InterfaceName[1..] : s.InterfaceName)} As {s.InterfaceName}")) + ")");
            foreach (var svc in services)
            {
                var pName = ToCamelCase(svc.InterfaceName.StartsWith('I') ? svc.InterfaceName[1..] : svc.InterfaceName);
                sb.AppendLine($"            Me._{pName} = {pName}");
            }
            sb.AppendLine("        End Sub");
        }
        else
        {
            sb.AppendLine("        Public Sub New()");
            sb.AppendLine("        End Sub");
        }
        sb.AppendLine();

        // 可觀察屬性公開存取子
        if (properties.Count > 0)
        {
            sb.AppendLine("        ' 可觀察屬性公開存取子");
            foreach (var (propName, (vbType, _)) in properties)
            {
                var fieldName = $"_{ToCamelCase(propName)}";
                sb.AppendLine($"        Public Property {propName} As {vbType}");
                sb.AppendLine("            Get");
                sb.AppendLine($"                Return {fieldName}");
                sb.AppendLine("            End Get");
                sb.AppendLine($"            Set(value As {vbType})");
                sb.AppendLine($"                SetProperty({fieldName}, value)");
                sb.AppendLine("            End Set");
                sb.AppendLine("        End Property");
                sb.AppendLine();
            }
        }

        // Commands
        if (commands.Count > 0)
        {
            sb.AppendLine("        ' RelayCommand 命令公開屬性");
            foreach (var (cmdName, (isAsync, paramType)) in commands)
            {
                var actionMethodName = cmdName.EndsWith("Command", StringComparison.Ordinal)
                    ? cmdName[..^7]
                    : cmdName;

                if (isAsync)
                {
                    if (paramType is not null)
                    {
                        sb.AppendLine($"        Public ReadOnly Property {cmdName} As IAsyncRelayCommand(Of {paramType}) = New AsyncRelayCommand(Of {paramType})(AddressOf {actionMethodName}Async)");
                    }
                    else
                    {
                        sb.AppendLine($"        Public ReadOnly Property {cmdName} As IAsyncRelayCommand = New AsyncRelayCommand(AddressOf {actionMethodName}Async)");
                    }
                }
                else
                {
                    if (paramType is not null)
                    {
                        sb.AppendLine($"        Public ReadOnly Property {cmdName} As IRelayCommand(Of {paramType}) = New RelayCommand(Of {paramType})(AddressOf {actionMethodName})");
                    }
                    else
                    {
                        sb.AppendLine($"        Public ReadOnly Property {cmdName} As IRelayCommand = New RelayCommand(AddressOf {actionMethodName})");
                    }
                }
            }
            sb.AppendLine();

            sb.AppendLine("        ' 命令執行私有處理常式 (Handler Methods)");
            foreach (var (cmdName, (isAsync, paramType)) in commands)
            {
                var actionMethodName = cmdName.EndsWith("Command", StringComparison.Ordinal)
                    ? cmdName[..^7]
                    : cmdName;

                if (isAsync)
                {
                    var paramSig = paramType is not null ? $"(param As {paramType})" : "()";
                    sb.AppendLine($"        Private Async Function {actionMethodName}Async{paramSig} As Task");
                    sb.AppendLine("            Await Task.Yield()");
                    sb.AppendLine("        End Function");
                    sb.AppendLine();
                }
                else
                {
                    var paramSig = paramType is not null ? $"(param As {paramType})" : "()";
                    sb.AppendLine($"        Private Sub {actionMethodName}{paramSig}");
                    sb.AppendLine("            ' TODO: 實作業務邏輯");
                    sb.AppendLine("        End Sub");
                    sb.AppendLine();
                }
            }
        }

        sb.AppendLine("    End Class");
        sb.AppendLine("End Namespace");

        return new GeneratedSourceFile(
            $"{document.ViewModelClassName}.vb",
            sb.ToString().TrimEnd() + Environment.NewLine,
            SourceFileType.ViewModel);
    }

    private static (string VBType, string DefaultValue) InferVBPropertyType(string targetProperty, ControlType controlType, string? customType)
    {
        if (!string.IsNullOrWhiteSpace(customType))
        {
            var mapped = MapToVBType(customType);
            return (mapped, GetDefaultValueForVBType(mapped));
        }

        return targetProperty switch
        {
            "Text" or "Content" or "Title" or "Watermark" => ("String", "\"\""),
            "IsChecked" => ("Boolean?", "False"),
            "IsEnabled" or "IsVisible" or "IsReadOnly" => ("Boolean", "True"),
            "Value" or "Minimum" or "Maximum" => ("Double", "0.0"),
            "SelectedIndex" => ("Integer", "0"),
            "SelectedItem" => ("Object", "Nothing"),
            "ItemsSource" => ("ObservableCollection(Of Object)", "New ObservableCollection(Of Object)()"),
            _ => ("Object", "Nothing")
        };
    }

    private static string MapToVBType(string csharpType) => csharpType.Trim() switch
    {
        "string" or "String" => "String",
        "int" or "Int32" => "Integer",
        "double" or "Double" => "Double",
        "float" or "Single" => "Single",
        "bool" or "Boolean" => "Boolean",
        "decimal" or "Decimal" => "Decimal",
        "object" or "Object" => "Object",
        "object?" => "Object",
        _ => csharpType.Trim()
    };

    private static string GetDefaultValueForVBType(string vbType) => vbType switch
    {
        "String" => "\"\"",
        "Integer" => "0",
        "Double" => "0.0",
        "Single" => "0.0F",
        "Boolean" => "False",
        "Decimal" => "0D",
        _ => "Nothing"
    };

    private static string NormalizePropertyName(string prop) => char.ToUpperInvariant(prop[0]) + prop[1..];
    private static string NormalizeCommandName(string cmd)
    {
        var normalized = char.ToUpperInvariant(cmd[0]) + cmd[1..];
        return normalized.EndsWith("Command", StringComparison.Ordinal) ? normalized : normalized + "Command";
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return "item";
        return char.ToLowerInvariant(name[0]) + name[1..];
    }
}
