// filepath: src/AFG.Generators/VisualBasic/VisualBasicViewGenerator.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using AFG.Core.Enums;
using AFG.Core.Models.Ast;
using AFG.Generators.Abstractions;

namespace AFG.Generators.VisualBasic;

/// <summary>
/// 將 UI AST 遞迴轉譯為標準符合 Visual Basic (.NET) 規範的 Avalonia View 原始碼。
/// </summary>
public sealed class VisualBasicViewGenerator : ICodeGenerator
{
    public GeneratedSourceFile Generate(FormDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        var allNodes = AstTreeOperations.Flatten(document.RootNode);
        var sb = new StringBuilder();

        sb.AppendLine("' <auto-generated />");
        sb.AppendLine("Option Explicit On");
        sb.AppendLine("Option Strict On");
        sb.AppendLine();
        sb.AppendLine("Imports System");
        sb.AppendLine("Imports System.Collections.ObjectModel");
        sb.AppendLine("Imports Avalonia");
        sb.AppendLine("Imports Avalonia.Controls");
        sb.AppendLine("Imports Avalonia.Controls.Primitives");
        sb.AppendLine("Imports Avalonia.Layout");
        sb.AppendLine("Imports Avalonia.Media");
        sb.AppendLine("Imports Avalonia.Interactivity");
        sb.AppendLine("Imports Avalonia.Input");
        sb.AppendLine("Imports Avalonia.Data");
        sb.AppendLine("Imports CommunityToolkit.Mvvm.ComponentModel");
        sb.AppendLine("Imports CommunityToolkit.Mvvm.Input");
        sb.AppendLine();

        sb.AppendLine($"Namespace {document.RootNamespace}");
        sb.AppendLine($"    Public Class {document.ViewClassName}");
        sb.AppendLine("        Inherits UserControl");
        sb.AppendLine();

        // 收集具名欄位 (WithEvents)
        var namedNodes = allNodes.Where(n => !string.IsNullOrWhiteSpace(n.Name)).ToList();
        if (document.GenerateCodeBehindFields && namedNodes.Count > 0)
        {
            sb.AppendLine("        ' Code-Behind 具名欄位 (WithEvents)");
            foreach (var node in namedNodes)
            {
                var typeName = GetAvaloniaControlTypeName(node.Type);
                sb.AppendLine($"        Private WithEvents _{ToCamelCase(node.Name!)} As {typeName}");
            }
            sb.AppendLine();
        }

        sb.AppendLine("        Public Sub New()");
        sb.AppendLine("            InitializeComponent()");
        sb.AppendLine("        End Sub");
        sb.AppendLine();

        sb.AppendLine("        Private Sub InitializeComponent()");
        sb.AppendLine($"            Me.Width = {document.CanvasWidth.ToString(CultureInfo.InvariantCulture)}");
        sb.AppendLine($"            Me.Height = {document.CanvasHeight.ToString(CultureInfo.InvariantCulture)}");

        if (document.MinWidth.HasValue)
            sb.AppendLine($"            Me.MinWidth = {document.MinWidth.Value.ToString(CultureInfo.InvariantCulture)}");
        if (document.MinHeight.HasValue)
            sb.AppendLine($"            Me.MinHeight = {document.MinHeight.Value.ToString(CultureInfo.InvariantCulture)}");
        if (document.MaxWidth.HasValue)
            sb.AppendLine($"            Me.MaxWidth = {document.MaxWidth.Value.ToString(CultureInfo.InvariantCulture)}");
        if (document.MaxHeight.HasValue)
            sb.AppendLine($"            Me.MaxHeight = {document.MaxHeight.Value.ToString(CultureInfo.InvariantCulture)}");

        if (!string.IsNullOrWhiteSpace(document.BackgroundColor))
        {
            sb.AppendLine($"            Me.Background = New SolidColorBrush(Color.Parse(\"{document.BackgroundColor}\"))");
        }

        sb.AppendLine();

        // 產生控制項樹
        var rootVarName = "rootControl";
        RenderNode(sb, document.RootNode, rootVarName, "            ", isRoot: true);

        sb.AppendLine($"            Me.Content = {rootVarName}");
        sb.AppendLine("        End Sub");

        // 若為 Code-Behind 模式，產生事件處理器 Stub
        if (document.ArchitectureMode == ArchitectureMode.CodeBehind)
        {
            var eventNodes = allNodes.Where(n => n.Events.Count > 0).ToList();
            if (eventNodes.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("        ' Code-Behind 事件處理器");
                foreach (var node in eventNodes)
                {
                    var nodeName = !string.IsNullOrWhiteSpace(node.Name) ? node.Name : node.Id;
                    foreach (var evt in node.Events)
                    {
                        var handlerName = !string.IsNullOrWhiteSpace(evt.CommandProperty)
                            ? evt.CommandProperty
                            : $"On{nodeName}_{evt.EventName}";

                        sb.AppendLine($"        Private Sub {handlerName}(sender As Object, e As RoutedEventArgs)");
                        sb.AppendLine("            ' TODO: 實作事件處理邏輯");
                        sb.AppendLine("        End Sub");
                    }
                }
            }
        }

        sb.AppendLine("    End Class");
        sb.AppendLine("End Namespace");

        return new GeneratedSourceFile(
            $"{document.ViewClassName}.vb",
            sb.ToString().TrimEnd() + Environment.NewLine,
            SourceFileType.View);
    }

    private static void RenderNode(StringBuilder sb, AstNode node, string varName, string indent, bool isRoot = false)
    {
        var typeName = GetAvaloniaControlTypeName(node.Type);
        if (isRoot)
        {
            sb.AppendLine($"{indent}Dim {varName} As New {typeName}()");
        }

        if (!string.IsNullOrWhiteSpace(node.Name))
        {
            sb.AppendLine($"{indent}{varName}.Name = \"{node.Name}\"");
            sb.AppendLine($"{indent}_{ToCamelCase(node.Name)} = {varName}");
        }

        if (node.Width.HasValue)
            sb.AppendLine($"{indent}{varName}.Width = {node.Width.Value.ToString(CultureInfo.InvariantCulture)}");
        if (node.Height.HasValue)
            sb.AppendLine($"{indent}{varName}.Height = {node.Height.Value.ToString(CultureInfo.InvariantCulture)}");

        if (node.CanvasLeft.HasValue)
            sb.AppendLine($"{indent}Canvas.SetLeft({varName}, {node.CanvasLeft.Value.ToString(CultureInfo.InvariantCulture)})");
        if (node.CanvasTop.HasValue)
            sb.AppendLine($"{indent}Canvas.SetTop({varName}, {node.CanvasTop.Value.ToString(CultureInfo.InvariantCulture)})");

        if (node.GridRow > 0)
            sb.AppendLine($"{indent}Grid.SetRow({varName}, {node.GridRow})");
        if (node.GridColumn > 0)
            sb.AppendLine($"{indent}Grid.SetColumn({varName}, {node.GridColumn})");
        if (node.GridRowSpan > 1)
            sb.AppendLine($"{indent}Grid.SetRowSpan({varName}, {node.GridRowSpan})");
        if (node.GridColumnSpan > 1)
            sb.AppendLine($"{indent}Grid.SetColumnSpan({varName}, {node.GridColumnSpan})");

        if (node.HorizontalAlignment != HorizontalAlignment.Stretch)
            sb.AppendLine($"{indent}{varName}.HorizontalAlignment = HorizontalAlignment.{node.HorizontalAlignment}");
        if (node.VerticalAlignment != VerticalAlignment.Stretch)
            sb.AppendLine($"{indent}{varName}.VerticalAlignment = VerticalAlignment.{node.VerticalAlignment}");

        if (node.Margin != ThicknessModel.Zero)
        {
            var m = node.Margin;
            sb.AppendLine($"{indent}{varName}.Margin = New Thickness({m.Left.ToString(CultureInfo.InvariantCulture)}, {m.Top.ToString(CultureInfo.InvariantCulture)}, {m.Right.ToString(CultureInfo.InvariantCulture)}, {m.Bottom.ToString(CultureInfo.InvariantCulture)})");
        }

        if (node.Padding != ThicknessModel.Zero)
        {
            var p = node.Padding;
            sb.AppendLine($"{indent}{varName}.Padding = New Thickness({p.Left.ToString(CultureInfo.InvariantCulture)}, {p.Top.ToString(CultureInfo.InvariantCulture)}, {p.Right.ToString(CultureInfo.InvariantCulture)}, {p.Bottom.ToString(CultureInfo.InvariantCulture)})");
        }

        if (!string.IsNullOrWhiteSpace(node.Background))
            sb.AppendLine($"{indent}{varName}.Background = New SolidColorBrush(Color.Parse(\"{node.Background}\"))");
        if (!string.IsNullOrWhiteSpace(node.Foreground))
            sb.AppendLine($"{indent}{varName}.Foreground = New SolidColorBrush(Color.Parse(\"{node.Foreground}\"))");
        if (!string.IsNullOrWhiteSpace(node.BorderBrush))
            sb.AppendLine($"{indent}{varName}.BorderBrush = New SolidColorBrush(Color.Parse(\"{node.BorderBrush}\"))");
        if (node.BorderThickness.HasValue)
        {
            var bt = node.BorderThickness.Value;
            sb.AppendLine($"{indent}{varName}.BorderThickness = New Thickness({bt.Left.ToString(CultureInfo.InvariantCulture)}, {bt.Top.ToString(CultureInfo.InvariantCulture)}, {bt.Right.ToString(CultureInfo.InvariantCulture)}, {bt.Bottom.ToString(CultureInfo.InvariantCulture)})");
        }
        if (node.CornerRadius.HasValue)
        {
            var cr = node.CornerRadius.Value;
            sb.AppendLine($"{indent}{varName}.CornerRadius = New CornerRadius({cr.TopLeft.ToString(CultureInfo.InvariantCulture)}, {cr.TopRight.ToString(CultureInfo.InvariantCulture)}, {cr.BottomRight.ToString(CultureInfo.InvariantCulture)}, {cr.BottomLeft.ToString(CultureInfo.InvariantCulture)})");
        }

        if (node.FontSize.HasValue)
            sb.AppendLine($"{indent}{varName}.FontSize = {node.FontSize.Value.ToString(CultureInfo.InvariantCulture)}");
        if (!string.IsNullOrWhiteSpace(node.FontWeight))
            sb.AppendLine($"{indent}{varName}.FontWeight = FontWeight.Parse(\"{node.FontWeight}\")");

        if (node.Opacity < 1.0)
            sb.AppendLine($"{indent}{varName}.Opacity = {node.Opacity.ToString(CultureInfo.InvariantCulture)}");
        if (!node.IsVisible)
            sb.AppendLine($"{indent}{varName}.IsVisible = False");
        if (!node.IsEnabled)
            sb.AppendLine($"{indent}{varName}.IsEnabled = False");

        // 控制項專屬屬性
        if (node.Type == ControlType.Button)
        {
            if (!string.IsNullOrWhiteSpace(node.Content))
                sb.AppendLine($"{indent}{varName}.Content = \"{EscapeString(node.Content)}\"");
        }
        else if (node.Type == ControlType.TextBlock)
        {
            if (!string.IsNullOrWhiteSpace(node.Text))
                sb.AppendLine($"{indent}{varName}.Text = \"{EscapeString(node.Text)}\"");
        }
        else if (node.Type == ControlType.TextBox)
        {
            if (!string.IsNullOrWhiteSpace(node.Text))
                sb.AppendLine($"{indent}{varName}.Text = \"{EscapeString(node.Text)}\"");
            if (!string.IsNullOrWhiteSpace(node.Watermark))
                sb.AppendLine($"{indent}{varName}.Watermark = \"{EscapeString(node.Watermark)}\"");
        }
        else if (node.Type is ControlType.CheckBox or ControlType.RadioButton)
        {
            if (!string.IsNullOrWhiteSpace(node.Content))
                sb.AppendLine($"{indent}{varName}.Content = \"{EscapeString(node.Content)}\"");
            if (node.IsChecked.HasValue)
                sb.AppendLine($"{indent}{varName}.IsChecked = {(node.IsChecked.Value ? "True" : "False")}");
        }
        else if (node.Type is ControlType.Slider or ControlType.ProgressBar)
        {
            if (node.Value.HasValue)
                sb.AppendLine($"{indent}{varName}.Value = {node.Value.Value.ToString(CultureInfo.InvariantCulture)}");
            if (node.Minimum.HasValue)
                sb.AppendLine($"{indent}{varName}.Minimum = {node.Minimum.Value.ToString(CultureInfo.InvariantCulture)}");
            if (node.Maximum.HasValue)
                sb.AppendLine($"{indent}{varName}.Maximum = {node.Maximum.Value.ToString(CultureInfo.InvariantCulture)}");
        }

        // 資料綁定
        foreach (var binding in node.Bindings)
        {
            if (string.IsNullOrWhiteSpace(binding.ViewModelProperty)) continue;
            var propName = $"{typeName}.{binding.TargetProperty}Property";
            sb.AppendLine($"{indent}{varName}.Bind({propName}, New Binding(\"{binding.ViewModelProperty}\"))");
        }

        // 事件綁定 (MVVM Command)
        foreach (var evt in node.Events)
        {
            if (!string.IsNullOrWhiteSpace(evt.CommandProperty))
            {
                if (node.Type == ControlType.Button && evt.EventName == "Click")
                {
                    sb.AppendLine($"{indent}{varName}.Bind(Button.CommandProperty, New Binding(\"{evt.CommandProperty}\"))");
                }
            }
        }

        // 子節點處理
        if (node.Children.Count > 0)
        {
            var idx = 0;
            foreach (var child in node.Children)
            {
                idx++;
                var childVarName = $"{varName}_child{idx}";
                sb.AppendLine();
                sb.AppendLine($"{indent}Dim {childVarName} As New {GetAvaloniaControlTypeName(child.Type)}()");
                RenderNode(sb, child, childVarName, indent, isRoot: false);

                if (node.Type is ControlType.Canvas or ControlType.Grid or ControlType.StackPanel or ControlType.DockPanel or ControlType.WrapPanel)
                {
                    sb.AppendLine($"{indent}{varName}.Children.Add({childVarName})");
                }
                else if (node.Type is ControlType.Border or ControlType.ScrollViewer)
                {
                    sb.AppendLine($"{indent}{varName}.Content = {childVarName}");
                }
            }
        }
    }

    private static string GetAvaloniaControlTypeName(ControlType type) => type switch
    {
        ControlType.Canvas => "Canvas",
        ControlType.Grid => "Grid",
        ControlType.StackPanel => "StackPanel",
        ControlType.DockPanel => "DockPanel",
        ControlType.WrapPanel => "WrapPanel",
        ControlType.Border => "Border",
        ControlType.ScrollViewer => "ScrollViewer",
        ControlType.Button => "Button",
        ControlType.TextBox => "TextBox",
        ControlType.TextBlock => "TextBlock",
        ControlType.CheckBox => "CheckBox",
        ControlType.RadioButton => "RadioButton",
        ControlType.ComboBox => "ComboBox",
        ControlType.ListBox => "ListBox",
        ControlType.Slider => "Slider",
        ControlType.ProgressBar => "ProgressBar",
        ControlType.DatePicker => "DatePicker",
        ControlType.TimePicker => "TimePicker",
        ControlType.Image => "Image",
        ControlType.PictureBox => "Image",
        _ => "Control"
    };

    private static string EscapeString(string str) => str.Replace("\"", "\"\"");

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return "control";
        return char.ToLowerInvariant(name[0]) + name[1..];
    }
}
