// filepath: src/AFG.Generators/Mvvm/MvvmViewModelGenerator.cs
using System.Collections.Generic;
using System.Text;
using AFG.Core.Enums;
using AFG.Core.Models.Ast;
using AFG.Generators.Abstractions;

namespace AFG.Generators.Mvvm;

/// <summary>
/// 掃描 UI AST 中的資料綁定與事件命令，生成符合 CommunityToolkit.Mvvm 規範並動態整合自訂型別、自訂 DI 服務與同步/非同步 Command 的 ViewModel 原始碼。
/// </summary>
public sealed class MvvmViewModelGenerator : ICodeGenerator
{
    public GeneratedSourceFile Generate(FormDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        var allNodes = AstTreeOperations.Flatten(document.RootNode);

        // 收集所有唯一的 ViewModel 屬性與指定/推斷型別及初始值 (統一標準化為 PascalCase)
        var properties = new Dictionary<string, (string Type, string? InitialValue)>(StringComparer.Ordinal);
        foreach (var node in allNodes)
        {
            foreach (var binding in node.Bindings)
            {
                if (string.IsNullOrWhiteSpace(binding.ViewModelProperty))
                {
                    continue;
                }

                var propName = NormalizePropertyName(binding.ViewModelProperty);
                if (!properties.ContainsKey(propName))
                {
                    var propType = !string.IsNullOrWhiteSpace(binding.CustomDataType)
                        ? binding.CustomDataType.Trim()
                        : InferPropertyType(binding.TargetProperty, node.Type);

                    var initialVal = ExtractInitialValue(node, binding.TargetProperty, propType);
                    properties[propName] = (propType, initialVal);
                }
            }
        }

        // 收集所有唯一的 Command 命令名稱、非同步標記與多參數配置清單 (統一標準化為 PascalCase + Command)
        var commands = new Dictionary<string, CommandGenInfo>(StringComparer.Ordinal);
        foreach (var node in allNodes)
        {
            foreach (var evt in node.Events)
            {
                if (!string.IsNullOrWhiteSpace(evt.CommandProperty))
                {
                    var cmdName = NormalizeCommandName(evt.CommandProperty);
                    var effectiveParams = evt.GetEffectiveParameters()
                        .DistinctBy(p => string.IsNullOrWhiteSpace(p.Name) ? "parameter" : ToCamelCase(p.Name))
                        .Select(p => new CommandParameterInfo(
                            Name: string.IsNullOrWhiteSpace(p.Name) ? "parameter" : ToCamelCase(p.Name),
                            Type: string.IsNullOrWhiteSpace(p.Type) ? "object?" : p.Type.Trim()))
                        .ToList();

                    if (!commands.TryGetValue(cmdName, out var existing))
                    {
                        commands[cmdName] = new CommandGenInfo(cmdName, evt.IsAsync, effectiveParams);
                    }
                    else if (existing.Parameters.Count == 0 && effectiveParams.Count > 0)
                    {
                        commands[cmdName] = existing with { Parameters = effectiveParams };
                    }
                }
            }
        }

        var nonVisualComponents = allNodes
            .Where(n => n.Type is ControlType.DispatcherTimer or ControlType.BackgroundWorker
                              or ControlType.BluetoothClient or ControlType.SerialPortService)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Collections.ObjectModel;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Avalonia.Input;");
        sb.AppendLine("using Avalonia.Interactivity;");
        sb.AppendLine("using Avalonia.Threading;");
        sb.AppendLine("using CommunityToolkit.Mvvm.ComponentModel;");
        sb.AppendLine("using CommunityToolkit.Mvvm.Input;");

        var services = document.InjectedServices ?? [];
        if (services.Count > 0 || nonVisualComponents.Any(c => c.Type is ControlType.BluetoothClient or ControlType.SerialPortService))
        {
            sb.AppendLine($"using {document.RootNamespace}.Services;");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {document.RootNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {document.ViewModelClassName} : ObservableObject");
        sb.AppendLine("{");

        // 不可視元件與硬體通訊宣告 (如 DispatcherTimer, BackgroundWorker, BluetoothClient, SerialPortService)
        if (nonVisualComponents.Count > 0)
        {
            foreach (var comp in nonVisualComponents)
            {
                var fieldName = ToPrivateFieldName(string.IsNullOrWhiteSpace(comp.Name) ? comp.Type.ToString() : comp.Name);
                if (comp.Type == ControlType.DispatcherTimer)
                {
                    var initClause = comp.Interval.HasValue
                        ? $" = new() {{ Interval = TimeSpan.FromMilliseconds({comp.Interval.Value}) }};"
                        : " = new();";
                    sb.AppendLine($"    private readonly DispatcherTimer {fieldName}{initClause}");
                }
                else if (comp.Type == ControlType.BackgroundWorker)
                {
                    sb.AppendLine($"    private readonly BackgroundWorker {fieldName} = new();");
                }
                else if (comp.Type == ControlType.BluetoothClient)
                {
                    sb.AppendLine($"    private readonly BluetoothClient {fieldName} = new();");
                }
                else if (comp.Type == ControlType.SerialPortService)
                {
                    sb.AppendLine($"    private readonly SerialPortService {fieldName} = new();");
                }
            }
            sb.AppendLine();
        }

        // 服務欄位宣告
        if (services.Count > 0)
        {
            foreach (var svc in services)
            {
                var fieldName = ToPrivateFieldName(svc.InterfaceName.StartsWith('I') ? svc.InterfaceName[1..] : svc.InterfaceName);
                sb.AppendLine($"    private readonly {svc.InterfaceName}? {fieldName};");
            }
            sb.AppendLine();
        }

        // 建構子 (自動註冊不可視元件之專屬事件回呼與服務注入)
        var nonVisualEvents = nonVisualComponents
            .SelectMany(c => c.Events.Select(e => (Component: c, Event: e)))
            .ToList();

        var hasNonVisualEvents = nonVisualEvents.Count > 0;
        var hasServices = services.Count > 0;

        if (hasNonVisualEvents || hasServices)
        {
            sb.AppendLine($"    public {document.ViewModelClassName}()");
            sb.AppendLine("    {");
            foreach (var (comp, evt) in nonVisualEvents)
            {
                var fieldName = ToPrivateFieldName(string.IsNullOrWhiteSpace(comp.Name) ? comp.Type.ToString() : comp.Name);
                var cmdName = NormalizeCommandName(evt.CommandProperty);
                var hasParams = commands.TryGetValue(cmdName, out var cInfo) && cInfo.Parameters.Count > 0;
                var execArg = !hasParams ? "null" : cInfo!.Parameters.Count > 1 ? "(s, e)" : "e";
                sb.AppendLine($"        {fieldName}.{evt.EventName} += (s, e) => {cmdName}.Execute({execArg});");
            }
            sb.AppendLine("    }");
            sb.AppendLine();

            if (hasServices)
            {
                var ctorParams = string.Join(", ", services.Select(s => $"{s.InterfaceName} {ToCamelCase(s.InterfaceName.StartsWith('I') ? s.InterfaceName[1..] : s.InterfaceName)}"));
                sb.AppendLine($"    public {document.ViewModelClassName}({ctorParams}) : this()");
                sb.AppendLine("    {");
                foreach (var svc in services)
                {
                    var fieldName = ToPrivateFieldName(svc.InterfaceName.StartsWith('I') ? svc.InterfaceName[1..] : svc.InterfaceName);
                    var paramName = ToCamelCase(svc.InterfaceName.StartsWith('I') ? svc.InterfaceName[1..] : svc.InterfaceName);
                    sb.AppendLine($"        {fieldName} = {paramName};");
                }
                sb.AppendLine("    }");
                sb.AppendLine();
            }
        }

        // 輸出屬性
        if (properties.Count > 0)
        {
            foreach (var (propName, propInfo) in properties)
            {
                var fieldName = ToPrivateFieldName(propName);
                var defaultValue = !string.IsNullOrEmpty(propInfo.InitialValue)
                    ? $" = {propInfo.InitialValue}"
                    : GetDefaultValueExpression(propInfo.Type);

                sb.AppendLine("    [ObservableProperty]");
                sb.AppendLine($"    private {propInfo.Type} {fieldName}{defaultValue};");
                sb.AppendLine();
            }
        }

        // 輸出 Commands (支援無參數/單參數/多參數，以及同步 void 與非同步 async Task)
        if (commands.Count > 0)
        {
            foreach (var (_, cmdInfo) in commands)
            {
                var rawName = cmdInfo.CommandName.EndsWith("Command", StringComparison.Ordinal)
                    ? cmdInfo.CommandName[..^"Command".Length]
                    : cmdInfo.CommandName;

                string paramSignature;
                if (cmdInfo.Parameters.Count == 0)
                {
                    paramSignature = string.Empty;
                }
                else if (cmdInfo.Parameters.Count == 1)
                {
                    var p = cmdInfo.Parameters[0];
                    var safeType = EnsureNullableType(p.Type);
                    var safeName = Roslyn.CSharpSyntaxSanitizer.EscapeIdentifier(p.Name);
                    paramSignature = $"{safeType} {safeName} = default";
                }
                else
                {
                    // CommunityToolkit.Mvvm [RelayCommand] 僅支援 0 或 1 個參數型別。
                    // 若配置多個參數，將其封裝為 Nullable ValueTuple 單一參數以符合 MVVM Toolkit 命令規範並確保 CanExecute(null) 不會因實值型別元組拒絕 null 而將按鈕禁用。
                    var tupleFields = string.Join(", ", cmdInfo.Parameters.Select(p => $"{EnsureNullableType(p.Type)} {Roslyn.CSharpSyntaxSanitizer.EscapeIdentifier(p.Name)}"));
                    paramSignature = $"({tupleFields})? args = null";
                }

                sb.AppendLine("    [RelayCommand]");
                if (cmdInfo.IsAsync)
                {
                    var asyncMethodName = rawName.EndsWith("Async", StringComparison.Ordinal)
                        ? rawName
                        : $"{rawName}Async";

                    sb.AppendLine($"    private async Task {asyncMethodName}({paramSignature})");
                    sb.AppendLine("    {");
                    sb.AppendLine("        // TODO: 實作非同步命令業務邏輯");
                    sb.AppendLine("        await Task.CompletedTask;");
                    sb.AppendLine("    }");
                }
                else
                {
                    var syncMethodName = rawName.EndsWith("Async", StringComparison.Ordinal)
                        ? rawName[..^"Async".Length]
                        : rawName;

                    sb.AppendLine($"    private void {syncMethodName}({paramSignature})");
                    sb.AppendLine("    {");
                    sb.AppendLine("        // TODO: 實作同步命令業務邏輯");
                    sb.AppendLine("    }");
                }
                sb.AppendLine();
            }
        }

        sb.AppendLine("}");

        return new GeneratedSourceFile(
            FileName: $"{document.ViewModelClassName}.cs",
            Content: sb.ToString(),
            FileType: SourceFileType.ViewModel);
    }

    private static string ToPrivateFieldName(string propertyName)
    {
        if (string.IsNullOrEmpty(propertyName))
        {
            return "_value";
        }

        var sanitized = Roslyn.CSharpSyntaxSanitizer.SanitizeIdentifier(propertyName);
        return $"_{char.ToLowerInvariant(sanitized[0])}{sanitized[1..]}";
    }

    private static string EnsureNullableType(string type)
    {
        if (string.IsNullOrWhiteSpace(type)) return "object?";
        type = type.Trim();
        if (type.EndsWith('?')) return type;
        return $"{type}?";
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return "service";
        var sanitized = Roslyn.CSharpSyntaxSanitizer.SanitizeIdentifier(name);
        var camel = $"{char.ToLowerInvariant(sanitized[0])}{sanitized[1..]}";
        return Roslyn.CSharpSyntaxSanitizer.EscapeIdentifier(camel);
    }

    private static string InferPropertyType(string targetProperty, ControlType controlType) => targetProperty switch
    {
        "IsChecked" or "IsEnabled" or "IsVisible" or "CanSubmit" => "bool",
        "Value" or "Minimum" or "Maximum" or "Progress" => "double",
        "SelectedIndex" or "Count" => "int",
        "ItemsSource" => "ObservableCollection<string>",
        "SelectedItem" => "string?",
        "Source" => "Avalonia.Media.IImage?",
        "Stretch" => "Avalonia.Media.Stretch",
        _ => "string"
    };

    private static string GetDefaultValueExpression(string typeName)
    {
        if (typeName == "string") return " = string.Empty";
        if (typeName.StartsWith("ObservableCollection", StringComparison.Ordinal) ||
            typeName.StartsWith("List<", StringComparison.Ordinal))
        {
            return " = []";
        }
        return string.Empty;
    }

    private static string? ExtractInitialValue(AstNode node, string targetProperty, string propType)
    {
        return targetProperty switch
        {
            "Text" => !string.IsNullOrEmpty(node.Text) ? $"\"{Roslyn.CSharpSyntaxSanitizer.EscapeStringLiteral(node.Text)}\"" : null,
            "Content" => !string.IsNullOrEmpty(node.Content) ? $"\"{Roslyn.CSharpSyntaxSanitizer.EscapeStringLiteral(node.Content)}\"" : null,
            "Source" => !string.IsNullOrEmpty(node.Source) ? $"\"{Roslyn.CSharpSyntaxSanitizer.EscapeStringLiteral(node.Source)}\"" : null,
            "IsChecked" when node.IsChecked.HasValue => node.IsChecked.Value ? "true" : "false",
            "Value" when node.Value.HasValue => node.Value.Value.ToString(System.Globalization.CultureInfo.InvariantCulture),
            _ => null
        };
    }

    public static string NormalizePropertyName(string name)
    {
        if (string.IsNullOrWhiteSpace(name)) return "Value";
        name = Roslyn.CSharpSyntaxSanitizer.SanitizeIdentifier(name.Trim());
        return char.ToUpperInvariant(name[0]) + name[1..];
    }

    public static string NormalizeCommandName(string name)
    {
        if (string.IsNullOrWhiteSpace(name)) return "ExecuteCommand";
        name = Roslyn.CSharpSyntaxSanitizer.SanitizeIdentifier(name.Trim());
        var raw = name.EndsWith("Command", StringComparison.OrdinalIgnoreCase)
            ? name[..^"Command".Length]
            : name;
        if (string.IsNullOrWhiteSpace(raw)) raw = "Execute";
        return char.ToUpperInvariant(raw[0]) + raw[1..] + "Command";
    }

    private sealed record CommandParameterInfo(
        string Name,
        string Type);

    private sealed record CommandGenInfo(
        string CommandName,
        bool IsAsync,
        List<CommandParameterInfo> Parameters);
}
