// filepath: src/AFG.Generators/Mvvm/MvvmViewModelGenerator.cs
namespace AFG.Generators.Mvvm;

/// <summary>
/// 掃描 UI AST 中的資料綁定與事件命令，生成符合 CommunityToolkit.Mvvm 規範並整合相依性注入 (DI) 與同步/非同步 Command 的 ViewModel 原始碼。
/// </summary>
public sealed class MvvmViewModelGenerator : ICodeGenerator
{
    public GeneratedSourceFile Generate(FormDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        var allNodes = AstTreeOperations.Flatten(document.RootNode);

        // 收集所有唯一的 ViewModel 屬性與推斷型別
        var properties = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var node in allNodes)
        {
            foreach (var binding in node.Bindings)
            {
                if (string.IsNullOrWhiteSpace(binding.ViewModelProperty))
                {
                    continue;
                }

                if (!properties.ContainsKey(binding.ViewModelProperty))
                {
                    var inferredType = InferPropertyType(binding.TargetProperty, node.Type);
                    properties[binding.ViewModelProperty] = inferredType;
                }
            }
        }

        // 收集所有唯一的 Command 命令名稱與非同步標記
        var commands = new Dictionary<string, bool>(StringComparer.Ordinal);
        foreach (var node in allNodes)
        {
            foreach (var evt in node.Events)
            {
                if (!string.IsNullOrWhiteSpace(evt.CommandProperty))
                {
                    if (!commands.ContainsKey(evt.CommandProperty))
                    {
                        commands[evt.CommandProperty] = evt.IsAsync;
                    }
                }
            }
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using CommunityToolkit.Mvvm.ComponentModel;");
        sb.AppendLine("using CommunityToolkit.Mvvm.Input;");
        sb.AppendLine($"using {document.RootNamespace}.Services;");
        sb.AppendLine();
        sb.AppendLine($"namespace {document.RootNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {document.ViewModelClassName} : ObservableObject");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IGreetingService? _greetingService;");
        sb.AppendLine();
        sb.AppendLine($"    public {document.ViewModelClassName}()");
        sb.AppendLine("    {");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public {document.ViewModelClassName}(IGreetingService greetingService)");
        sb.AppendLine("    {");
        sb.AppendLine("        _greetingService = greetingService;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // 輸出屬性
        if (properties.Count > 0)
        {
            foreach (var (propName, propType) in properties)
            {
                var fieldName = ToPrivateFieldName(propName);
                var defaultValue = GetDefaultValueExpression(propType);

                sb.AppendLine("    [ObservableProperty]");
                sb.AppendLine($"    private {propType} {fieldName}{defaultValue};");
                sb.AppendLine();
            }
        }

        // 輸出 Commands (支援同步 void 與非同步 async Task)
        if (commands.Count > 0)
        {
            foreach (var (cmdName, isAsync) in commands)
            {
                var rawName = cmdName.EndsWith("Command", StringComparison.Ordinal)
                    ? cmdName[..^"Command".Length]
                    : cmdName;

                sb.AppendLine("    [RelayCommand]");
                if (isAsync)
                {
                    var asyncMethodName = rawName.EndsWith("Async", StringComparison.Ordinal)
                        ? rawName
                        : $"{rawName}Async";

                    sb.AppendLine($"    private async Task {asyncMethodName}()");
                    sb.AppendLine("    {");
                    sb.AppendLine("        // TODO: 實作非同步命令業務邏輯");
                    sb.AppendLine("        await Task.CompletedTask;");
                    sb.AppendLine("    }");
                }
                else
                {
                    var syncMethodName = rawName.EndsWith("Async", StringComparison.Ordinal)
                        ? rawName[..^"Async".Length]
                        : rawName;

                    sb.AppendLine($"    private void {syncMethodName}()");
                    sb.AppendLine("    {");
                    sb.AppendLine("        // TODO: 實作同步命令業務邏輯");
                    sb.AppendLine("    }");
                }
                sb.AppendLine();
            }
        }

        sb.AppendLine("}");

        return new GeneratedSourceFile(
            FileName: $"{document.ViewModelClassName}.cs",
            Content: sb.ToString(),
            FileType: SourceFileType.ViewModel);
    }

    private static string ToPrivateFieldName(string propertyName)
    {
        if (string.IsNullOrEmpty(propertyName))
        {
            return "_value";
        }

        return $"_{char.ToLowerInvariant(propertyName[0])}{propertyName[1..]}";
    }

    private static string InferPropertyType(string targetProperty, ControlType controlType) => targetProperty switch
    {
        "IsChecked" or "IsEnabled" or "IsVisible" or "CanSubmit" => "bool",
        "Value" or "Minimum" or "Maximum" or "Progress" => "double",
        "SelectedIndex" or "Count" => "int",
        "ItemsSource" => "System.Collections.IEnumerable",
        "SelectedItem" => "object?",
        _ => "string"
    };

    private static string GetDefaultValueExpression(string typeName) => typeName switch
    {
        "string" => " = string.Empty",
        "bool" => string.Empty,
        "double" => string.Empty,
        "int" => string.Empty,
        _ => string.Empty
    };
}
