// filepath: src/AFG.Generators/FSharp/FSharpViewGenerator.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using AFG.Core.Enums;
using AFG.Core.Models.Ast;
using AFG.Generators.Abstractions;

namespace AFG.Generators.FSharp;

/// <summary>
/// 將 UI AST 遞迴轉譯為標準符合 F# 規範的 Avalonia View 原始碼。
/// </summary>
public sealed class FSharpViewGenerator : ICodeGenerator
{
    public GeneratedSourceFile Generate(FormDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        var allNodes = AstTreeOperations.Flatten(document.RootNode);
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"namespace {document.RootNamespace}");
        sb.AppendLine();
        sb.AppendLine("open System");
        sb.AppendLine("open System.Collections.ObjectModel");
        sb.AppendLine("open Avalonia");
        sb.AppendLine("open Avalonia.Controls");
        sb.AppendLine("open Avalonia.Controls.Primitives");
        sb.AppendLine("open Avalonia.Layout");
        sb.AppendLine("open Avalonia.Media");
        sb.AppendLine("open Avalonia.Interactivity");
        sb.AppendLine("open Avalonia.Input");
        sb.AppendLine("open Avalonia.Data");
        sb.AppendLine("open CommunityToolkit.Mvvm.ComponentModel");
        sb.AppendLine("open CommunityToolkit.Mvvm.Input");
        sb.AppendLine();

        sb.AppendLine($"type {document.ViewClassName}() as this =");
        sb.AppendLine("    inherit UserControl()");
        sb.AppendLine();

        // 收集 Code-Behind 模式或 Hybrid 模式下的具名欄位宣告
        var namedNodes = allNodes.Where(n => !string.IsNullOrWhiteSpace(n.Name)).ToList();
        if (document.GenerateCodeBehindFields && namedNodes.Count > 0)
        {
            sb.AppendLine("    // Code-Behind 具名欄位");
            foreach (var node in namedNodes)
            {
                var typeName = GetAvaloniaControlTypeName(node.Type);
                sb.AppendLine($"    let mutable _{ToCamelCase(node.Name!)} : {typeName} = null");
            }
            sb.AppendLine();
        }

        sb.AppendLine("    do");
        sb.AppendLine("        this.InitializeComponent()");
        sb.AppendLine();

        sb.AppendLine("    member private this.InitializeComponent() =");
        sb.AppendLine($"        this.Width <- {document.CanvasWidth.ToString(CultureInfo.InvariantCulture)}");
        sb.AppendLine($"        this.Height <- {document.CanvasHeight.ToString(CultureInfo.InvariantCulture)}");

        if (document.MinWidth.HasValue)
            sb.AppendLine($"        this.MinWidth <- {document.MinWidth.Value.ToString(CultureInfo.InvariantCulture)}");
        if (document.MinHeight.HasValue)
            sb.AppendLine($"        this.MinHeight <- {document.MinHeight.Value.ToString(CultureInfo.InvariantCulture)}");
        if (document.MaxWidth.HasValue)
            sb.AppendLine($"        this.MaxWidth <- {document.MaxWidth.Value.ToString(CultureInfo.InvariantCulture)}");
        if (document.MaxHeight.HasValue)
            sb.AppendLine($"        this.MaxHeight <- {document.MaxHeight.Value.ToString(CultureInfo.InvariantCulture)}");

        if (!string.IsNullOrWhiteSpace(document.BackgroundColor))
        {
            sb.AppendLine($"        this.Background <- Color.Parse(\"{document.BackgroundColor}\") |> SolidColorBrush");
        }

        sb.AppendLine();

        // 產生控制項樹建構
        var rootVarName = "rootControl";
        RenderNode(sb, document.RootNode, rootVarName, "        ", document.RootNamespace, isRoot: true);

        sb.AppendLine($"        this.Content <- {rootVarName}");
        sb.AppendLine();

        // 若為 Code-Behind 模式，產生事件處理器 Stub
        if (document.ArchitectureMode == ArchitectureMode.CodeBehind)
        {
            var eventNodes = allNodes.Where(n => n.Events.Count > 0).ToList();
            if (eventNodes.Count > 0)
            {
                sb.AppendLine("    // Code-Behind 事件處理器");
                foreach (var node in eventNodes)
                {
                    var nodeName = !string.IsNullOrWhiteSpace(node.Name) ? node.Name : node.Id;
                    foreach (var evt in node.Events)
                    {
                        var handlerName = !string.IsNullOrWhiteSpace(evt.CommandProperty)
                            ? evt.CommandProperty
                            : $"On{nodeName}_{evt.EventName}";

                        sb.AppendLine($"    member private this.{handlerName}(sender: obj, e: RoutedEventArgs) =");
                        sb.AppendLine("        ()");
                        sb.AppendLine();
                    }
                }
            }
        }

        return new GeneratedSourceFile(
            $"{document.ViewClassName}.fs",
            sb.ToString().TrimEnd() + Environment.NewLine,
            SourceFileType.View);
    }

    private static void RenderNode(StringBuilder sb, AstNode node, string varName, string indent, string rootNamespace, bool isRoot = false)
    {
        var typeName = GetAvaloniaControlTypeName(node.Type);
        if (isRoot)
        {
            sb.AppendLine($"{indent}let {varName} = {typeName}()");
        }

        if (!string.IsNullOrWhiteSpace(node.Name))
        {
            sb.AppendLine($"{indent}{varName}.Name <- \"{node.Name}\"");
            sb.AppendLine($"{indent}_{ToCamelCase(node.Name)} <- {varName}");
        }

        if (node.Width.HasValue)
            sb.AppendLine($"{indent}{varName}.Width <- {node.Width.Value.ToString(CultureInfo.InvariantCulture)}");
        if (node.Height.HasValue)
            sb.AppendLine($"{indent}{varName}.Height <- {node.Height.Value.ToString(CultureInfo.InvariantCulture)}");

        if (node.CanvasLeft.HasValue)
            sb.AppendLine($"{indent}Canvas.SetLeft({varName}, {node.CanvasLeft.Value.ToString(CultureInfo.InvariantCulture)})");
        if (node.CanvasTop.HasValue)
            sb.AppendLine($"{indent}Canvas.SetTop({varName}, {node.CanvasTop.Value.ToString(CultureInfo.InvariantCulture)})");

        if (node.GridRow > 0)
            sb.AppendLine($"{indent}Grid.SetRow({varName}, {node.GridRow})");
        if (node.GridColumn > 0)
            sb.AppendLine($"{indent}Grid.SetColumn({varName}, {node.GridColumn})");
        if (node.GridRowSpan > 1)
            sb.AppendLine($"{indent}Grid.SetRowSpan({varName}, {node.GridRowSpan})");
        if (node.GridColumnSpan > 1)
            sb.AppendLine($"{indent}Grid.SetColumnSpan({varName}, {node.GridColumnSpan})");

        if (node.HorizontalAlignment != HorizontalAlignment.Stretch)
            sb.AppendLine($"{indent}{varName}.HorizontalAlignment <- HorizontalAlignment.{node.HorizontalAlignment}");
        if (node.VerticalAlignment != VerticalAlignment.Stretch)
            sb.AppendLine($"{indent}{varName}.VerticalAlignment <- VerticalAlignment.{node.VerticalAlignment}");

        if (node.Margin != ThicknessModel.Zero)
        {
            var m = node.Margin;
            sb.AppendLine($"{indent}{varName}.Margin <- Thickness({m.Left.ToString(CultureInfo.InvariantCulture)}, {m.Top.ToString(CultureInfo.InvariantCulture)}, {m.Right.ToString(CultureInfo.InvariantCulture)}, {m.Bottom.ToString(CultureInfo.InvariantCulture)})");
        }

        if (node.Padding != ThicknessModel.Zero)
        {
            var p = node.Padding;
            sb.AppendLine($"{indent}{varName}.Padding <- Thickness({p.Left.ToString(CultureInfo.InvariantCulture)}, {p.Top.ToString(CultureInfo.InvariantCulture)}, {p.Right.ToString(CultureInfo.InvariantCulture)}, {p.Bottom.ToString(CultureInfo.InvariantCulture)})");
        }

        if (!string.IsNullOrWhiteSpace(node.Background))
            sb.AppendLine($"{indent}{varName}.Background <- Color.Parse(\"{node.Background}\") |> SolidColorBrush");
        if (!string.IsNullOrWhiteSpace(node.Foreground))
            sb.AppendLine($"{indent}{varName}.Foreground <- Color.Parse(\"{node.Foreground}\") |> SolidColorBrush");
        if (!string.IsNullOrWhiteSpace(node.BorderBrush))
            sb.AppendLine($"{indent}{varName}.BorderBrush <- Color.Parse(\"{node.BorderBrush}\") |> SolidColorBrush");
        if (node.BorderThickness.HasValue)
        {
            var bt = node.BorderThickness.Value;
            sb.AppendLine($"{indent}{varName}.BorderThickness <- Thickness({bt.Left.ToString(CultureInfo.InvariantCulture)}, {bt.Top.ToString(CultureInfo.InvariantCulture)}, {bt.Right.ToString(CultureInfo.InvariantCulture)}, {bt.Bottom.ToString(CultureInfo.InvariantCulture)})");
        }
        if (node.CornerRadius.HasValue)
        {
            var cr = node.CornerRadius.Value;
            sb.AppendLine($"{indent}{varName}.CornerRadius <- CornerRadius({cr.TopLeft.ToString(CultureInfo.InvariantCulture)}, {cr.TopRight.ToString(CultureInfo.InvariantCulture)}, {cr.BottomRight.ToString(CultureInfo.InvariantCulture)}, {cr.BottomLeft.ToString(CultureInfo.InvariantCulture)})");
        }

        if (node.FontSize.HasValue)
            sb.AppendLine($"{indent}{varName}.FontSize <- {node.FontSize.Value.ToString(CultureInfo.InvariantCulture)}");
        if (!string.IsNullOrWhiteSpace(node.FontWeight))
            sb.AppendLine($"{indent}{varName}.FontWeight <- FontWeight.Parse(\"{node.FontWeight}\")");

        if (node.Opacity < 1.0)
            sb.AppendLine($"{indent}{varName}.Opacity <- {node.Opacity.ToString(CultureInfo.InvariantCulture)}");
        if (!node.IsVisible)
            sb.AppendLine($"{indent}{varName}.IsVisible <- false");
        if (!node.IsEnabled)
            sb.AppendLine($"{indent}{varName}.IsEnabled <- false");

        // 控制項專屬屬性
        if (node.Type == ControlType.Button)
        {
            if (!string.IsNullOrWhiteSpace(node.Content))
                sb.AppendLine($"{indent}{varName}.Content <- \"{EscapeString(node.Content)}\"");
        }
        else if (node.Type == ControlType.TextBlock)
        {
            if (!string.IsNullOrWhiteSpace(node.Text))
                sb.AppendLine($"{indent}{varName}.Text <- \"{EscapeString(node.Text)}\"");
        }
        else if (node.Type == ControlType.TextBox)
        {
            if (!string.IsNullOrWhiteSpace(node.Text))
                sb.AppendLine($"{indent}{varName}.Text <- \"{EscapeString(node.Text)}\"");
            if (!string.IsNullOrWhiteSpace(node.Watermark))
                sb.AppendLine($"{indent}{varName}.Watermark <- \"{EscapeString(node.Watermark)}\"");
        }
        else if (node.Type is ControlType.CheckBox or ControlType.RadioButton)
        {
            if (!string.IsNullOrWhiteSpace(node.Content))
                sb.AppendLine($"{indent}{varName}.Content <- \"{EscapeString(node.Content)}\"");
            if (node.IsChecked.HasValue)
                sb.AppendLine($"{indent}{varName}.IsChecked <- Nullable({(node.IsChecked.Value ? "true" : "false")})");
        }
        else if (node.Type is ControlType.Slider or ControlType.ProgressBar)
        {
            if (node.Value.HasValue)
                sb.AppendLine($"{indent}{varName}.Value <- {node.Value.Value.ToString(CultureInfo.InvariantCulture)}");
            if (node.Minimum.HasValue)
                sb.AppendLine($"{indent}{varName}.Minimum <- {node.Minimum.Value.ToString(CultureInfo.InvariantCulture)}");
            if (node.Maximum.HasValue)
                sb.AppendLine($"{indent}{varName}.Maximum <- {node.Maximum.Value.ToString(CultureInfo.InvariantCulture)}");
        }
        else if (node.Type is ControlType.PictureBox or ControlType.Image)
        {
            if (node.InitBitmap)
            {
                var w = (node.Width ?? 200).ToString(CultureInfo.InvariantCulture);
                var h = (node.Height ?? 150).ToString(CultureInfo.InvariantCulture);
                var bg = string.IsNullOrWhiteSpace(node.BitmapBackgroundColor) ? "#F0F0F0" : node.BitmapBackgroundColor.Trim();
                sb.AppendLine($"{indent}{varName}.Source <- BitmapHelper.CreateInitializedBitmap({w}, {h}, Color.Parse(\"{bg}\"))");
            }
            else if (!string.IsNullOrWhiteSpace(node.Source))
            {
                var sourcePath = node.Source.Trim();
                if (node.UseRelativePath && !sourcePath.StartsWith("http", StringComparison.OrdinalIgnoreCase) && !sourcePath.StartsWith("avares://", StringComparison.OrdinalIgnoreCase))
                {
                    var fileName = System.IO.Path.GetFileName(sourcePath.Replace('\\', '/'));
                    var assetUri = $"avares://{rootNamespace}.Shared/Assets/{fileName}";
                    sb.AppendLine($"{indent}{varName}.Source <- BitmapHelper.LoadBitmap(\"{assetUri}\")");
                }
                else
                {
                    sb.AppendLine($"{indent}{varName}.Source <- BitmapHelper.LoadBitmap(\"{sourcePath}\")");
                }
            }
        }
        else if (node.Type == ControlType.MediaPlayer)
        {
            if (!string.IsNullOrWhiteSpace(node.Source))
            {
                var sourcePath = node.Source.Trim();
                if (node.UseRelativePath && !sourcePath.StartsWith("http", StringComparison.OrdinalIgnoreCase) && !sourcePath.StartsWith("avares://", StringComparison.OrdinalIgnoreCase))
                {
                    var fileName = System.IO.Path.GetFileName(sourcePath.Replace('\\', '/'));
                    var assetUri = $"avares://{rootNamespace}.Shared/Assets/{fileName}";
                    sb.AppendLine($"{indent}{varName}.Source <- \"{assetUri}\"");
                }
                else
                {
                    sb.AppendLine($"{indent}{varName}.Source <- \"{sourcePath}\"");
                }
            }
            if (node.AutoPlay == true)
                sb.AppendLine($"{indent}{varName}.AutoPlay <- true");
            if (node.IsLooping == true)
                sb.AppendLine($"{indent}{varName}.IsLooping <- true");
            if (node.Volume.HasValue)
                sb.AppendLine($"{indent}{varName}.Volume <- {node.Volume.Value.ToString(CultureInfo.InvariantCulture)}");
        }

        // 資料綁定
        foreach (var binding in node.Bindings)
        {
            if (string.IsNullOrWhiteSpace(binding.ViewModelProperty)) continue;
            var propName = GetAvaloniaPropertyAccessor(typeName, binding.TargetProperty);
            sb.AppendLine($"{indent}{varName}.Bind({propName}, Binding(\"{binding.ViewModelProperty}\")) |> ignore");
        }

        // 事件綁定 (MVVM Command)
        foreach (var evt in node.Events)
        {
            if (!string.IsNullOrWhiteSpace(evt.CommandProperty))
            {
                if (node.Type == ControlType.Button && evt.EventName == "Click")
                {
                    sb.AppendLine($"{indent}{varName}.Bind(Button.CommandProperty, Binding(\"{evt.CommandProperty}\")) |> ignore");
                }
            }
        }

        // 子節點處理 (Containers)
        if (node.Children.Count > 0)
        {
            var idx = 0;
            foreach (var child in node.Children)
            {
                idx++;
                var childVarName = $"{varName}_child{idx}";
                sb.AppendLine();
                sb.AppendLine($"{indent}let {childVarName} = {GetAvaloniaControlTypeName(child.Type)}()");
                RenderNode(sb, child, childVarName, indent, rootNamespace, isRoot: false);

                if (node.Type is ControlType.Canvas or ControlType.Grid or ControlType.StackPanel or ControlType.DockPanel or ControlType.WrapPanel)
                {
                    sb.AppendLine($"{indent}{varName}.Children.Add({childVarName}) |> ignore");
                }
                else if (node.Type is ControlType.Border or ControlType.ScrollViewer)
                {
                    sb.AppendLine($"{indent}{varName}.Content <- {childVarName}");
                }
            }
        }
    }

    private static string GetAvaloniaControlTypeName(ControlType type) => type switch
    {
        ControlType.Canvas => "Canvas",
        ControlType.Grid => "Grid",
        ControlType.StackPanel => "StackPanel",
        ControlType.DockPanel => "DockPanel",
        ControlType.WrapPanel => "WrapPanel",
        ControlType.Border => "Border",
        ControlType.ScrollViewer => "ScrollViewer",
        ControlType.Button => "Button",
        ControlType.TextBox => "TextBox",
        ControlType.TextBlock => "TextBlock",
        ControlType.CheckBox => "CheckBox",
        ControlType.RadioButton => "RadioButton",
        ControlType.ComboBox => "ComboBox",
        ControlType.ListBox => "ListBox",
        ControlType.Slider => "Slider",
        ControlType.ProgressBar => "ProgressBar",
        ControlType.DatePicker => "DatePicker",
        ControlType.TimePicker => "TimePicker",
        ControlType.Image => "Image",
        ControlType.PictureBox => "Image",
        ControlType.MediaPlayer => "MediaPlayerControl",
        _ => "Control"
    };

    private static string GetAvaloniaPropertyAccessor(string controlType, string targetProperty)
    {
        return $"{controlType}.{targetProperty}Property";
    }

    private static string EscapeString(string str) => str.Replace("\"", "\\\"");

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return "control";
        return char.ToLowerInvariant(name[0]) + name[1..];
    }
}
