// filepath: src/AFG.Generators/FSharp/FSharpViewModelGenerator.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using AFG.Core.Enums;
using AFG.Core.Models.Ast;
using AFG.Generators.Abstractions;

namespace AFG.Generators.FSharp;

/// <summary>
/// 掃描 UI AST 中的資料綁定與事件命令，生成符合 F# 與 CommunityToolkit.Mvvm 規範之 ViewModel 原始碼。
/// </summary>
public sealed class FSharpViewModelGenerator : ICodeGenerator
{
    public GeneratedSourceFile Generate(FormDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        var allNodes = AstTreeOperations.Flatten(document.RootNode);
        var properties = new Dictionary<string, (string FSharpType, string DefaultValue)>(StringComparer.Ordinal);

        foreach (var node in allNodes)
        {
            foreach (var binding in node.Bindings)
            {
                if (string.IsNullOrWhiteSpace(binding.ViewModelProperty)) continue;
                var propName = NormalizePropertyName(binding.ViewModelProperty);
                if (!properties.ContainsKey(propName))
                {
                    var (fsharpType, defVal) = InferFSharpPropertyType(binding.TargetProperty, node.Type, binding.CustomDataType);
                    properties[propName] = (fsharpType, defVal);
                }
            }
        }

        var commands = new Dictionary<string, (bool IsAsync, string? ParamType)>(StringComparer.Ordinal);
        var allEvents = allNodes.SelectMany(n => n.Events).Concat(document.Events);
        foreach (var evt in allEvents)
        {
            if (!string.IsNullOrWhiteSpace(evt.CommandProperty))
            {
                var cmdName = NormalizeCommandName(evt.CommandProperty);
                var param = evt.GetEffectiveParameters().FirstOrDefault();
                var paramType = param is not null && !string.IsNullOrWhiteSpace(param.Type)
                    ? MapToFSharpType(param.Type)
                    : null;

                if (!commands.ContainsKey(cmdName))
                {
                    commands[cmdName] = (evt.IsAsync, paramType);
                }
            }
        }

        var services = document.InjectedServices ?? [];
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nowarn \"3261\" \"3262\" \"3263\" \"1183\" \"0020\"");
        sb.AppendLine($"namespace {document.RootNamespace}");
        sb.AppendLine();
        sb.AppendLine("open System");
        sb.AppendLine("open System.Collections.ObjectModel");
        sb.AppendLine("open System.ComponentModel");
        sb.AppendLine("open System.Threading.Tasks");
        sb.AppendLine("open CommunityToolkit.Mvvm.ComponentModel");
        sb.AppendLine("open CommunityToolkit.Mvvm.Input");
        sb.AppendLine();

        // 建構子參數 (Injected Services)
        var ctorParams = services.Count > 0
            ? "(" + string.Join(", ", services.Select(s => $"{ToCamelCase(s.InterfaceName.StartsWith('I') ? s.InterfaceName[1..] : s.InterfaceName)}: {s.InterfaceName}")) + ")"
            : "()";

        sb.AppendLine($"type {document.ViewModelClassName}{ctorParams} as this =");
        sb.AppendLine("    inherit ObservableObject()");
        sb.AppendLine();

        // 注入服務內部存取欄位
        if (services.Count > 0)
        {
            sb.AppendLine("    // 注入服務");
            foreach (var svc in services)
            {
                var pName = ToCamelCase(svc.InterfaceName.StartsWith('I') ? svc.InterfaceName[1..] : svc.InterfaceName);
                sb.AppendLine($"    let _{pName} = {pName}");
            }
            sb.AppendLine();
        }

        // 屬性私有欄位
        if (properties.Count > 0)
        {
            sb.AppendLine("    // 可觀察屬性後盾欄位");
            foreach (var (propName, (fsharpType, defVal)) in properties)
            {
                var fieldName = $"_{ToCamelCase(propName)}";
                sb.AppendLine($"    let mutable {fieldName} : {fsharpType} = {defVal}");
            }
            sb.AppendLine();

            sb.AppendLine("    // 可觀察屬性公開存取子");
            foreach (var (propName, (fsharpType, _)) in properties)
            {
                var fieldName = $"_{ToCamelCase(propName)}";
                sb.AppendLine($"    member this.{propName}");
                sb.AppendLine($"        with get() = {fieldName}");
                sb.AppendLine($"        and set(value: {fsharpType}) = this.SetProperty(&{fieldName}, value) |> ignore");
                sb.AppendLine();
            }
        }

        // Commands
        if (commands.Count > 0)
        {
            sb.AppendLine("    // RelayCommand 命令公開屬性");
            foreach (var (cmdName, (isAsync, paramType)) in commands)
            {
                var actionMethodName = cmdName.EndsWith("Command", StringComparison.Ordinal)
                    ? cmdName[..^7]
                    : cmdName;

                if (isAsync)
                {
                    if (paramType is not null)
                    {
                        sb.AppendLine($"    member this.{cmdName} = AsyncRelayCommand<{paramType}>(fun p -> this.{actionMethodName}Async(p))");
                    }
                    else
                    {
                        sb.AppendLine($"    member this.{cmdName} = AsyncRelayCommand(fun () -> this.{actionMethodName}Async())");
                    }
                }
                else
                {
                    if (paramType is not null)
                    {
                        sb.AppendLine($"    member this.{cmdName} = RelayCommand<{paramType}>(fun p -> this.{actionMethodName}(p))");
                    }
                    else
                    {
                        sb.AppendLine($"    member this.{cmdName} = RelayCommand(fun () -> this.{actionMethodName}())");
                    }
                }
            }
            sb.AppendLine();

            sb.AppendLine("    // 命令執行私有處理常式 (Handler Methods)");
            foreach (var (cmdName, (isAsync, paramType)) in commands)
            {
                var actionMethodName = cmdName.EndsWith("Command", StringComparison.Ordinal)
                    ? cmdName[..^7]
                    : cmdName;

                if (isAsync)
                {
                    var paramSig = paramType is not null ? $"(param: {paramType})" : "()";
                    sb.AppendLine($"    member private this.{actionMethodName}Async{paramSig} =");
                    sb.AppendLine("        task {");
                    sb.AppendLine("            do! Task.Yield()");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                }
                else
                {
                    var paramSig = paramType is not null ? $"(param: {paramType})" : "()";
                    sb.AppendLine($"    member private this.{actionMethodName}{paramSig} =");
                    sb.AppendLine("        ()");
                    sb.AppendLine();
                }
            }
        }

        return new GeneratedSourceFile(
            $"{document.ViewModelClassName}.fs",
            sb.ToString().TrimEnd() + Environment.NewLine,
            SourceFileType.ViewModel);
    }

    private static (string FSharpType, string DefaultValue) InferFSharpPropertyType(string targetProperty, ControlType controlType, string? customType)
    {
        if (!string.IsNullOrWhiteSpace(customType))
        {
            var mapped = MapToFSharpType(customType);
            return (mapped, GetDefaultValueForFSharpType(mapped));
        }

        return targetProperty switch
        {
            "Text" or "Content" or "Title" or "Watermark" => ("string", "\"\""),
            "IsChecked" => ("Nullable<bool>", "Nullable(false)"),
            "IsEnabled" or "IsVisible" or "IsReadOnly" => ("bool", "true"),
            "Value" or "Minimum" or "Maximum" => ("float", "0.0"),
            "SelectedIndex" => ("int", "0"),
            "SelectedItem" => ("obj", "null"),
            "ItemsSource" => ("ObservableCollection<obj>", "ObservableCollection<obj>()"),
            _ => ("obj", "null")
        };
    }

    private static string MapToFSharpType(string csharpType) => csharpType.Trim() switch
    {
        "string" or "String" => "string",
        "int" or "Int32" => "int",
        "double" or "Double" => "float",
        "float" or "Single" => "float32",
        "bool" or "Boolean" => "bool",
        "decimal" or "Decimal" => "decimal",
        "object" or "Object" => "obj",
        "object?" => "obj",
        _ => csharpType.Trim()
    };

    private static string GetDefaultValueForFSharpType(string fsharpType) => fsharpType switch
    {
        "string" => "\"\"",
        "int" => "0",
        "float" => "0.0",
        "float32" => "0.0f",
        "bool" => "false",
        "decimal" => "0M",
        _ => "null"
    };

    private static string NormalizePropertyName(string prop) => char.ToUpperInvariant(prop[0]) + prop[1..];
    private static string NormalizeCommandName(string cmd)
    {
        var normalized = char.ToUpperInvariant(cmd[0]) + cmd[1..];
        return normalized.EndsWith("Command", StringComparison.Ordinal) ? normalized : normalized + "Command";
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return "item";
        return char.ToLowerInvariant(name[0]) + name[1..];
    }
}
